#!/usr/bin/env python
# encoding: utf-8

name = "seed"
shortDesc = ""
longDesc = """

"""
autoGenerated=True
entry(
    index = 0,
    label = "Pt + H2O <=> H2OX",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.75, n=0, Ea=(0,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 1,
    label = "Pt + CO <=> OCX",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.84, n=0, Ea=(0,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 2,
    label = "Pt + H2 <=> H2_ads",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Adsorbate;VacantSite]
    Euclidian distance = 0
    family: Surface_Adsorption_vdW"""),
    longDesc = 
"""
Exact match found for rate rule [Adsorbate;VacantSite]
Euclidian distance = 0
family: Surface_Adsorption_vdW
""",
)

entry(
    index = 3,
    label = "Pt + Pt + H2 <=> HX + HX",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.046, n=0, Ea=(0,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 4,
    label = "Pt + Pt + O2 <=> OX + OX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.89e+21,'cm^5/(mol^2*s)'), n=-0.5, Ea=(0,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 5,
    label = "Pt + Pt + CO2 <=> OX + OCX",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(A=0.02, n=0, Ea=(41.84,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [CO2;VacantSite1;VacantSite2]
    Euclidian distance = 2.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Adsorption_Dissociative_Double"""),
    longDesc = 
"""
Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [CO2;VacantSite1;VacantSite2]
Euclidian distance = 2.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Dissociative_Double
""",
)

entry(
    index = 6,
    label = "Pt + CO2 <=> CO2X",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.005, n=0, Ea=(0,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 7,
    label = "OX + OCX <=> Pt + CO2X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.7e+21,'cm^2/(mol*s)'), n=0, Ea=(117600,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 8,
    label = "Pt + CH4 <=> CH4_ads",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Adsorbate;VacantSite]
    Euclidian distance = 0
    family: Surface_Adsorption_vdW"""),
    longDesc = 
"""
Exact match found for rate rule [Adsorbate;VacantSite]
Euclidian distance = 0
family: Surface_Adsorption_vdW
""",
)

entry(
    index = 9,
    label = "HX + CO2X <=> HOX + OCX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1e+19,'cm^2/(mol*s)'), n=0, Ea=(8400,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 10,
    label = "OX + HX <=> Pt + HOX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.28e+21,'cm^2/(mol*s)'), n=0, Ea=(11200,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 11,
    label = "OX + H2OX <=> HOX + HOX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1e+20,'cm^2/(mol*s)'), n=0, Ea=(43100,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 12,
    label = "HX + HOX <=> Pt + H2OX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(2.04e+21,'cm^2/(mol*s)'), n=0, Ea=(66220,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 13,
    label = "Pt + Pt + H2O <=> HX + HOX",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(A=0.02, n=0, Ea=(61.9349,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Average of [H2;VacantSite1;VacantSite2]
    Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [H2O;VacantSite1;VacantSite2]
    Euclidian distance = 3.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Adsorption_Dissociative
    Ea raised from 0.0 to 61.9 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Average of [H2;VacantSite1;VacantSite2]
Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [H2O;VacantSite1;VacantSite2]
Euclidian distance = 3.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Dissociative
Ea raised from 0.0 to 61.9 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 14,
    label = "HOX + H2_ads <=> HX + H2OX",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2e+13,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Donating;Abstracting] for rate rule [H-H;*O-H]
    Euclidian distance = 2.23606797749979
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_Single_vdW
    Kinetics were estimated in this direction instead of the reverse because:
    Both directions are estimates, but this direction is exergonic.
    dGrxn(298 K) = -118.06 kJ/mol
    Ea raised from -64.3 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [Donating;Abstracting] for rate rule [H-H;*O-H]
Euclidian distance = 2.23606797749979
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_Single_vdW
Kinetics were estimated in this direction instead of the reverse because:
Both directions are estimates, but this direction is exergonic.
dGrxn(298 K) = -118.06 kJ/mol
Ea raised from -64.3 to 0.0 kJ/mol.
""",
)

entry(
    index = 15,
    label = "OX + H2_ads <=> HX + HOX",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2e+13,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [H-H;*=O]
    Euclidian distance = 1.4142135623730951
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_vdW
    Ea raised from -18.2 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [H-H;*=O]
Euclidian distance = 1.4142135623730951
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_vdW
Ea raised from -18.2 to 0.0 kJ/mol.
""",
)

entry(
    index = 16,
    label = "Pt + Pt + CH4 <=> HX + CH3X",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.0009, n=0, Ea=(72000,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 17,
    label = "Pt + OX + CH4 <=> HOX + CH3X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(5e+18,'cm^5/(mol^2*s)'), n=0.7, Ea=(42000,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 18,
    label = "Pt + HOX + CH4 <=> H2OX + CH3X",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=1, n=0, Ea=(10000,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 19,
    label = "Pt + CH4_ads <=> HX + CH3X",
    degeneracy = 4.0,
    kinetics = SurfaceArrhenius(A=(1.9516e+16,'m^2/(mol*s)'), n=0, Ea=(52.2248,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Combined;VacantSite] for rate rule [C-H;VacantSite]
    Euclidian distance = 2.0
    Multiplied by reaction path degeneracy 4.0
    family: Surface_Dissociation_vdW"""),
    longDesc = 
"""
Estimated using template [Combined;VacantSite] for rate rule [C-H;VacantSite]
Euclidian distance = 2.0
Multiplied by reaction path degeneracy 4.0
family: Surface_Dissociation_vdW
""",
)

entry(
    index = 20,
    label = "H2_ads + CH3X <=> HX + CH4_ads",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2e+13,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Donating;Abstracting] for rate rule [H-H;*C-3R]
    Euclidian distance = 2.23606797749979
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_Single_vdW
    Kinetics were estimated in this direction instead of the reverse because:
    Both directions are estimates, but this direction is exergonic.
    dGrxn(298 K) = -61.23 kJ/mol
    Ea raised from -29.7 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [Donating;Abstracting] for rate rule [H-H;*C-3R]
Euclidian distance = 2.23606797749979
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_Single_vdW
Kinetics were estimated in this direction instead of the reverse because:
Both directions are estimates, but this direction is exergonic.
dGrxn(298 K) = -61.23 kJ/mol
Ea raised from -29.7 to 0.0 kJ/mol.
""",
)

entry(
    index = 21,
    label = "OX + CH4_ads <=> HOX + CH3X",
    degeneracy = 4.0,
    kinetics = SurfaceArrhenius(A=(4e+13,'m^2/(mol*s)'), n=0, Ea=(23.1008,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [C-R;*=O]
    Euclidian distance = 1.4142135623730951
    Multiplied by reaction path degeneracy 4.0
    family: Surface_Abstraction_vdW
    Ea raised from 11.5 to 23.1 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [C-R;*=O]
Euclidian distance = 1.4142135623730951
Multiplied by reaction path degeneracy 4.0
family: Surface_Abstraction_vdW
Ea raised from 11.5 to 23.1 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 22,
    label = "HOX + CH4_ads <=> H2OX + CH3X",
    degeneracy = 4.0,
    kinetics = SurfaceArrhenius(A=(4e+13,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Donating;Abstracting] for rate rule [C-R;*O-H]
    Euclidian distance = 2.23606797749979
    Multiplied by reaction path degeneracy 4.0
    family: Surface_Abstraction_Single_vdW
    Kinetics were estimated in this direction instead of the reverse because:
    Both directions are estimates, but this direction is exergonic.
    dGrxn(298 K) = -56.82 kJ/mol
    Ea raised from -34.6 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [Donating;Abstracting] for rate rule [C-R;*O-H]
Euclidian distance = 2.23606797749979
Multiplied by reaction path degeneracy 4.0
family: Surface_Abstraction_Single_vdW
Kinetics were estimated in this direction instead of the reverse because:
Both directions are estimates, but this direction is exergonic.
dGrxn(298 K) = -56.82 kJ/mol
Ea raised from -34.6 to 0.0 kJ/mol.
""",
)

entry(
    index = 23,
    label = "HX + CH2X <=> Pt + CH3X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.09e+22,'cm^2/(mol*s)'), n=0, Ea=(0,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 24,
    label = "H2_ads + CH2X <=> HX + CH3X",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2e+13,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [H-H;*=C-2R]
    Euclidian distance = 3.1622776601683795
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_vdW
    Ea raised from -33.8 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [H-H;*=C-2R]
Euclidian distance = 3.1622776601683795
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_vdW
Ea raised from -33.8 to 0.0 kJ/mol.
""",
)

entry(
    index = 25,
    label = "HOX + CH2X <=> OX + CH3X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(5e+17,'m^2/(mol*s)'), n=0, Ea=(40,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Abstracting;*R-H] for rate rule [C=*;*OH]
    Euclidian distance = 2.23606797749979
    family: Surface_Abstraction
    Kinetics were estimated in this direction instead of the reverse because:
    Both directions are estimates, but this direction is exergonic.
    dGrxn(298 K) = -35.61 kJ/mol"""),
    longDesc = 
"""
Estimated using template [Abstracting;*R-H] for rate rule [C=*;*OH]
Euclidian distance = 2.23606797749979
family: Surface_Abstraction
Kinetics were estimated in this direction instead of the reverse because:
Both directions are estimates, but this direction is exergonic.
dGrxn(298 K) = -35.61 kJ/mol
""",
)

entry(
    index = 26,
    label = "H2OX + CH2X <=> HOX + CH3X",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2e+13,'m^2/(mol*s)'), n=0, Ea=(60.1764,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O-R;*=C-2R]
    Euclidian distance = 3.1622776601683795
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_vdW
    Ea raised from 30.6 to 60.2 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O-R;*=C-2R]
Euclidian distance = 3.1622776601683795
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_vdW
Ea raised from 30.6 to 60.2 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 27,
    label = "CH2X + CH4_ads <=> CH3X + CH3X",
    degeneracy = 4.0,
    kinetics = SurfaceArrhenius(A=(4e+13,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [C-R;*=C-2R]
    Euclidian distance = 3.1622776601683795
    Multiplied by reaction path degeneracy 4.0
    family: Surface_Abstraction_vdW
    Ea raised from -4.0 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [C-R;*=C-2R]
Euclidian distance = 3.1622776601683795
Multiplied by reaction path degeneracy 4.0
family: Surface_Abstraction_vdW
Ea raised from -4.0 to 0.0 kJ/mol.
""",
)

entry(
    index = 28,
    label = "HX + CHX <=> Pt + CH2X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.09e+22,'cm^2/(mol*s)'), n=0, Ea=(0,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 29,
    label = "H2_ads + CHX <=> HX + CH2X",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2e+13,'m^2/(mol*s)'), n=0, Ea=(9.0942,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [H-H;*#CH]
    Euclidian distance = 3.1622776601683795
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_vdW
    Ea raised from 2.5 to 9.1 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [H-H;*#CH]
Euclidian distance = 3.1622776601683795
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_vdW
Ea raised from 2.5 to 9.1 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 30,
    label = "OX + CH2X <=> HOX + CHX",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(1e+18,'m^2/(mol*s)'), n=0, Ea=(40,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Abstracting;*R-H] for rate rule [O;*=C-H]
    Euclidian distance = 2.23606797749979
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction
    Kinetics were estimated in this direction instead of the reverse because:
    Both directions are estimates, but this direction is exergonic.
    dGrxn(298 K) = -45.28 kJ/mol"""),
    longDesc = 
"""
Estimated using template [Abstracting;*R-H] for rate rule [O;*=C-H]
Euclidian distance = 2.23606797749979
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction
Kinetics were estimated in this direction instead of the reverse because:
Both directions are estimates, but this direction is exergonic.
dGrxn(298 K) = -45.28 kJ/mol
""",
)

entry(
    index = 31,
    label = "H2OX + CHX <=> HOX + CH2X",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2e+13,'m^2/(mol*s)'), n=0, Ea=(133.374,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O-R;*#CH]
    Euclidian distance = 3.1622776601683795
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_vdW
    Ea raised from 66.8 to 133.4 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O-R;*#CH]
Euclidian distance = 3.1622776601683795
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_vdW
Ea raised from 66.8 to 133.4 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 32,
    label = "CHX + CH4_ads <=> CH2X + CH3X",
    degeneracy = 4.0,
    kinetics = SurfaceArrhenius(A=(4e+13,'m^2/(mol*s)'), n=0, Ea=(65.9687,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [C-R;*#CH]
    Euclidian distance = 3.1622776601683795
    Multiplied by reaction path degeneracy 4.0
    family: Surface_Abstraction_vdW
    Ea raised from 32.2 to 66.0 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [C-R;*#CH]
Euclidian distance = 3.1622776601683795
Multiplied by reaction path degeneracy 4.0
family: Surface_Abstraction_vdW
Ea raised from 32.2 to 66.0 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 33,
    label = "CH2X + CH2X <=> CHX + CH3X",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(1e+18,'m^2/(mol*s)'), n=0, Ea=(40,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Abstracting;*R-H] for rate rule [C=*;*=C-H]
    Euclidian distance = 2.8284271247461903
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction
    Kinetics were estimated in this direction instead of the reverse because:
    Both directions are estimates, but this direction is exergonic.
    dGrxn(298 K) = -80.89 kJ/mol"""),
    longDesc = 
"""
Estimated using template [Abstracting;*R-H] for rate rule [C=*;*=C-H]
Euclidian distance = 2.8284271247461903
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction
Kinetics were estimated in this direction instead of the reverse because:
Both directions are estimates, but this direction is exergonic.
dGrxn(298 K) = -80.89 kJ/mol
""",
)

entry(
    index = 34,
    label = "OX + CX <=> Pt + OCX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.7e+19,'cm^2/(mol*s)'), n=0, Ea=(0,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 35,
    label = "Pt + CHX <=> HX + CX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.09e+22,'cm^2/(mol*s)'), n=0, Ea=(0,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 36,
    label = "H2 + CX <=> CH2X",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.04, n=0, Ea=(29700,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 37,
    label = "H2_ads + CX <=> HX + CHX",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2e+13,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [H-H;*$C]
    Euclidian distance = 2.23606797749979
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_vdW
    Ea raised from -50.1 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [H-H;*$C]
Euclidian distance = 2.23606797749979
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_vdW
Ea raised from -50.1 to 0.0 kJ/mol.
""",
)

entry(
    index = 38,
    label = "HOX + CX <=> OX + CHX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(5e+17,'m^2/(mol*s)'), n=0, Ea=(40,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Abstracting;*R-H] for rate rule [C$*;*OH]
    Euclidian distance = 2.23606797749979
    family: Surface_Abstraction
    Kinetics were estimated in this direction instead of the reverse because:
    Both directions are estimates, but this direction is exergonic.
    dGrxn(298 K) = -57.88 kJ/mol"""),
    longDesc = 
"""
Estimated using template [Abstracting;*R-H] for rate rule [C$*;*OH]
Euclidian distance = 2.23606797749979
family: Surface_Abstraction
Kinetics were estimated in this direction instead of the reverse because:
Both directions are estimates, but this direction is exergonic.
dGrxn(298 K) = -57.88 kJ/mol
""",
)

entry(
    index = 39,
    label = "H2OX + CX <=> HOX + CHX",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2e+13,'m^2/(mol*s)'), n=0, Ea=(28.349,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O-R;*$C]
    Euclidian distance = 2.23606797749979
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_vdW
    Ea raised from 14.3 to 28.3 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O-R;*$C]
Euclidian distance = 2.23606797749979
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_vdW
Ea raised from 14.3 to 28.3 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 40,
    label = "CX + CH4_ads <=> CHX + CH3X",
    degeneracy = 4.0,
    kinetics = SurfaceArrhenius(A=(4e+13,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [C-R;*$C]
    Euclidian distance = 2.23606797749979
    Multiplied by reaction path degeneracy 4.0
    family: Surface_Abstraction_vdW
    Ea raised from -20.3 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [C-R;*$C]
Euclidian distance = 2.23606797749979
Multiplied by reaction path degeneracy 4.0
family: Surface_Abstraction_vdW
Ea raised from -20.3 to 0.0 kJ/mol.
""",
)

entry(
    index = 41,
    label = "CX + CH3X <=> CHX + CH2X",
    degeneracy = 3.0,
    kinetics = SurfaceArrhenius(A=(1.5e+18,'m^2/(mol*s)'), n=0, Ea=(40,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Abstracting;*R-H] for rate rule [C$*;*-C-H]
    Euclidian distance = 2.8284271247461903
    Multiplied by reaction path degeneracy 3.0
    family: Surface_Abstraction
    Kinetics were estimated in this direction instead of the reverse because:
    Both directions are estimates, but this direction is exergonic.
    dGrxn(298 K) = -22.28 kJ/mol"""),
    longDesc = 
"""
Estimated using template [Abstracting;*R-H] for rate rule [C$*;*-C-H]
Euclidian distance = 2.8284271247461903
Multiplied by reaction path degeneracy 3.0
family: Surface_Abstraction
Kinetics were estimated in this direction instead of the reverse because:
Both directions are estimates, but this direction is exergonic.
dGrxn(298 K) = -22.28 kJ/mol
""",
)

entry(
    index = 42,
    label = "CX + CH2X <=> CHX + CHX",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(1e+18,'m^2/(mol*s)'), n=0, Ea=(40,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Abstracting;*R-H] for rate rule [C$*;*=C-H]
    Euclidian distance = 2.8284271247461903
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction
    Kinetics were estimated in this direction instead of the reverse because:
    Both directions are estimates, but this direction is exergonic.
    dGrxn(298 K) = -103.16 kJ/mol"""),
    longDesc = 
"""
Estimated using template [Abstracting;*R-H] for rate rule [C$*;*=C-H]
Euclidian distance = 2.8284271247461903
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction
Kinetics were estimated in this direction instead of the reverse because:
Both directions are estimates, but this direction is exergonic.
dGrxn(298 K) = -103.16 kJ/mol
""",
)

entry(
    index = 43,
    label = "HX + OCX <=> Pt + COH_ads",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.048e+17,'m^2/(mol*s)'), n=0, Ea=(119.572,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate1;Adsorbate2] for rate rule [*=C=O;H-*]
    Euclidian distance = 3.1622776601683795
    family: Surface_Dissociation_Beta"""),
    longDesc = 
"""
Estimated using template [Adsorbate1;Adsorbate2] for rate rule [*=C=O;H-*]
Euclidian distance = 3.1622776601683795
family: Surface_Dissociation_Beta
""",
)

entry(
    index = 44,
    label = "H2OX + CX <=> HX + COH_ads",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2e+13,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [AdsorbateVdW;*$C]
    Euclidian distance = 2.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_vdW
    Ea raised from -33.3 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [AdsorbateVdW;*$C]
Euclidian distance = 2.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_vdW
Ea raised from -33.3 to 0.0 kJ/mol.
""",
)

entry(
    index = 45,
    label = "Pt + COH_ads <=> HOX + CX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1e+17,'m^2/(mol*s)'), n=0, Ea=(308.909,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Combined;VacantSite] for rate rule [C-O;VacantSite]
    Euclidian distance = 2.0
    family: Surface_Dissociation"""),
    longDesc = 
"""
Estimated using template [Combined;VacantSite] for rate rule [C-O;VacantSite]
Euclidian distance = 2.0
family: Surface_Dissociation
""",
)

