#!/usr/bin/env python
# encoding: utf-8

name = "seed"
shortDesc = ""
longDesc = """

"""
autoGenerated=True
entry(
    index = 0,
    label = "site + H2 <=> [H][H].[Pt]",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""From training reaction 5 used for Adsorbate;VacantSite
    Exact match found for rate rule [Adsorbate;VacantSite]
    Euclidian distance = 0
    family: Surface_Adsorption_vdW"""),
    longDesc = 
"""
From training reaction 5 used for Adsorbate;VacantSite
Exact match found for rate rule [Adsorbate;VacantSite]
Euclidian distance = 0
family: Surface_Adsorption_vdW
""",
)

entry(
    index = 1,
    label = "site + site + H2 <=> HX + HX",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.032, n=0, Ea=(0,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/Deutschmann_Ni
""",
)

entry(
    index = 2,
    label = "site + site + CO2 <=> OX + OCX",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(A=0.02, n=0, Ea=(41.84,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [CO2;VacantSite1;VacantSite2]
    Euclidian distance = 2.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Adsorption_Dissociative_Double"""),
    longDesc = 
"""
Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [CO2;VacantSite1;VacantSite2]
Euclidian distance = 2.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Dissociative_Double
""",
)

entry(
    index = 3,
    label = "site + CO <=> OCX",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.5, n=0, Ea=(0,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/Deutschmann_Ni
""",
)

entry(
    index = 4,
    label = "[H][H].[Pt] + OCX <=> HX + CXHO",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2.07394e+13,'m^2/(mol*s)'), n=0.936633, Ea=(121.703,'kJ/mol'), T0=(1,'K'), Tmin=(303.03,'K'), Tmax=(2000,'K'), comment="""Estimated using template [AdsorbateVdW;*=C=R] for rate rule [H-H;*=C=R]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;*=C=R] for rate rule [H-H;*=C=R]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 5,
    label = "HX + OCX <=> site + CXHO",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.14e+17,'m^2/(mol*s)'), n=0, Ea=(22.8299,'kcal/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Matched reaction 26 OCX_3 + HX_5 <=> CXHO_1 + Ni_4 in Surface_Dissociation/training
    This reaction matched rate rule [C-H;VacantSite]
    family: Surface_Dissociation
    metal: None"""),
    longDesc = 
"""
Matched reaction 26 OCX_3 + HX_5 <=> CXHO_1 + Ni_4 in Surface_Dissociation/training
This reaction matched rate rule [C-H;VacantSite]
family: Surface_Dissociation
metal: None
""",
)

entry(
    index = 6,
    label = "site + site + H2O <=> HX + HOX",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(A=0.032, n=0, Ea=(18.8723,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [H2O;VacantSite1;VacantSite2]
    Euclidian distance = 3.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Adsorption_Dissociative
    Ea raised from 0.0 to 18.9 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [H2O;VacantSite1;VacantSite2]
Euclidian distance = 3.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Dissociative
Ea raised from 0.0 to 18.9 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 7,
    label = "OX + [H][H].[Pt] <=> HX + HOX",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(4.87241e+15,'m^2/(mol*s)'), n=0.639876, Ea=(120.26,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [AdsorbateVdW;*=O] for rate rule [H-H;*=O]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;*=O] for rate rule [H-H;*=O]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 8,
    label = "site + HOX <=> OX + HX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(7.452e+17,'m^2/(mol*s)'), n=0, Ea=(38.7417,'kcal/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Matched reaction 15 HOX_1 + Ni_4 <=> OX_3 + HX_5 in Surface_Dissociation/training
    This reaction matched rate rule [O-H;VacantSite]
    family: Surface_Dissociation
    metal: None"""),
    longDesc = 
"""
Matched reaction 15 HOX_1 + Ni_4 <=> OX_3 + HX_5 in Surface_Dissociation/training
This reaction matched rate rule [O-H;VacantSite]
family: Surface_Dissociation
metal: None
""",
)

entry(
    index = 9,
    label = "OX + CXHO <=> HOX + OCX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.298e+17,'m^2/(mol*s)'), n=0, Ea=(0,'kcal/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Matched reaction 39 O* + HCO* <=> OH* + CO* in Surface_Abstraction/training
    This reaction matched rate rule [O;*-C-H]
    family: Surface_Abstraction
    metal: None"""),
    longDesc = 
"""
Matched reaction 39 O* + HCO* <=> OH* + CO* in Surface_Abstraction/training
This reaction matched rate rule [O;*-C-H]
family: Surface_Abstraction
metal: None
""",
)

entry(
    index = 10,
    label = "site + H2O <=> O.[Pt]",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(0,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Matched reaction 5 H2O + X <=> H2OX in Surface_Adsorption_vdW/training
    This reaction matched rate rule [Adsorbate;VacantSite]
    family: Surface_Adsorption_vdW
    metal: None"""),
    longDesc = 
"""
Matched reaction 5 H2O + X <=> H2OX in Surface_Adsorption_vdW/training
This reaction matched rate rule [Adsorbate;VacantSite]
family: Surface_Adsorption_vdW
metal: None
""",
)

entry(
    index = 11,
    label = "HOX + [H][H].[Pt] <=> HX + O.[Pt]",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2e+13,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Donating;Abstracting] for rate rule [H-H;*O-H]
    Euclidian distance = 2.23606797749979
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_Single_vdW
    Ea raised from -43.2 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [Donating;Abstracting] for rate rule [H-H;*O-H]
Euclidian distance = 2.23606797749979
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_Single_vdW
Ea raised from -43.2 to 0.0 kJ/mol.
""",
)

entry(
    index = 12,
    label = "site + O.[Pt] <=> HX + HOX",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(4.879e+15,'m^2/(mol*s)'), n=0, Ea=(8.70585,'kcal/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Matched reaction 14 H2O* + X_4 <=> OH* + H* in Surface_Dissociation_vdW/training
    This reaction matched rate rule [O-H;VacantSite]
    family: Surface_Dissociation_vdW
    metal: None
    Ea raised from 20.3 to 36.4 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Matched reaction 14 H2O* + X_4 <=> OH* + H* in Surface_Dissociation_vdW/training
This reaction matched rate rule [O-H;VacantSite]
family: Surface_Dissociation_vdW
metal: None
Ea raised from 20.3 to 36.4 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 13,
    label = "HOX + CXHO <=> O.[Pt] + OCX",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(3.261e+17,'m^2/(mol*s)'), n=0, Ea=(6.91816,'kcal/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Matched reaction 40 OH_2* + HCO* <=> H2O* + CO* in Surface_Abstraction_vdW/training
    This reaction matched rate rule [O-R;*=C=R]
    family: Surface_Abstraction_vdW
    metal: None"""),
    longDesc = 
"""
Matched reaction 40 OH_2* + HCO* <=> H2O* + CO* in Surface_Abstraction_vdW/training
This reaction matched rate rule [O-R;*=C=R]
family: Surface_Abstraction_vdW
metal: None
""",
)

entry(
    index = 14,
    label = "HOX + HOX <=> OX + O.[Pt]",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(5.691e+16,'m^2/(mol*s)'), n=0, Ea=(14.0669,'kcal/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Matched reaction 16 OH_2* + OH_4* <=> H2O* + O* in Surface_Abstraction_vdW/training
    This reaction matched rate rule [O-R;*=O]
    family: Surface_Abstraction_vdW
    metal: None"""),
    longDesc = 
"""
Matched reaction 16 OH_2* + OH_4* <=> H2O* + O* in Surface_Abstraction_vdW/training
This reaction matched rate rule [O-R;*=O]
family: Surface_Abstraction_vdW
metal: None
""",
)

entry(
    index = 15,
    label = "HX + C=O.[Pt] <=> [H][H].[Pt] + CXHO",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2e+13,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Donating;Abstracting] for rate rule [C-R;Abstracting]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_Single_vdW
    Ea raised from -13.3 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [Donating;Abstracting] for rate rule [C-R;Abstracting]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_Single_vdW
Ea raised from -13.3 to 0.0 kJ/mol.
""",
)

entry(
    index = 16,
    label = "HX + CXHO <=> site + C=O.[Pt]",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(1.932e+17,'m^2/(mol*s)'), n=0, Ea=(18.2517,'kcal/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Matched reaction 30 HCO* + H* <=> CH2O* + X_4 in Surface_Dissociation_vdW/training
    This reaction matched rate rule [C-H;VacantSite]
    family: Surface_Dissociation_vdW
    metal: None
    Ea raised from 45.3 to 76.4 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Matched reaction 30 HCO* + H* <=> CH2O* + X_4 in Surface_Dissociation_vdW/training
This reaction matched rate rule [C-H;VacantSite]
family: Surface_Dissociation_vdW
metal: None
Ea raised from 45.3 to 76.4 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 17,
    label = "OCX + C=O.[Pt] <=> CXHO + CXHO",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2.07394e+13,'m^2/(mol*s)'), n=0.936633, Ea=(121.703,'kJ/mol'), T0=(1,'K'), Tmin=(303.03,'K'), Tmax=(2000,'K'), comment="""Estimated using template [AdsorbateVdW;*=C=R] for rate rule [C-R;*=C=R]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;*=C=R] for rate rule [C-R;*=C=R]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 18,
    label = "OX + C=O.[Pt] <=> HOX + CXHO",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2.81e+20,'m^2/(mol*s)'), n=-0.101, Ea=(92.7,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""From training reaction 21 used for C-R;*=O
    Exact match found for rate rule [C-R;*=O]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
From training reaction 21 used for C-R;*=O
Exact match found for rate rule [C-R;*=O]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 19,
    label = "HOX + C=O.[Pt] <=> O.[Pt] + CXHO",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2e+13,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Donating;Abstracting] for rate rule [C-R;*O-H]
    Euclidian distance = 2.23606797749979
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_Single_vdW
    Ea raised from -56.5 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [Donating;Abstracting] for rate rule [C-R;*O-H]
Euclidian distance = 2.23606797749979
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_Single_vdW
Ea raised from -56.5 to 0.0 kJ/mol.
""",
)

entry(
    index = 20,
    label = "[H][H].[Pt] + C=O.[Pt] <=> HX + CO[Pt]",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(1.40689e+10,'m^2/(mol*s)'), n=1.27097, Ea=(144.01,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Adsorbate1;Adsorbate2] for rate rule [O=C;H-H]
    Euclidian distance = 2.23606797749979
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Dual_Adsorption_vdW"""),
    longDesc = 
"""
Estimated using template [Adsorbate1;Adsorbate2] for rate rule [O=C;H-H]
Euclidian distance = 2.23606797749979
Multiplied by reaction path degeneracy 2.0
family: Surface_Dual_Adsorption_vdW
""",
)

entry(
    index = 21,
    label = "HX + C=O.[Pt] <=> site + CO[Pt]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(6.167e+17,'m^2/(mol*s)'), n=0, Ea=(5.53453,'kcal/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Matched reaction 24 CH2O* + H* <=> CH3O_1* + X_5 in Surface_Addition_Single_vdW/training
    This reaction matched rate rule [O=C;H*]
    family: Surface_Addition_Single_vdW
    metal: None"""),
    longDesc = 
"""
Matched reaction 24 CH2O* + H* <=> CH3O_1* + X_5 in Surface_Addition_Single_vdW/training
This reaction matched rate rule [O=C;H*]
family: Surface_Addition_Single_vdW
metal: None
""",
)

entry(
    index = 22,
    label = "CXHO + C=O.[Pt] <=> OCX + CO[Pt]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.398e+17,'m^2/(mol*s)'), n=0, Ea=(0,'kcal/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Matched reaction 44 CH2O* + HCO* <=> CH3O* + CO* in Surface_Adsorption_Abstraction_vdW/training
    This reaction matched rate rule [O=C;*C-H]
    family: Surface_Adsorption_Abstraction_vdW
    metal: None"""),
    longDesc = 
"""
Matched reaction 44 CH2O* + HCO* <=> CH3O* + CO* in Surface_Adsorption_Abstraction_vdW/training
This reaction matched rate rule [O=C;*C-H]
family: Surface_Adsorption_Abstraction_vdW
metal: None
""",
)

entry(
    index = 23,
    label = "HOX + C=O.[Pt] <=> OX + CO[Pt]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.814e+16,'m^2/(mol*s)'), n=0, Ea=(40.5238,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [O=C;Adsorbate1] for rate rule [O=C;*O-R]
    Euclidian distance = 1.0
    family: Surface_Adsorption_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [O=C;Adsorbate1] for rate rule [O=C;*O-R]
Euclidian distance = 1.0
family: Surface_Adsorption_Abstraction_vdW
""",
)

entry(
    index = 24,
    label = "O.[Pt] + C=O.[Pt] <=> HOX + CO[Pt]",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(1.40689e+10,'m^2/(mol*s)'), n=1.27097, Ea=(144.01,'kJ/mol'), T0=(1,'K'), Tmin=(303.03,'K'), Tmax=(2000,'K'), comment="""Estimated using template [Adsorbate1;O-R] for rate rule [O=C;O-R]
    Euclidian distance = 2.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Dual_Adsorption_vdW"""),
    longDesc = 
"""
Estimated using template [Adsorbate1;O-R] for rate rule [O=C;O-R]
Euclidian distance = 2.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Dual_Adsorption_vdW
""",
)

entry(
    index = 25,
    label = "C=O.[Pt] + C=O.[Pt] <=> CXHO + CO[Pt]",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(1.40689e+10,'m^2/(mol*s)'), n=1.27097, Ea=(144.01,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Adsorbate1;Adsorbate2] for rate rule [O=C;C-R]
    Euclidian distance = 2.23606797749979
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Dual_Adsorption_vdW"""),
    longDesc = 
"""
Estimated using template [Adsorbate1;Adsorbate2] for rate rule [O=C;C-R]
Euclidian distance = 2.23606797749979
Multiplied by reaction path degeneracy 2.0
family: Surface_Dual_Adsorption_vdW
""",
)

entry(
    index = 26,
    label = "site + CH4 <=> C.[Pt]",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.008, n=0, Ea=(0,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Matched reaction 11 CH4 + X <=> CH4X in Surface_Adsorption_vdW/training
    This reaction matched rate rule [Adsorbate;VacantSite]
    family: Surface_Adsorption_vdW
    metal: None"""),
    longDesc = 
"""
Matched reaction 11 CH4 + X <=> CH4X in Surface_Adsorption_vdW/training
This reaction matched rate rule [Adsorbate;VacantSite]
family: Surface_Adsorption_vdW
metal: None
""",
)

entry(
    index = 27,
    label = "OX + C.[Pt] <=> HX + CO[Pt]",
    degeneracy = 4.0,
    kinetics = SurfaceArrhenius(A=(9.74482e+15,'m^2/(mol*s)'), n=0.639876, Ea=(120.26,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [AdsorbateVdW;*=O]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 4.0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using an average for rate rule [AdsorbateVdW;*=O]
Euclidian distance = 0
Multiplied by reaction path degeneracy 4.0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 28,
    label = "site + site + CH4 <=> HX + C[Pt]",
    degeneracy = 4.0,
    kinetics = StickingCoefficient(A=0.064, n=0, Ea=(18.2685,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [C-H;VacantSite1;VacantSite2]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 4.0
    family: Surface_Adsorption_Dissociative
    Ea raised from 0.0 to 18.3 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [C-H;VacantSite1;VacantSite2]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 4.0
family: Surface_Adsorption_Dissociative
Ea raised from 0.0 to 18.3 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 29,
    label = "site + CO[Pt] <=> OX + C[Pt]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(8.733e+16,'m^2/(mol*s)'), n=0, Ea=(45.3481,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""From training reaction 28 used for O-C;VacantSite
    Exact match found for rate rule [O-C;VacantSite]
    Euclidian distance = 0
    family: Surface_Dissociation"""),
    longDesc = 
"""
From training reaction 28 used for O-C;VacantSite
Exact match found for rate rule [O-C;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation
""",
)

entry(
    index = 30,
    label = "site + C.[Pt] <=> HX + C[Pt]",
    degeneracy = 4.0,
    kinetics = SurfaceArrhenius(A=(1.54e+17,'m^2/(mol*s)'), n=0.087, Ea=(55800,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Matched reaction 12 CH4* + X_4 <=> CH3* + H* in Surface_Dissociation_vdW/training
    This reaction matched rate rule [C-H;VacantSite]
    family: Surface_Dissociation_vdW
    metal: None"""),
    longDesc = 
"""
Matched reaction 12 CH4* + X_4 <=> CH3* + H* in Surface_Dissociation_vdW/training
This reaction matched rate rule [C-H;VacantSite]
family: Surface_Dissociation_vdW
metal: None
""",
)

entry(
    index = 31,
    label = "[H][H].[Pt] + C[Pt] <=> HX + C.[Pt]",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2e+13,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Donating;Abstracting] for rate rule [H-H;*C-3R]
    Euclidian distance = 2.23606797749979
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_Single_vdW
    Ea raised from -37.0 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [Donating;Abstracting] for rate rule [H-H;*C-3R]
Euclidian distance = 2.23606797749979
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_Single_vdW
Ea raised from -37.0 to 0.0 kJ/mol.
""",
)

entry(
    index = 32,
    label = "OCX + C.[Pt] <=> CXHO + C[Pt]",
    degeneracy = 4.0,
    kinetics = SurfaceArrhenius(A=(4.14787e+13,'m^2/(mol*s)'), n=0.936633, Ea=(121.703,'kJ/mol'), T0=(1,'K'), Tmin=(303.03,'K'), Tmax=(2000,'K'), comment="""Estimated using template [AdsorbateVdW;*=C=R] for rate rule [C-R;*=C=R]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 4.0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;*=C=R] for rate rule [C-R;*=C=R]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 4.0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 33,
    label = "OX + C.[Pt] <=> HOX + C[Pt]",
    degeneracy = 4.0,
    kinetics = SurfaceArrhenius(A=(5.62e+20,'m^2/(mol*s)'), n=-0.101, Ea=(92700,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Matched reaction 21 CH4* + O* <=> CH3* + OH_4* in Surface_Abstraction_vdW/training
    This reaction matched rate rule [C-R;*=O]
    family: Surface_Abstraction_vdW
    metal: None"""),
    longDesc = 
"""
Matched reaction 21 CH4* + O* <=> CH3* + OH_4* in Surface_Abstraction_vdW/training
This reaction matched rate rule [C-R;*=O]
family: Surface_Abstraction_vdW
metal: None
""",
)

entry(
    index = 34,
    label = "C=O.[Pt] + C[Pt] <=> CXHO + C.[Pt]",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2e+13,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Donating;Abstracting] for rate rule [C-R;*C-3R]
    Euclidian distance = 2.23606797749979
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_Single_vdW
    Ea raised from -50.2 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [Donating;Abstracting] for rate rule [C-R;*C-3R]
Euclidian distance = 2.23606797749979
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_Single_vdW
Ea raised from -50.2 to 0.0 kJ/mol.
""",
)

entry(
    index = 35,
    label = "HOX + C.[Pt] <=> O.[Pt] + C[Pt]",
    degeneracy = 4.0,
    kinetics = SurfaceArrhenius(A=(4e+13,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Donating;Abstracting] for rate rule [C-R;*O-H]
    Euclidian distance = 2.23606797749979
    Multiplied by reaction path degeneracy 4.0
    family: Surface_Abstraction_Single_vdW
    Ea raised from -6.2 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [Donating;Abstracting] for rate rule [C-R;*O-H]
Euclidian distance = 2.23606797749979
Multiplied by reaction path degeneracy 4.0
family: Surface_Abstraction_Single_vdW
Ea raised from -6.2 to 0.0 kJ/mol.
""",
)

entry(
    index = 36,
    label = "C=O.[Pt] + C.[Pt] <=> C[Pt] + CO[Pt]",
    degeneracy = 4.0,
    kinetics = SurfaceArrhenius(A=(2.81379e+10,'m^2/(mol*s)'), n=1.27097, Ea=(144.01,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Adsorbate1;Adsorbate2] for rate rule [O=C;C-R]
    Euclidian distance = 2.23606797749979
    Multiplied by reaction path degeneracy 4.0
    family: Surface_Dual_Adsorption_vdW"""),
    longDesc = 
"""
Estimated using template [Adsorbate1;Adsorbate2] for rate rule [O=C;C-R]
Euclidian distance = 2.23606797749979
Multiplied by reaction path degeneracy 4.0
family: Surface_Dual_Adsorption_vdW
""",
)

entry(
    index = 37,
    label = "site + CO2 <=> CO2X",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=7e-06, n=0, Ea=(26444.6,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Matched reaction 7 CO2 + X <=> CO2X in Surface_Adsorption_vdW/training
    This reaction matched rate rule [Adsorbate;VacantSite]
    family: Surface_Adsorption_vdW
    metal: None
    Ea raised from 0.0 to 26.4 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Matched reaction 7 CO2 + X <=> CO2X in Surface_Adsorption_vdW/training
This reaction matched rate rule [Adsorbate;VacantSite]
family: Surface_Adsorption_vdW
metal: None
Ea raised from 0.0 to 26.4 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 38,
    label = "OX + OCX <=> site + CO2X",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(4.06e+16,'m^2/(mol*s)'), n=0, Ea=(26.7542,'kcal/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Matched reaction 9 CO* + O* <=> CO2* + X_4 in Surface_Dissociation_Double_vdW/training
    This reaction matched rate rule [CO2;VacantSite]
    family: Surface_Dissociation_Double_vdW
    metal: None
    Ea raised from 62.7 to 111.9 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Matched reaction 9 CO* + O* <=> CO2* + X_4 in Surface_Dissociation_Double_vdW/training
This reaction matched rate rule [CO2;VacantSite]
family: Surface_Dissociation_Double_vdW
metal: None
Ea raised from 62.7 to 111.9 kJ/mol to match endothermicity of reaction.
""",
)

