#!/usr/bin/env python
# encoding: utf-8

name = "seed_edge"
shortDesc = ""
longDesc = """

"""
autoGenerated=True
entry(
    index = 0,
    label = "H2OX + OCX <=> HOX + HCO_ads",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2e+13,'m^2/(mol*s)'), n=0, Ea=(165.323,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O-R;*=C=R]
    Euclidian distance = 3.1622776601683795
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_vdW
    Ea raised from 82.3 to 165.3 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O-R;*=C=R]
Euclidian distance = 3.1622776601683795
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_vdW
Ea raised from 82.3 to 165.3 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 1,
    label = "H2OX + OCX <=> HX + HOCOX",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2e+13,'m^2/(mol*s)'), n=0, Ea=(162.143,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [AdsorbateVdW;*=C=R]
    Euclidian distance = 3.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_vdW
    Ea raised from 80.5 to 162.1 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [AdsorbateVdW;*=C=R]
Euclidian distance = 3.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_vdW
Ea raised from 80.5 to 162.1 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 2,
    label = "Pt + Pt + OCCO(S) <=> OCX + OCX",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.01, n=0, Ea=(41.84,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [CC;VacantSite1;VacantSite2]
    Euclidian distance = 1.0
    family: Surface_Adsorption_Dissociative_Double"""),
    longDesc = 
"""
Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [CC;VacantSite1;VacantSite2]
Euclidian distance = 1.0
family: Surface_Adsorption_Dissociative_Double
""",
)

entry(
    index = 3,
    label = "Pt + OCCO(S)-2 <=> OCX + OCX",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2e+13,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [AdsorbateVdW;VacantSite]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Dissociation_Double_vdW
    Ea raised from -293.3 to 0.0 kJ/mol."""),
    longDesc = 
"""
Exact match found for rate rule [AdsorbateVdW;VacantSite]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Dissociation_Double_vdW
Ea raised from -293.3 to 0.0 kJ/mol.
""",
)

entry(
    index = 4,
    label = "H2_ads + OCX <=> HX + HCO_ads",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2e+13,'m^2/(mol*s)'), n=0, Ea=(41.0439,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [H-H;*=C=R]
    Euclidian distance = 3.1622776601683795
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_vdW
    Ea raised from 18.0 to 41.0 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [H-H;*=C=R]
Euclidian distance = 3.1622776601683795
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_vdW
Ea raised from 18.0 to 41.0 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 5,
    label = "Pt + H <=> HX",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Adsorbate;VacantSite]
    Euclidian distance = 0
    family: Surface_Adsorption_Single"""),
    longDesc = 
"""
Exact match found for rate rule [Adsorbate;VacantSite]
Euclidian distance = 0
family: Surface_Adsorption_Single
""",
)

entry(
    index = 6,
    label = "HX + CO2 <=> formyloxyX",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(A=1e-05, n=0, Ea=(148.526,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate1;Gas] for rate rule [*H;R=R]
    Euclidian distance = 1.4142135623730951
    Multiplied by reaction path degeneracy 2.0
    family: Surface_EleyRideal_Addition_Multiple_Bond"""),
    longDesc = 
"""
Estimated using template [Adsorbate1;Gas] for rate rule [*H;R=R]
Euclidian distance = 1.4142135623730951
Multiplied by reaction path degeneracy 2.0
family: Surface_EleyRideal_Addition_Multiple_Bond
""",
)

entry(
    index = 7,
    label = "HX + CO2 <=> HOCOX",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(A=1e-05, n=0, Ea=(68.66,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate1;Gas] for rate rule [*H;R=R]
    Euclidian distance = 1.4142135623730951
    Multiplied by reaction path degeneracy 2.0
    family: Surface_EleyRideal_Addition_Multiple_Bond"""),
    longDesc = 
"""
Estimated using template [Adsorbate1;Gas] for rate rule [*H;R=R]
Euclidian distance = 1.4142135623730951
Multiplied by reaction path degeneracy 2.0
family: Surface_EleyRideal_Addition_Multiple_Bond
""",
)

entry(
    index = 8,
    label = "Pt + HCO_ads <=> HX + OCX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1e+17,'m^2/(mol*s)'), n=0, Ea=(114.571,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Combined;VacantSite] for rate rule [C-H;VacantSite]
    Euclidian distance = 2.0
    family: Surface_Dissociation"""),
    longDesc = 
"""
Estimated using template [Combined;VacantSite] for rate rule [C-H;VacantSite]
Euclidian distance = 2.0
family: Surface_Dissociation
""",
)

entry(
    index = 9,
    label = "OX + H2OX <=> HX + OOH_ads",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2e+13,'m^2/(mol*s)'), n=0, Ea=(250.811,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [AdsorbateVdW;*=O]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_vdW
    Ea raised from 126.0 to 250.8 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [AdsorbateVdW;*=O]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_vdW
Ea raised from 126.0 to 250.8 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 10,
    label = "Pt + O2(S) <=> OX + OX",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2e+13,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [AdsorbateVdW;VacantSite]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Dissociation_Double_vdW
    Ea raised from -177.0 to 0.0 kJ/mol."""),
    longDesc = 
"""
Exact match found for rate rule [AdsorbateVdW;VacantSite]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Dissociation_Double_vdW
Ea raised from -177.0 to 0.0 kJ/mol.
""",
)

entry(
    index = 11,
    label = "H2OX + CO2X <=> HOX + formyloxyX",
    degeneracy = 4.0,
    kinetics = SurfaceArrhenius(A=(4e+13,'m^2/(mol*s)'), n=0, Ea=(200.219,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate1;Adsorbate2] for rate rule [O=C=O;O-R]
    Euclidian distance = 3.1622776601683795
    Multiplied by reaction path degeneracy 4.0
    family: Surface_Dual_Adsorption_vdW
    Ea raised from 0.0 to 200.2 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [Adsorbate1;Adsorbate2] for rate rule [O=C=O;O-R]
Euclidian distance = 3.1622776601683795
Multiplied by reaction path degeneracy 4.0
family: Surface_Dual_Adsorption_vdW
Ea raised from 0.0 to 200.2 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 12,
    label = "H2OX + CO2X <=> HOX + HOCOX",
    degeneracy = 4.0,
    kinetics = SurfaceArrhenius(A=(4e+13,'m^2/(mol*s)'), n=0, Ea=(117.662,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate1;Adsorbate2] for rate rule [CO2;O-R]
    Euclidian distance = 4.123105625617661
    Multiplied by reaction path degeneracy 4.0
    family: Surface_Dual_Adsorption_vdW
    Ea raised from 0.0 to 117.7 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [Adsorbate1;Adsorbate2] for rate rule [CO2;O-R]
Euclidian distance = 4.123105625617661
Multiplied by reaction path degeneracy 4.0
family: Surface_Dual_Adsorption_vdW
Ea raised from 0.0 to 117.7 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 13,
    label = "H2OX + CO2X <=> HX + O=C(O)O[Pt]",
    degeneracy = 4.0,
    kinetics = SurfaceArrhenius(A=(4e+13,'m^2/(mol*s)'), n=0, Ea=(90.799,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate1;Adsorbate2] for rate rule [O=C=O;Adsorbate2]
    Euclidian distance = 3.0
    Multiplied by reaction path degeneracy 4.0
    family: Surface_Dual_Adsorption_vdW
    Ea raised from 0.0 to 90.8 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [Adsorbate1;Adsorbate2] for rate rule [O=C=O;Adsorbate2]
Euclidian distance = 3.0
Multiplied by reaction path degeneracy 4.0
family: Surface_Dual_Adsorption_vdW
Ea raised from 0.0 to 90.8 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 14,
    label = "H2OX + CO2X <=> HX + O=C([Pt])OO",
    degeneracy = 4.0,
    kinetics = SurfaceArrhenius(A=(4e+13,'m^2/(mol*s)'), n=0, Ea=(337.253,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate1;Adsorbate2] for rate rule [CO2;Adsorbate2]
    Euclidian distance = 4.0
    Multiplied by reaction path degeneracy 4.0
    family: Surface_Dual_Adsorption_vdW
    Ea raised from 0.0 to 337.3 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [Adsorbate1;Adsorbate2] for rate rule [CO2;Adsorbate2]
Euclidian distance = 4.0
Multiplied by reaction path degeneracy 4.0
family: Surface_Dual_Adsorption_vdW
Ea raised from 0.0 to 337.3 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 15,
    label = "H2_ads + CO2X <=> HX + formyloxyX",
    degeneracy = 4.0,
    kinetics = SurfaceArrhenius(A=(4e+13,'m^2/(mol*s)'), n=0, Ea=(75.9397,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate1;Adsorbate2] for rate rule [O=C=O;H-H]
    Euclidian distance = 3.1622776601683795
    Multiplied by reaction path degeneracy 4.0
    family: Surface_Dual_Adsorption_vdW
    Ea raised from 0.0 to 75.9 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [Adsorbate1;Adsorbate2] for rate rule [O=C=O;H-H]
Euclidian distance = 3.1622776601683795
Multiplied by reaction path degeneracy 4.0
family: Surface_Dual_Adsorption_vdW
Ea raised from 0.0 to 75.9 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 16,
    label = "H2_ads + CO2X <=> HX + HOCOX",
    degeneracy = 4.0,
    kinetics = SurfaceArrhenius(A=(4e+13,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate1;Adsorbate2] for rate rule [CO2;H-H]
    Euclidian distance = 4.123105625617661
    Multiplied by reaction path degeneracy 4.0
    family: Surface_Dual_Adsorption_vdW"""),
    longDesc = 
"""
Estimated using template [Adsorbate1;Adsorbate2] for rate rule [CO2;H-H]
Euclidian distance = 4.123105625617661
Multiplied by reaction path degeneracy 4.0
family: Surface_Dual_Adsorption_vdW
""",
)

entry(
    index = 17,
    label = "HX + CO2X <=> Pt + formyloxyX",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2e+13,'m^2/(mol*s)'), n=0, Ea=(121.455,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O=C=O;H*]
    Euclidian distance = 3.1622776601683795
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Addition_Single_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O=C=O;H*]
Euclidian distance = 3.1622776601683795
Multiplied by reaction path degeneracy 2.0
family: Surface_Addition_Single_vdW
""",
)

entry(
    index = 18,
    label = "HX + CO2X <=> Pt + HOCOX",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2e+13,'m^2/(mol*s)'), n=0, Ea=(39.2762,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [CO2;H*]
    Euclidian distance = 4.123105625617661
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Addition_Single_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [CO2;H*]
Euclidian distance = 4.123105625617661
Multiplied by reaction path degeneracy 2.0
family: Surface_Addition_Single_vdW
""",
)

entry(
    index = 19,
    label = "OCX + CH4_ads <=> HCO_ads + CH3X",
    degeneracy = 4.0,
    kinetics = SurfaceArrhenius(A=(4e+13,'m^2/(mol*s)'), n=0, Ea=(97.9184,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [C-R;*=C=R]
    Euclidian distance = 3.1622776601683795
    Multiplied by reaction path degeneracy 4.0
    family: Surface_Abstraction_vdW
    Ea raised from 47.7 to 97.9 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [C-R;*=C=R]
Euclidian distance = 3.1622776601683795
Multiplied by reaction path degeneracy 4.0
family: Surface_Abstraction_vdW
Ea raised from 47.7 to 97.9 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 20,
    label = "OCX + CH4_ads <=> HX + acetylX",
    degeneracy = 4.0,
    kinetics = SurfaceArrhenius(A=(4e+13,'m^2/(mol*s)'), n=0, Ea=(162.9,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [AdsorbateVdW;*=C=R]
    Euclidian distance = 3.0
    Multiplied by reaction path degeneracy 4.0
    family: Surface_Abstraction_vdW
    Ea raised from 80.9 to 162.9 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [AdsorbateVdW;*=C=R]
Euclidian distance = 3.0
Multiplied by reaction path degeneracy 4.0
family: Surface_Abstraction_vdW
Ea raised from 80.9 to 162.9 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 21,
    label = "OX + CH4_ads <=> HX + O-CH3_ads",
    degeneracy = 4.0,
    kinetics = SurfaceArrhenius(A=(4e+13,'m^2/(mol*s)'), n=0, Ea=(39.8315,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [AdsorbateVdW;*=O]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 4.0
    family: Surface_Abstraction_vdW
    Ea raised from 19.3 to 39.8 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [AdsorbateVdW;*=O]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 4.0
family: Surface_Abstraction_vdW
Ea raised from 19.3 to 39.8 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 22,
    label = "CO2X + CH4_ads <=> formyloxyX + CH3X",
    degeneracy = 8.0,
    kinetics = SurfaceArrhenius(A=(8e+13,'m^2/(mol*s)'), n=0, Ea=(132.814,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate1;Adsorbate2] for rate rule [O=C=O;C-R]
    Euclidian distance = 3.1622776601683795
    Multiplied by reaction path degeneracy 8.0
    family: Surface_Dual_Adsorption_vdW
    Ea raised from 0.0 to 132.8 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [Adsorbate1;Adsorbate2] for rate rule [O=C=O;C-R]
Euclidian distance = 3.1622776601683795
Multiplied by reaction path degeneracy 8.0
family: Surface_Dual_Adsorption_vdW
Ea raised from 0.0 to 132.8 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 23,
    label = "CO2X + CH4_ads <=> HX + acetyloxyX",
    degeneracy = 8.0,
    kinetics = SurfaceArrhenius(A=(8e+13,'m^2/(mol*s)'), n=0, Ea=(93.7956,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate1;Adsorbate2] for rate rule [O=C=O;Adsorbate2]
    Euclidian distance = 3.0
    Multiplied by reaction path degeneracy 8.0
    family: Surface_Dual_Adsorption_vdW
    Ea raised from 0.0 to 93.8 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [Adsorbate1;Adsorbate2] for rate rule [O=C=O;Adsorbate2]
Euclidian distance = 3.0
Multiplied by reaction path degeneracy 8.0
family: Surface_Dual_Adsorption_vdW
Ea raised from 0.0 to 93.8 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 24,
    label = "CO2X + CH4_ads <=> HOCOX + CH3X",
    degeneracy = 8.0,
    kinetics = SurfaceArrhenius(A=(8e+13,'m^2/(mol*s)'), n=0, Ea=(50.2571,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate1;Adsorbate2] for rate rule [CO2;C-R]
    Euclidian distance = 4.123105625617661
    Multiplied by reaction path degeneracy 8.0
    family: Surface_Dual_Adsorption_vdW
    Ea raised from 0.0 to 50.3 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [Adsorbate1;Adsorbate2] for rate rule [CO2;C-R]
Euclidian distance = 4.123105625617661
Multiplied by reaction path degeneracy 8.0
family: Surface_Dual_Adsorption_vdW
Ea raised from 0.0 to 50.3 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 25,
    label = "CO2X + CH4_ads <=> HX + CH3OCOX",
    degeneracy = 8.0,
    kinetics = SurfaceArrhenius(A=(8e+13,'m^2/(mol*s)'), n=0, Ea=(96.3921,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate1;Adsorbate2] for rate rule [CO2;Adsorbate2]
    Euclidian distance = 4.0
    Multiplied by reaction path degeneracy 8.0
    family: Surface_Dual_Adsorption_vdW
    Ea raised from 0.0 to 96.4 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [Adsorbate1;Adsorbate2] for rate rule [CO2;Adsorbate2]
Euclidian distance = 4.0
Multiplied by reaction path degeneracy 8.0
family: Surface_Dual_Adsorption_vdW
Ea raised from 0.0 to 96.4 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 26,
    label = "Pt + OH(D) <=> HOX",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Adsorbate;VacantSite]
    Euclidian distance = 0
    family: Surface_Adsorption_Single"""),
    longDesc = 
"""
Exact match found for rate rule [Adsorbate;VacantSite]
Euclidian distance = 0
family: Surface_Adsorption_Single
""",
)

entry(
    index = 27,
    label = "HOX + CO2 <=> O=C(O)O[Pt]",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(A=1e-05, n=0, Ea=(68.66,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate1;Gas] for rate rule [Adsorbate1;R=R]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_EleyRideal_Addition_Multiple_Bond"""),
    longDesc = 
"""
Estimated using template [Adsorbate1;Gas] for rate rule [Adsorbate1;R=R]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Surface_EleyRideal_Addition_Multiple_Bond
""",
)

entry(
    index = 28,
    label = "HOX + CO2 <=> O=C([Pt])OO",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(A=1e-05, n=0, Ea=(283.683,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate1;Gas] for rate rule [Adsorbate1;R=R]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_EleyRideal_Addition_Multiple_Bond
    Ea raised from 283.7 to 283.7 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [Adsorbate1;Gas] for rate rule [Adsorbate1;R=R]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Surface_EleyRideal_Addition_Multiple_Bond
Ea raised from 283.7 to 283.7 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 29,
    label = "HX + HO-OH_ads <=> HOX + H2OX",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2e+13,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Donating;Abstracting] for rate rule [HO-OH;Abstracting]
    Euclidian distance = 3.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_Single_vdW
    Kinetics were estimated in this direction instead of the reverse because:
    Both directions are estimates, but this direction is exergonic.
    dGrxn(298 K) = -196.25 kJ/mol
    Ea raised from -96.8 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [Donating;Abstracting] for rate rule [HO-OH;Abstracting]
Euclidian distance = 3.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_Single_vdW
Kinetics were estimated in this direction instead of the reverse because:
Both directions are estimates, but this direction is exergonic.
dGrxn(298 K) = -196.25 kJ/mol
Ea raised from -96.8 to 0.0 kJ/mol.
""",
)

entry(
    index = 30,
    label = "OX + HCO_ads <=> HOX + OCX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(5e+17,'m^2/(mol*s)'), n=0, Ea=(40,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Abstracting;*R-H] for rate rule [O;*-C-H]
    Euclidian distance = 2.23606797749979
    family: Surface_Abstraction
    Kinetics were estimated in this direction instead of the reverse because:
    Both directions are estimates, but this direction is exergonic.
    dGrxn(298 K) = -69.76 kJ/mol"""),
    longDesc = 
"""
Estimated using template [Abstracting;*R-H] for rate rule [O;*-C-H]
Euclidian distance = 2.23606797749979
family: Surface_Abstraction
Kinetics were estimated in this direction instead of the reverse because:
Both directions are estimates, but this direction is exergonic.
dGrxn(298 K) = -69.76 kJ/mol
""",
)

entry(
    index = 31,
    label = "Pt + HOCOX <=> HOX + OCX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1e+17,'m^2/(mol*s)'), n=0, Ea=(117.687,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Combined;VacantSite] for rate rule [C-O;VacantSite]
    Euclidian distance = 2.0
    family: Surface_Dissociation"""),
    longDesc = 
"""
Estimated using template [Combined;VacantSite] for rate rule [C-O;VacantSite]
Euclidian distance = 2.0
family: Surface_Dissociation
""",
)

entry(
    index = 32,
    label = "HOX + OCX <=> Pt + OOC#[Pt]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.048e+17,'m^2/(mol*s)'), n=0, Ea=(263.201,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate1;Adsorbate2] for rate rule [*=C=O;O-*]
    Euclidian distance = 3.1622776601683795
    family: Surface_Dissociation_Beta
    Ea raised from 261.5 to 263.2 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [Adsorbate1;Adsorbate2] for rate rule [*=C=O;O-*]
Euclidian distance = 3.1622776601683795
family: Surface_Dissociation_Beta
Ea raised from 261.5 to 263.2 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 33,
    label = "Pt + OOH_ads <=> OX + HOX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1e+17,'m^2/(mol*s)'), n=0, Ea=(41.1856,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Combined;VacantSite] for rate rule [O;VacantSite]
    Euclidian distance = 1.0
    family: Surface_Dissociation"""),
    longDesc = 
"""
Estimated using template [Combined;VacantSite] for rate rule [O;VacantSite]
Euclidian distance = 1.0
family: Surface_Dissociation
""",
)

entry(
    index = 34,
    label = "HOX + CO2X <=> Pt + O=C(O)O[Pt]",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2e+13,'m^2/(mol*s)'), n=0, Ea=(24.8434,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O=C=O;HO*]
    Euclidian distance = 3.605551275463989
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Addition_Single_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O=C=O;HO*]
Euclidian distance = 3.605551275463989
Multiplied by reaction path degeneracy 2.0
family: Surface_Addition_Single_vdW
""",
)

entry(
    index = 35,
    label = "HOX + CO2X <=> Pt + O=C([Pt])OO",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2e+13,'m^2/(mol*s)'), n=0, Ea=(257.24,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [CO2;HO*]
    Euclidian distance = 4.47213595499958
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Addition_Single_vdW
    Ea raised from 256.6 to 257.2 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [CO2;HO*]
Euclidian distance = 4.47213595499958
Multiplied by reaction path degeneracy 2.0
family: Surface_Addition_Single_vdW
Ea raised from 256.6 to 257.2 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 36,
    label = "HOX + CO2X <=> OX + formyloxyX",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(3.69e+16,'m^2/(mol*s)'), n=0, Ea=(109.869,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O=C=O;*O-R]
    Euclidian distance = 3.1622776601683795
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Adsorption_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O=C=O;*O-R]
Euclidian distance = 3.1622776601683795
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Abstraction_vdW
""",
)

entry(
    index = 37,
    label = "HOX + CO2X <=> OX + HOCOX",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(3.69e+16,'m^2/(mol*s)'), n=0, Ea=(51.077,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [CO2;*O-R]
    Euclidian distance = 4.123105625617661
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Adsorption_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [CO2;*O-R]
Euclidian distance = 4.123105625617661
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Abstraction_vdW
""",
)

entry(
    index = 38,
    label = "HOX + CH4_ads <=> HX + H3C-OH_ads",
    degeneracy = 4.0,
    kinetics = SurfaceArrhenius(A=(4e+13,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Donating;Abstracting] for rate rule [Donating;*O-H]
    Euclidian distance = 2.0
    Multiplied by reaction path degeneracy 4.0
    family: Surface_Abstraction_Single_vdW
    Kinetics were estimated in this direction instead of the reverse because:
    Both directions are estimates, but this direction is exergonic.
    dGrxn(298 K) = -12.23 kJ/mol
    Ea raised from -16.7 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [Donating;Abstracting] for rate rule [Donating;*O-H]
Euclidian distance = 2.0
Multiplied by reaction path degeneracy 4.0
family: Surface_Abstraction_Single_vdW
Kinetics were estimated in this direction instead of the reverse because:
Both directions are estimates, but this direction is exergonic.
dGrxn(298 K) = -12.23 kJ/mol
Ea raised from -16.7 to 0.0 kJ/mol.
""",
)

entry(
    index = 39,
    label = "Pt + Pt + HOOH <=> HOX + HOX",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.01, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Average of [H2;VacantSite1;VacantSite2]
    Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [O;VacantSite1;VacantSite2]
    Euclidian distance = 1.0
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Average of [H2;VacantSite1;VacantSite2]
Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [O;VacantSite1;VacantSite2]
Euclidian distance = 1.0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 40,
    label = "Pt + HO-OH_ads <=> HOX + HOX",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(9.758e+15,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Combined;VacantSite]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Dissociation_vdW"""),
    longDesc = 
"""
Exact match found for rate rule [Combined;VacantSite]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Dissociation_vdW
""",
)

entry(
    index = 41,
    label = "Pt + CH3 <=> CH3X",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Adsorbate;VacantSite]
    Euclidian distance = 0
    family: Surface_Adsorption_Single"""),
    longDesc = 
"""
Exact match found for rate rule [Adsorbate;VacantSite]
Euclidian distance = 0
family: Surface_Adsorption_Single
""",
)

entry(
    index = 42,
    label = "CO2 + CH3X <=> acetyloxyX",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(A=1e-05, n=0, Ea=(107.631,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate1;Gas] for rate rule [*C;R=R]
    Euclidian distance = 1.4142135623730951
    Multiplied by reaction path degeneracy 2.0
    family: Surface_EleyRideal_Addition_Multiple_Bond
    Ea raised from 106.0 to 107.6 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [Adsorbate1;Gas] for rate rule [*C;R=R]
Euclidian distance = 1.4142135623730951
Multiplied by reaction path degeneracy 2.0
family: Surface_EleyRideal_Addition_Multiple_Bond
Ea raised from 106.0 to 107.6 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 43,
    label = "CO2 + CH3X <=> CH3OCOX",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(A=1e-05, n=0, Ea=(110.227,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate1;Gas] for rate rule [*C;R=R]
    Euclidian distance = 1.4142135623730951
    Multiplied by reaction path degeneracy 2.0
    family: Surface_EleyRideal_Addition_Multiple_Bond
    Ea raised from 108.0 to 110.2 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [Adsorbate1;Gas] for rate rule [*C;R=R]
Euclidian distance = 1.4142135623730951
Multiplied by reaction path degeneracy 2.0
family: Surface_EleyRideal_Addition_Multiple_Bond
Ea raised from 108.0 to 110.2 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 44,
    label = "HX + H3C-OH_ads <=> H2OX + CH3X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1e+13,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Donating;Abstracting] for rate rule [C-OH;Abstracting]
    Euclidian distance = 3.0
    family: Surface_Abstraction_Single_vdW
    Kinetics were estimated in this direction instead of the reverse because:
    Both directions are estimates, but this direction is exergonic.
    dGrxn(298 K) = -44.59 kJ/mol
    Ea raised from -17.9 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [Donating;Abstracting] for rate rule [C-OH;Abstracting]
Euclidian distance = 3.0
family: Surface_Abstraction_Single_vdW
Kinetics were estimated in this direction instead of the reverse because:
Both directions are estimates, but this direction is exergonic.
dGrxn(298 K) = -44.59 kJ/mol
Ea raised from -17.9 to 0.0 kJ/mol.
""",
)

entry(
    index = 45,
    label = "HCO_ads + CH2X <=> OCX + CH3X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(5e+17,'m^2/(mol*s)'), n=0, Ea=(40,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Abstracting;*R-H] for rate rule [C=*;*-C-H]
    Euclidian distance = 2.8284271247461903
    family: Surface_Abstraction
    Kinetics were estimated in this direction instead of the reverse because:
    Both directions are estimates, but this direction is exergonic.
    dGrxn(298 K) = -105.37 kJ/mol"""),
    longDesc = 
"""
Estimated using template [Abstracting;*R-H] for rate rule [C=*;*-C-H]
Euclidian distance = 2.8284271247461903
family: Surface_Abstraction
Kinetics were estimated in this direction instead of the reverse because:
Both directions are estimates, but this direction is exergonic.
dGrxn(298 K) = -105.37 kJ/mol
""",
)

entry(
    index = 46,
    label = "Pt + acetylX <=> OCX + CH3X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1e+17,'m^2/(mol*s)'), n=0, Ea=(58.9312,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Combined;VacantSite] for rate rule [C;VacantSite]
    Euclidian distance = 1.0
    family: Surface_Dissociation"""),
    longDesc = 
"""
Estimated using template [Combined;VacantSite] for rate rule [C;VacantSite]
Euclidian distance = 1.0
family: Surface_Dissociation
""",
)

entry(
    index = 47,
    label = "OCX + CH3X <=> Pt + COC#[Pt]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.048e+17,'m^2/(mol*s)'), n=0, Ea=(477.528,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate1;Adsorbate2] for rate rule [*=C=O;C-*]
    Euclidian distance = 3.1622776601683795
    family: Surface_Dissociation_Beta"""),
    longDesc = 
"""
Estimated using template [Adsorbate1;Adsorbate2] for rate rule [*=C=O;C-*]
Euclidian distance = 3.1622776601683795
family: Surface_Dissociation_Beta
""",
)

entry(
    index = 48,
    label = "Pt + O-CH3_ads <=> OX + CH3X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1e+17,'m^2/(mol*s)'), n=0, Ea=(162.416,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Combined;VacantSite] for rate rule [O-C;VacantSite]
    Euclidian distance = 2.0
    family: Surface_Dissociation"""),
    longDesc = 
"""
Estimated using template [Combined;VacantSite] for rate rule [O-C;VacantSite]
Euclidian distance = 2.0
family: Surface_Dissociation
""",
)

entry(
    index = 49,
    label = "CO2X + CH3X <=> Pt + acetyloxyX",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2e+13,'m^2/(mol*s)'), n=0, Ea=(81.1884,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O=C=O;C*]
    Euclidian distance = 3.1622776601683795
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Addition_Single_vdW
    Ea raised from 78.9 to 81.2 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O=C=O;C*]
Euclidian distance = 3.1622776601683795
Multiplied by reaction path degeneracy 2.0
family: Surface_Addition_Single_vdW
Ea raised from 78.9 to 81.2 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 50,
    label = "CO2X + CH3X <=> Pt + CH3OCOX",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2e+13,'m^2/(mol*s)'), n=0, Ea=(83.7849,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [CO2;C*]
    Euclidian distance = 4.123105625617661
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Addition_Single_vdW
    Ea raised from 80.9 to 83.8 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [CO2;C*]
Euclidian distance = 4.123105625617661
Multiplied by reaction path degeneracy 2.0
family: Surface_Addition_Single_vdW
Ea raised from 80.9 to 83.8 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 51,
    label = "CO2X + CH3X <=> formyloxyX + CH2X",
    degeneracy = 6.0,
    kinetics = SurfaceArrhenius(A=(1.107e+17,'m^2/(mol*s)'), n=0, Ea=(140.967,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O=C=O;*C-H]
    Euclidian distance = 3.605551275463989
    Multiplied by reaction path degeneracy 6.0
    family: Surface_Adsorption_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O=C=O;*C-H]
Euclidian distance = 3.605551275463989
Multiplied by reaction path degeneracy 6.0
family: Surface_Adsorption_Abstraction_vdW
""",
)

entry(
    index = 52,
    label = "CO2X + CH3X <=> HOCOX + CH2X",
    degeneracy = 6.0,
    kinetics = SurfaceArrhenius(A=(1.107e+17,'m^2/(mol*s)'), n=0, Ea=(64.1378,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [CO2;*C-H]
    Euclidian distance = 4.47213595499958
    Multiplied by reaction path degeneracy 6.0
    family: Surface_Adsorption_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [CO2;*C-H]
Euclidian distance = 4.47213595499958
Multiplied by reaction path degeneracy 6.0
family: Surface_Adsorption_Abstraction_vdW
""",
)

entry(
    index = 53,
    label = "HX + CH3-CH3_ads <=> CH3X + CH4_ads",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2e+13,'m^2/(mol*s)'), n=0, Ea=(2.9279,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Donating;Abstracting] for rate rule [C-C;Abstracting]
    Euclidian distance = 2.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_Single_vdW
    Kinetics were estimated in this direction instead of the reverse because:
    Both directions are estimates, but this direction is exergonic.
    dGrxn(298 K) = -7.78 kJ/mol"""),
    longDesc = 
"""
Estimated using template [Donating;Abstracting] for rate rule [C-C;Abstracting]
Euclidian distance = 2.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_Single_vdW
Kinetics were estimated in this direction instead of the reverse because:
Both directions are estimates, but this direction is exergonic.
dGrxn(298 K) = -7.78 kJ/mol
""",
)

entry(
    index = 54,
    label = "Pt + Pt + CH3OH <=> HOX + CH3X",
    degeneracy = 0.5,
    kinetics = StickingCoefficient(A=0.005, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Average of [H2;VacantSite1;VacantSite2]
    Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [O-C;VacantSite1;VacantSite2]
    Euclidian distance = 2.0
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Average of [H2;VacantSite1;VacantSite2]
Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [O-C;VacantSite1;VacantSite2]
Euclidian distance = 2.0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 55,
    label = "Pt + H3C-OH_ads <=> HOX + CH3X",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(9.758e+15,'m^2/(mol*s)'), n=0, Ea=(72.291,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Combined;VacantSite]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Dissociation_vdW"""),
    longDesc = 
"""
Exact match found for rate rule [Combined;VacantSite]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Dissociation_vdW
""",
)

entry(
    index = 56,
    label = "Pt + Pt + C2H6 <=> CH3X + CH3X",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.01, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Average of [H2;VacantSite1;VacantSite2]
    Estimated using an average for rate rule [Adsorbate;VacantSite1;VacantSite2]
    Euclidian distance = 0
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Average of [H2;VacantSite1;VacantSite2]
Estimated using an average for rate rule [Adsorbate;VacantSite1;VacantSite2]
Euclidian distance = 0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 57,
    label = "Pt + CH3-CH3_ads <=> CH3X + CH3X",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(9.758e+15,'m^2/(mol*s)'), n=0, Ea=(55.7383,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Combined;VacantSite]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Dissociation_vdW"""),
    longDesc = 
"""
Exact match found for rate rule [Combined;VacantSite]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Dissociation_vdW
""",
)

entry(
    index = 58,
    label = "H2OX + CH2X <=> HX + H2C-OH_ads",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2e+13,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [AdsorbateVdW;*=C-2R]
    Euclidian distance = 3.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_vdW
    Ea raised from -24.8 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [AdsorbateVdW;*=C-2R]
Euclidian distance = 3.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_vdW
Ea raised from -24.8 to 0.0 kJ/mol.
""",
)

entry(
    index = 59,
    label = "CHX + HCO_ads <=> OCX + CH2X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(5e+17,'m^2/(mol*s)'), n=0, Ea=(40,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Abstracting;*R-H] for rate rule [C#*;*-C-H]
    Euclidian distance = 2.8284271247461903
    family: Surface_Abstraction
    Kinetics were estimated in this direction instead of the reverse because:
    Both directions are estimates, but this direction is exergonic.
    dGrxn(298 K) = -24.48 kJ/mol"""),
    longDesc = 
"""
Estimated using template [Abstracting;*R-H] for rate rule [C#*;*-C-H]
Euclidian distance = 2.8284271247461903
family: Surface_Abstraction
Kinetics were estimated in this direction instead of the reverse because:
Both directions are estimates, but this direction is exergonic.
dGrxn(298 K) = -24.48 kJ/mol
""",
)

entry(
    index = 60,
    label = "Pt + Pt + ketene <=> OCX + CH2X",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.01, n=0, Ea=(41.84,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [CC;VacantSite1;VacantSite2]
    Euclidian distance = 1.0
    family: Surface_Adsorption_Dissociative_Double"""),
    longDesc = 
"""
Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [CC;VacantSite1;VacantSite2]
Euclidian distance = 1.0
family: Surface_Adsorption_Dissociative_Double
""",
)

entry(
    index = 61,
    label = "Pt + ketene-2 <=> OCX + CH2X",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2e+13,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [AdsorbateVdW;VacantSite]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Dissociation_Double_vdW
    Ea raised from -91.0 to 0.0 kJ/mol."""),
    longDesc = 
"""
Exact match found for rate rule [AdsorbateVdW;VacantSite]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Dissociation_Double_vdW
Ea raised from -91.0 to 0.0 kJ/mol.
""",
)

entry(
    index = 62,
    label = "Pt + Pt + CH2O <=> OX + CH2X",
    degeneracy = 0.5,
    kinetics = StickingCoefficient(A=0.005, n=0, Ea=(41.84,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [OC;VacantSite1;VacantSite2]
    Euclidian distance = 1.0
    family: Surface_Adsorption_Dissociative_Double"""),
    longDesc = 
"""
Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [OC;VacantSite1;VacantSite2]
Euclidian distance = 1.0
family: Surface_Adsorption_Dissociative_Double
""",
)

entry(
    index = 63,
    label = "Pt + H2C-O_ads <=> OX + CH2X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1e+13,'m^2/(mol*s)'), n=0, Ea=(23.6596,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;VacantSite] for rate rule [OC;VacantSite]
    Euclidian distance = 1.0
    family: Surface_Dissociation_Double_vdW
    Ea raised from 9.9 to 23.7 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;VacantSite] for rate rule [OC;VacantSite]
Euclidian distance = 1.0
family: Surface_Dissociation_Double_vdW
Ea raised from 9.9 to 23.7 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 64,
    label = "CO2X + CH2X <=> CHX + formyloxyX",
    degeneracy = 4.0,
    kinetics = SurfaceArrhenius(A=(7.38e+16,'m^2/(mol*s)'), n=0, Ea=(69.2696,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O=C=O;*C-R]
    Euclidian distance = 3.1622776601683795
    Multiplied by reaction path degeneracy 4.0
    family: Surface_Adsorption_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O=C=O;*C-R]
Euclidian distance = 3.1622776601683795
Multiplied by reaction path degeneracy 4.0
family: Surface_Adsorption_Abstraction_vdW
""",
)

entry(
    index = 65,
    label = "CO2X + CH2X <=> CHX + HOCOX",
    degeneracy = 4.0,
    kinetics = SurfaceArrhenius(A=(7.38e+16,'m^2/(mol*s)'), n=0, Ea=(33.6777,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [CO2;*C-R]
    Euclidian distance = 4.123105625617661
    Multiplied by reaction path degeneracy 4.0
    family: Surface_Adsorption_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [CO2;*C-R]
Euclidian distance = 4.123105625617661
Multiplied by reaction path degeneracy 4.0
family: Surface_Adsorption_Abstraction_vdW
""",
)

entry(
    index = 66,
    label = "CH2X + CH4_ads <=> HX + H2C-CH3_ads",
    degeneracy = 4.0,
    kinetics = SurfaceArrhenius(A=(4e+13,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [AdsorbateVdW;*=C-2R]
    Euclidian distance = 3.0
    Multiplied by reaction path degeneracy 4.0
    family: Surface_Abstraction_vdW
    Ea raised from -9.9 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [AdsorbateVdW;*=C-2R]
Euclidian distance = 3.0
Multiplied by reaction path degeneracy 4.0
family: Surface_Abstraction_vdW
Ea raised from -9.9 to 0.0 kJ/mol.
""",
)

entry(
    index = 67,
    label = "Pt + H2C-OH_ads <=> HOX + CH2X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1e+17,'m^2/(mol*s)'), n=0, Ea=(294.514,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Combined;VacantSite] for rate rule [C-O;VacantSite]
    Euclidian distance = 2.0
    family: Surface_Dissociation"""),
    longDesc = 
"""
Estimated using template [Combined;VacantSite] for rate rule [C-O;VacantSite]
Euclidian distance = 2.0
family: Surface_Dissociation
""",
)

entry(
    index = 68,
    label = "Pt + H2C-CH3_ads <=> CH2X + CH3X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1e+17,'m^2/(mol*s)'), n=0, Ea=(211.404,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Combined;VacantSite] for rate rule [C;VacantSite]
    Euclidian distance = 1.0
    family: Surface_Dissociation"""),
    longDesc = 
"""
Estimated using template [Combined;VacantSite] for rate rule [C;VacantSite]
Euclidian distance = 1.0
family: Surface_Dissociation
""",
)

entry(
    index = 69,
    label = "Pt + Pt + C2H4 <=> CH2X + CH2X",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.01, n=0, Ea=(41.84,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [CC;VacantSite1;VacantSite2]
    Euclidian distance = 1.0
    family: Surface_Adsorption_Dissociative_Double"""),
    longDesc = 
"""
Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [CC;VacantSite1;VacantSite2]
Euclidian distance = 1.0
family: Surface_Adsorption_Dissociative_Double
""",
)

entry(
    index = 70,
    label = "Pt + C2H4-2 <=> CH2X + CH2X",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2e+13,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [AdsorbateVdW;VacantSite]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Dissociation_Double_vdW
    Ea raised from -11.4 to 0.0 kJ/mol."""),
    longDesc = 
"""
Exact match found for rate rule [AdsorbateVdW;VacantSite]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Dissociation_Double_vdW
Ea raised from -11.4 to 0.0 kJ/mol.
""",
)

entry(
    index = 71,
    label = "H2OX + CHX <=> HX + HCOH_ads",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2e+13,'m^2/(mol*s)'), n=0, Ea=(52.1322,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [AdsorbateVdW;*#CH]
    Euclidian distance = 3.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_vdW
    Ea raised from 25.4 to 52.1 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [AdsorbateVdW;*#CH]
Euclidian distance = 3.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_vdW
Ea raised from 25.4 to 52.1 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 72,
    label = "CX + HCO_ads <=> OCX + CHX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(5e+17,'m^2/(mol*s)'), n=0, Ea=(40,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Abstracting;*R-H] for rate rule [C$*;*-C-H]
    Euclidian distance = 2.8284271247461903
    family: Surface_Abstraction
    Kinetics were estimated in this direction instead of the reverse because:
    Both directions are estimates, but this direction is exergonic.
    dGrxn(298 K) = -127.64 kJ/mol"""),
    longDesc = 
"""
Estimated using template [Abstracting;*R-H] for rate rule [C$*;*-C-H]
Euclidian distance = 2.8284271247461903
family: Surface_Abstraction
Kinetics were estimated in this direction instead of the reverse because:
Both directions are estimates, but this direction is exergonic.
dGrxn(298 K) = -127.64 kJ/mol
""",
)

entry(
    index = 73,
    label = "CO2X + CHX <=> CX + formyloxyX",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(3.69e+16,'m^2/(mol*s)'), n=0, Ea=(173.564,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O=C=O;*C-R]
    Euclidian distance = 3.1622776601683795
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Adsorption_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O=C=O;*C-R]
Euclidian distance = 3.1622776601683795
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Abstraction_vdW
""",
)

entry(
    index = 74,
    label = "CO2X + CHX <=> CX + HOCOX",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(3.69e+16,'m^2/(mol*s)'), n=0, Ea=(89.3131,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [CO2;*C-R]
    Euclidian distance = 4.123105625617661
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Adsorption_Abstraction_vdW
    Ea raised from 88.8 to 89.3 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [CO2;*C-R]
Euclidian distance = 4.123105625617661
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Abstraction_vdW
Ea raised from 88.8 to 89.3 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 75,
    label = "CHX + CH4_ads <=> HX + HC-CH3_ads",
    degeneracy = 4.0,
    kinetics = SurfaceArrhenius(A=(4e+13,'m^2/(mol*s)'), n=0, Ea=(46.3078,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [AdsorbateVdW;*#CH]
    Euclidian distance = 3.0
    Multiplied by reaction path degeneracy 4.0
    family: Surface_Abstraction_vdW
    Ea raised from 22.1 to 46.3 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [AdsorbateVdW;*#CH]
Euclidian distance = 3.0
Multiplied by reaction path degeneracy 4.0
family: Surface_Abstraction_vdW
Ea raised from 22.1 to 46.3 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 76,
    label = "Pt + HCOH_ads <=> HOX + CHX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1e+17,'m^2/(mol*s)'), n=0, Ea=(210.284,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Combined;VacantSite] for rate rule [C-O;VacantSite]
    Euclidian distance = 2.0
    family: Surface_Dissociation"""),
    longDesc = 
"""
Estimated using template [Combined;VacantSite] for rate rule [C-O;VacantSite]
Euclidian distance = 2.0
family: Surface_Dissociation
""",
)

entry(
    index = 77,
    label = "Pt + HC-CH3_ads <=> CHX + CH3X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1e+17,'m^2/(mol*s)'), n=0, Ea=(157.671,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Combined;VacantSite] for rate rule [C;VacantSite]
    Euclidian distance = 1.0
    family: Surface_Dissociation"""),
    longDesc = 
"""
Estimated using template [Combined;VacantSite] for rate rule [C;VacantSite]
Euclidian distance = 1.0
family: Surface_Dissociation
""",
)

entry(
    index = 78,
    label = "CX + CH4_ads <=> HX + C-CH3_ads",
    degeneracy = 4.0,
    kinetics = SurfaceArrhenius(A=(4e+13,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [AdsorbateVdW;*$C]
    Euclidian distance = 2.0
    Multiplied by reaction path degeneracy 4.0
    family: Surface_Abstraction_vdW
    Ea raised from -41.1 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [AdsorbateVdW;*$C]
Euclidian distance = 2.0
Multiplied by reaction path degeneracy 4.0
family: Surface_Abstraction_vdW
Ea raised from -41.1 to 0.0 kJ/mol.
""",
)

entry(
    index = 79,
    label = "Pt + C-CH3_ads <=> CX + CH3X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1e+17,'m^2/(mol*s)'), n=0, Ea=(263.776,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Combined;VacantSite] for rate rule [C;VacantSite]
    Euclidian distance = 1.0
    family: Surface_Dissociation"""),
    longDesc = 
"""
Estimated using template [Combined;VacantSite] for rate rule [C;VacantSite]
Euclidian distance = 1.0
family: Surface_Dissociation
""",
)

entry(
    index = 80,
    label = "H2OX + COH_ads <=> HOX + HCOH_ads",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2e+13,'m^2/(mol*s)'), n=0, Ea=(147.06,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O-R;*#C]
    Euclidian distance = 2.23606797749979
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_vdW
    Ea raised from 73.0 to 147.1 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O-R;*#C]
Euclidian distance = 2.23606797749979
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_vdW
Ea raised from 73.0 to 147.1 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 81,
    label = "H2OX + COH_ads <=> HX + OC(O)=[Pt]",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2e+13,'m^2/(mol*s)'), n=0, Ea=(201.479,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [AdsorbateVdW;*#C]
    Euclidian distance = 2.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_vdW
    Ea raised from 101.2 to 201.5 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [AdsorbateVdW;*#C]
Euclidian distance = 2.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_vdW
Ea raised from 101.2 to 201.5 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 82,
    label = "CX + HOCOX <=> OCX + COH_ads",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1e+15,'m^2/(mol*s)'), n=0, Ea=(80,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Abstracting;Donating] for rate rule [C$*;*C-OH]
    Euclidian distance = 3.605551275463989
    family: Surface_Abstraction
    Kinetics were estimated in this direction instead of the reverse because:
    Both directions are estimates, but this direction is exergonic.
    dGrxn(298 K) = -215.42 kJ/mol"""),
    longDesc = 
"""
Estimated using template [Abstracting;Donating] for rate rule [C$*;*C-OH]
Euclidian distance = 3.605551275463989
family: Surface_Abstraction
Kinetics were estimated in this direction instead of the reverse because:
Both directions are estimates, but this direction is exergonic.
dGrxn(298 K) = -215.42 kJ/mol
""",
)

entry(
    index = 83,
    label = "H2_ads + COH_ads <=> HX + HCOH_ads",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2e+13,'m^2/(mol*s)'), n=0, Ea=(22.7802,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [H-H;*#C]
    Euclidian distance = 2.23606797749979
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_vdW
    Ea raised from 8.6 to 22.8 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [H-H;*#C]
Euclidian distance = 2.23606797749979
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_vdW
Ea raised from 8.6 to 22.8 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 84,
    label = "Pt + HCOH_ads <=> HX + COH_ads",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1e+17,'m^2/(mol*s)'), n=0, Ea=(130.288,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Combined;VacantSite] for rate rule [C-H;VacantSite]
    Euclidian distance = 2.0
    family: Surface_Dissociation"""),
    longDesc = 
"""
Estimated using template [Combined;VacantSite] for rate rule [C-H;VacantSite]
Euclidian distance = 2.0
family: Surface_Dissociation
""",
)

entry(
    index = 85,
    label = "OOH_ads + CX <=> OX + COH_ads",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1e+15,'m^2/(mol*s)'), n=0, Ea=(80,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Abstracting;Donating] for rate rule [C$*;*O-OH]
    Euclidian distance = 3.605551275463989
    family: Surface_Abstraction
    Kinetics were estimated in this direction instead of the reverse because:
    Both directions are estimates, but this direction is exergonic.
    dGrxn(298 K) = -310.41 kJ/mol"""),
    longDesc = 
"""
Estimated using template [Abstracting;Donating] for rate rule [C$*;*O-OH]
Euclidian distance = 3.605551275463989
family: Surface_Abstraction
Kinetics were estimated in this direction instead of the reverse because:
Both directions are estimates, but this direction is exergonic.
dGrxn(298 K) = -310.41 kJ/mol
""",
)

entry(
    index = 86,
    label = "CO2X + COH_ads <=> CX + O=C(O)O[Pt]",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(3.69e+16,'m^2/(mol*s)'), n=0, Ea=(157.378,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O=C=O;*C-R]
    Euclidian distance = 3.1622776601683795
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Adsorption_Abstraction_vdW
    Ea raised from 155.2 to 157.4 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [O=C=O;*C-R]
Euclidian distance = 3.1622776601683795
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Abstraction_vdW
Ea raised from 155.2 to 157.4 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 87,
    label = "CO2X + COH_ads <=> CX + O=C([Pt])OO",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(3.69e+16,'m^2/(mol*s)'), n=0, Ea=(403.936,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [CO2;*C-R]
    Euclidian distance = 4.123105625617661
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Adsorption_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [CO2;*C-R]
Euclidian distance = 4.123105625617661
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Abstraction_vdW
""",
)

entry(
    index = 88,
    label = "COH_ads + CH4_ads <=> HCOH_ads + CH3X",
    degeneracy = 4.0,
    kinetics = SurfaceArrhenius(A=(4e+13,'m^2/(mol*s)'), n=0, Ea=(79.6546,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [C-R;*#C]
    Euclidian distance = 2.23606797749979
    Multiplied by reaction path degeneracy 4.0
    family: Surface_Abstraction_vdW
    Ea raised from 38.4 to 79.7 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [C-R;*#C]
Euclidian distance = 2.23606797749979
Multiplied by reaction path degeneracy 4.0
family: Surface_Abstraction_vdW
Ea raised from 38.4 to 79.7 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 89,
    label = "COH_ads + CH4_ads <=> HX + CC(O)=[Pt]",
    degeneracy = 4.0,
    kinetics = SurfaceArrhenius(A=(4e+13,'m^2/(mol*s)'), n=0, Ea=(291.191,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [AdsorbateVdW;*#C]
    Euclidian distance = 2.0
    Multiplied by reaction path degeneracy 4.0
    family: Surface_Abstraction_vdW
    Ea raised from 146.0 to 291.2 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [AdsorbateVdW;*#C]
Euclidian distance = 2.0
Multiplied by reaction path degeneracy 4.0
family: Surface_Abstraction_vdW
Ea raised from 146.0 to 291.2 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 90,
    label = "OX + HCOH_ads <=> HOX + COH_ads",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(5e+17,'m^2/(mol*s)'), n=0, Ea=(40,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Abstracting;*R-H] for rate rule [O;*=C-H]
    Euclidian distance = 2.23606797749979
    family: Surface_Abstraction
    Kinetics were estimated in this direction instead of the reverse because:
    Both directions are estimates, but this direction is exergonic.
    dGrxn(298 K) = -55.43 kJ/mol"""),
    longDesc = 
"""
Estimated using template [Abstracting;*R-H] for rate rule [O;*=C-H]
Euclidian distance = 2.23606797749979
family: Surface_Abstraction
Kinetics were estimated in this direction instead of the reverse because:
Both directions are estimates, but this direction is exergonic.
dGrxn(298 K) = -55.43 kJ/mol
""",
)

entry(
    index = 91,
    label = "HO-OH_ads + CX <=> HOX + COH_ads",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2e+13,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [HO-OH;*$C]
    Euclidian distance = 3.605551275463989
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_vdW
    Ea raised from -130.1 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [HO-OH;*$C]
Euclidian distance = 3.605551275463989
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_vdW
Ea raised from -130.1 to 0.0 kJ/mol.
""",
)

entry(
    index = 92,
    label = "Pt + OC(O)=[Pt] <=> HOX + COH_ads",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2e+17,'m^2/(mol*s)'), n=0, Ea=(82.9096,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Combined;VacantSite] for rate rule [C-O;VacantSite]
    Euclidian distance = 2.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Dissociation"""),
    longDesc = 
"""
Estimated using template [Combined;VacantSite] for rate rule [C-O;VacantSite]
Euclidian distance = 2.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Dissociation
""",
)

entry(
    index = 93,
    label = "CH2X + HCOH_ads <=> COH_ads + CH3X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(5e+17,'m^2/(mol*s)'), n=0, Ea=(40,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Abstracting;*R-H] for rate rule [C=*;*=C-H]
    Euclidian distance = 2.8284271247461903
    family: Surface_Abstraction
    Kinetics were estimated in this direction instead of the reverse because:
    Both directions are estimates, but this direction is exergonic.
    dGrxn(298 K) = -91.04 kJ/mol"""),
    longDesc = 
"""
Estimated using template [Abstracting;*R-H] for rate rule [C=*;*=C-H]
Euclidian distance = 2.8284271247461903
family: Surface_Abstraction
Kinetics were estimated in this direction instead of the reverse because:
Both directions are estimates, but this direction is exergonic.
dGrxn(298 K) = -91.04 kJ/mol
""",
)

entry(
    index = 94,
    label = "CX + H3C-OH_ads <=> COH_ads + CH3X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1e+13,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [C-OH;*$C]
    Euclidian distance = 3.605551275463989
    family: Surface_Abstraction_vdW
    Ea raised from -51.2 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [C-OH;*$C]
Euclidian distance = 3.605551275463989
family: Surface_Abstraction_vdW
Ea raised from -51.2 to 0.0 kJ/mol.
""",
)

entry(
    index = 95,
    label = "Pt + CC(O)=[Pt] <=> COH_ads + CH3X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1e+17,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Combined;VacantSite] for rate rule [C;VacantSite]
    Euclidian distance = 1.0
    family: Surface_Dissociation"""),
    longDesc = 
"""
Estimated using template [Combined;VacantSite] for rate rule [C;VacantSite]
Euclidian distance = 1.0
family: Surface_Dissociation
""",
)

entry(
    index = 96,
    label = "CX + H2C-OH_ads <=> COH_ads + CH2X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1e+15,'m^2/(mol*s)'), n=0, Ea=(80,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Abstracting;Donating] for rate rule [C$*;*-C-OH]
    Euclidian distance = 4.47213595499958
    family: Surface_Abstraction
    Kinetics were estimated in this direction instead of the reverse because:
    Both directions are estimates, but this direction is exergonic.
    dGrxn(298 K) = -13.08 kJ/mol"""),
    longDesc = 
"""
Estimated using template [Abstracting;Donating] for rate rule [C$*;*-C-OH]
Euclidian distance = 4.47213595499958
family: Surface_Abstraction
Kinetics were estimated in this direction instead of the reverse because:
Both directions are estimates, but this direction is exergonic.
dGrxn(298 K) = -13.08 kJ/mol
""",
)

entry(
    index = 97,
    label = "CHX + HCOH_ads <=> COH_ads + CH2X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(5e+17,'m^2/(mol*s)'), n=0, Ea=(40,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Abstracting;*R-H] for rate rule [C#*;*=C-H]
    Euclidian distance = 2.8284271247461903
    family: Surface_Abstraction
    Kinetics were estimated in this direction instead of the reverse because:
    Both directions are estimates, but this direction is exergonic.
    dGrxn(298 K) = -10.15 kJ/mol"""),
    longDesc = 
"""
Estimated using template [Abstracting;*R-H] for rate rule [C#*;*=C-H]
Euclidian distance = 2.8284271247461903
family: Surface_Abstraction
Kinetics were estimated in this direction instead of the reverse because:
Both directions are estimates, but this direction is exergonic.
dGrxn(298 K) = -10.15 kJ/mol
""",
)

entry(
    index = 98,
    label = "CX + HCOH_ads <=> CHX + COH_ads",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(1e+15,'m^2/(mol*s)'), n=0, Ea=(80,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Abstracting;Donating] for rate rule [C$*;*=C-OH]
    Euclidian distance = 4.47213595499958
    family: Surface_Abstraction
    Kinetics were estimated in this direction instead of the reverse because:
    Both directions are estimates, but this direction is exergonic.
    dGrxn(298 K) = -113.31 kJ/mol"""),
    longDesc = 
"""
Estimated using template [Abstracting;Donating] for rate rule [C$*;*=C-OH]
Euclidian distance = 4.47213595499958
family: Surface_Abstraction
Kinetics were estimated in this direction instead of the reverse because:
Both directions are estimates, but this direction is exergonic.
dGrxn(298 K) = -113.31 kJ/mol
""",
)

entry(
    index = 99,
    label = "CX + HCOH_ads <=> CHX + COH_ads",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(1e+15,'m^2/(mol*s)'), n=0, Ea=(80,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Abstracting;Donating] for rate rule [C$*;*=C-OH]
    Euclidian distance = 4.47213595499958
    family: Surface_Abstraction
    Kinetics were estimated in this direction instead of the reverse because:
    Both directions are estimates, but this direction is exergonic.
    dGrxn(298 K) = -113.31 kJ/mol"""),
    longDesc = 
"""
Estimated using template [Abstracting;Donating] for rate rule [C$*;*=C-OH]
Euclidian distance = 4.47213595499958
family: Surface_Abstraction
Kinetics were estimated in this direction instead of the reverse because:
Both directions are estimates, but this direction is exergonic.
dGrxn(298 K) = -113.31 kJ/mol
""",
)

entry(
    index = 100,
    label = "CX + OC(O)=[Pt] <=> COH_ads + COH_ads",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2e+15,'m^2/(mol*s)'), n=0, Ea=(80,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Abstracting;Donating] for rate rule [C$*;*=C-OH]
    Euclidian distance = 4.47213595499958
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction
    Kinetics were estimated in this direction instead of the reverse because:
    Both directions are estimates, but this direction is exergonic.
    dGrxn(298 K) = -268.53 kJ/mol"""),
    longDesc = 
"""
Estimated using template [Abstracting;Donating] for rate rule [C$*;*=C-OH]
Euclidian distance = 4.47213595499958
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction
Kinetics were estimated in this direction instead of the reverse because:
Both directions are estimates, but this direction is exergonic.
dGrxn(298 K) = -268.53 kJ/mol
""",
)

