#!/usr/bin/env python
# encoding: utf-8

name = "seed_edge"
shortDesc = ""
longDesc = """

"""
autoGenerated=True
entry(
    index = 0,
    label = "site + site + O2 <=> OX + OX",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.0436, n=-0.206, Ea=(1500,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/Deutschmann_Ni
""",
)

entry(
    index = 1,
    label = "site + OCX <=> OX + CX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.75e+09,'m^2/(mol*s)'), n=0, Ea=(116200,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/Deutschmann_Ni
""",
)

entry(
    index = 2,
    label = "HOX + CX <=> HX + OCX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.88e+21,'m^2/(mol*s)'), n=0.188, Ea=(62500,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/Deutschmann_Ni
""",
)

entry(
    index = 3,
    label = "OCX + OCX <=> CX + CO2X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.62e+10,'m^2/(mol*s)'), n=0.5, Ea=(241700,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/Deutschmann_Ni
""",
)

entry(
    index = 4,
    label = "OX + CHX <=> site + CXHO",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(4.59e+16,'m^2/(mol*s)'), n=0, Ea=(109900,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/Deutschmann_Ni
""",
)

entry(
    index = 5,
    label = "HOX + CXHO <=> HX + HOCXO",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(2.28e+16,'m^2/(mol*s)'), n=0.263, Ea=(15900,'J/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K')),
    longDesc = 
"""
Originally from reaction library: Surface/Deutschmann_Ni
""",
)

entry(
    index = 6,
    label = "site + H <=> HX",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.85, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using an average for rate rule [Adsorbate;VacantSite]
    Euclidian distance = 0
    family: Surface_Adsorption_Single"""),
    longDesc = 
"""
Estimated using an average for rate rule [Adsorbate;VacantSite]
Euclidian distance = 0
family: Surface_Adsorption_Single
""",
)

entry(
    index = 7,
    label = "HX + CO2 <=> formyloxyX",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(106.273,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Adsorbate1;R=R] for rate rule [*H;R=R]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_EleyRideal_Addition_Multiple_Bond"""),
    longDesc = 
"""
Estimated using template [Adsorbate1;R=R] for rate rule [*H;R=R]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Surface_EleyRideal_Addition_Multiple_Bond
""",
)

entry(
    index = 8,
    label = "HX + CO2 <=> HOCXO",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(78.4626,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Adsorbate1;R=R] for rate rule [*H;R=R]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_EleyRideal_Addition_Multiple_Bond
    Ea raised from 78.3 to 78.5 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [Adsorbate1;R=R] for rate rule [*H;R=R]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Surface_EleyRideal_Addition_Multiple_Bond
Ea raised from 78.3 to 78.5 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 9,
    label = "HX + OCX <=> site + OC#[Pt]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.799e+17,'m^2/(mol*s)'), n=0, Ea=(52.1168,'kcal/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Matched reaction 27 CO* + H* <=> COH* + Cu in Surface_Dissociation_Beta/training
    This reaction matched rate rule [*=C=O;H-*]
    family: Surface_Dissociation_Beta
    metal: None"""),
    longDesc = 
"""
Matched reaction 27 CO* + H* <=> COH* + Cu in Surface_Dissociation_Beta/training
This reaction matched rate rule [*=C=O;H-*]
family: Surface_Dissociation_Beta
metal: None
""",
)

entry(
    index = 10,
    label = "site + site + OCCO(S) <=> OCX + OCX",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.01, n=0, Ea=(41.84,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [CC;VacantSite1;VacantSite2]
    Euclidian distance = 1.0
    family: Surface_Adsorption_Dissociative_Double"""),
    longDesc = 
"""
Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [CC;VacantSite1;VacantSite2]
Euclidian distance = 1.0
family: Surface_Adsorption_Dissociative_Double
""",
)

entry(
    index = 11,
    label = "site + OCCO(S)-2 <=> OCX + OCX",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(3.282e+16,'m^2/(mol*s)'), n=0, Ea=(241.213,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Estimated using an average for rate rule [AdsorbateVdW;VacantSite]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Dissociation_Double_vdW"""),
    longDesc = 
"""
Estimated using an average for rate rule [AdsorbateVdW;VacantSite]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Dissociation_Double_vdW
""",
)

entry(
    index = 12,
    label = "site + O2(S) <=> OX + OX",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(3.282e+16,'m^2/(mol*s)'), n=0, Ea=(241.213,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Estimated using an average for rate rule [AdsorbateVdW;VacantSite]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Dissociation_Double_vdW"""),
    longDesc = 
"""
Estimated using an average for rate rule [AdsorbateVdW;VacantSite]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Dissociation_Double_vdW
""",
)

entry(
    index = 13,
    label = "site + HCO <=> CXHO",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.85, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using an average for rate rule [Adsorbate;VacantSite]
    Euclidian distance = 0
    family: Surface_Adsorption_Single"""),
    longDesc = 
"""
Estimated using an average for rate rule [Adsorbate;VacantSite]
Euclidian distance = 0
family: Surface_Adsorption_Single
""",
)

entry(
    index = 14,
    label = "CO2 + CXHO <=> O=CC(=O)O[Pt]",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(210.899,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [*C;R=R]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_EleyRideal_Addition_Multiple_Bond"""),
    longDesc = 
"""
Estimated using an average for rate rule [*C;R=R]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_EleyRideal_Addition_Multiple_Bond
""",
)

entry(
    index = 15,
    label = "CO2 + CXHO <=> O=COC(=O)[Pt]",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(172.347,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [*C;R=R]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_EleyRideal_Addition_Multiple_Bond
    Ea raised from 171.2 to 172.3 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using an average for rate rule [*C;R=R]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_EleyRideal_Addition_Multiple_Bond
Ea raised from 171.2 to 172.3 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 16,
    label = "site + site + CH2O <=> HX + CXHO",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.016, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [C-H;VacantSite1;VacantSite2]
    Euclidian distance = 1.0
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [C-H;VacantSite1;VacantSite2]
Euclidian distance = 1.0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 17,
    label = "HX + CXHO <=> site + OC=[Pt]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.048e+17,'m^2/(mol*s)'), n=0, Ea=(20.9851,'kcal/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Matched reaction 29 HCO* + H* <=> HCOH* + Cu in Surface_Dissociation_Beta/training
    This reaction matched rate rule [*-C=O;H-*]
    family: Surface_Dissociation_Beta
    metal: None"""),
    longDesc = 
"""
Matched reaction 29 HCO* + H* <=> HCOH* + Cu in Surface_Dissociation_Beta/training
This reaction matched rate rule [*-C=O;H-*]
family: Surface_Dissociation_Beta
metal: None
""",
)

entry(
    index = 18,
    label = "site + OCHCOX <=> OCX + CXHO",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(7.35976e+18,'m^2/(mol*s)'), n=-0.1065, Ea=(27.15,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [C;VacantSite]
    Euclidian distance = 0
    family: Surface_Dissociation"""),
    longDesc = 
"""
Estimated using an average for rate rule [C;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation
""",
)

entry(
    index = 19,
    label = "OCX + CXHO <=> site + O=COC#[Pt]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.799e+17,'m^2/(mol*s)'), n=0, Ea=(697.263,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Estimated using template [*=C=O;Adsorbate2] for rate rule [*=C=O;C-*]
    Euclidian distance = 1.0
    family: Surface_Dissociation_Beta"""),
    longDesc = 
"""
Estimated using template [*=C=O;Adsorbate2] for rate rule [*=C=O;C-*]
Euclidian distance = 1.0
family: Surface_Dissociation_Beta
""",
)

entry(
    index = 20,
    label = "site + formyloxyX <=> OX + CXHO",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(8.733e+16,'m^2/(mol*s)'), n=0, Ea=(10.8385,'kcal/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Matched reaction 28 HCOO* + Ni_4 <=> HCO* + OX_3 in Surface_Dissociation/training
    This reaction matched rate rule [O-C;VacantSite]
    family: Surface_Dissociation
    metal: None"""),
    longDesc = 
"""
Matched reaction 28 HCOO* + Ni_4 <=> HCO* + OX_3 in Surface_Dissociation/training
This reaction matched rate rule [O-C;VacantSite]
family: Surface_Dissociation
metal: None
""",
)

entry(
    index = 21,
    label = "site + site + glyoxal <=> CXHO + CXHO",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.016, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using an average for rate rule [Adsorbate;VacantSite1;VacantSite2]
    Euclidian distance = 0
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Estimated using an average for rate rule [Adsorbate;VacantSite1;VacantSite2]
Euclidian distance = 0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 22,
    label = "CXHO + CXHO <=> site + O=COC=[Pt]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(7.62e+16,'m^2/(mol*s)'), n=0, Ea=(311.912,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Estimated using template [*-C=O;Adsorbate2] for rate rule [*-C=O;C-*]
    Euclidian distance = 1.0
    family: Surface_Dissociation_Beta"""),
    longDesc = 
"""
Estimated using template [*-C=O;Adsorbate2] for rate rule [*-C=O;C-*]
Euclidian distance = 1.0
family: Surface_Dissociation_Beta
""",
)

entry(
    index = 23,
    label = "site + glyoxal-2 <=> CXHO + CXHO",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(3.562e+17,'m^2/(mol*s)'), n=0, Ea=(157.271,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""From training reaction 34 used for Combined;VacantSite
    Exact match found for rate rule [Combined;VacantSite]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Dissociation_vdW"""),
    longDesc = 
"""
From training reaction 34 used for Combined;VacantSite
Exact match found for rate rule [Combined;VacantSite]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Dissociation_vdW
""",
)

entry(
    index = 24,
    label = "site + OH(D) <=> HOX",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.85, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using an average for rate rule [Adsorbate;VacantSite]
    Euclidian distance = 0
    family: Surface_Adsorption_Single"""),
    longDesc = 
"""
Estimated using an average for rate rule [Adsorbate;VacantSite]
Euclidian distance = 0
family: Surface_Adsorption_Single
""",
)

entry(
    index = 25,
    label = "HOX + CO2 <=> O=C(O)O[Pt]",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(73.06,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [Adsorbate1;R=R]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_EleyRideal_Addition_Multiple_Bond"""),
    longDesc = 
"""
Estimated using an average for rate rule [Adsorbate1;R=R]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_EleyRideal_Addition_Multiple_Bond
""",
)

entry(
    index = 26,
    label = "HOX + CO2 <=> O=C([Pt])OO",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(340.401,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [Adsorbate1;R=R]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_EleyRideal_Addition_Multiple_Bond"""),
    longDesc = 
"""
Estimated using an average for rate rule [Adsorbate1;R=R]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_EleyRideal_Addition_Multiple_Bond
""",
)

entry(
    index = 27,
    label = "HOX + OCX <=> site + HOCXO",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(4.02e+14,'m^2/(mol*s)'), n=0, Ea=(109.946,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Matched reaction 1 OCX_3 + HOX_5 <=> HOCXO_1 + Ni_4 in Surface_Dissociation/training
    This reaction matched rate rule [C-O;VacantSite]
    family: Surface_Dissociation
    metal: None
    Ea raised from 11.5 to 109.9 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Matched reaction 1 OCX_3 + HOX_5 <=> HOCXO_1 + Ni_4 in Surface_Dissociation/training
This reaction matched rate rule [C-O;VacantSite]
family: Surface_Dissociation
metal: None
Ea raised from 11.5 to 109.9 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 28,
    label = "HOX + OCX <=> site + OOC#[Pt]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.799e+17,'m^2/(mol*s)'), n=0, Ea=(318.763,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Estimated using template [*=C=O;Adsorbate2] for rate rule [*=C=O;O-*]
    Euclidian distance = 1.0
    family: Surface_Dissociation_Beta
    Ea raised from 318.3 to 318.8 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [*=C=O;Adsorbate2] for rate rule [*=C=O;O-*]
Euclidian distance = 1.0
family: Surface_Dissociation_Beta
Ea raised from 318.3 to 318.8 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 29,
    label = "site + OO[Pt] <=> OX + HOX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(2.55105e+17,'m^2/(mol*s)'), n=0, Ea=(103.722,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [O;VacantSite]
    Euclidian distance = 0
    family: Surface_Dissociation"""),
    longDesc = 
"""
Estimated using an average for rate rule [O;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation
""",
)

entry(
    index = 30,
    label = "site + site + formic_acid <=> HOX + CXHO",
    degeneracy = 0.5,
    kinetics = StickingCoefficient(A=0.008, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [O-C;VacantSite1;VacantSite2]
    Euclidian distance = 2.0
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [O-C;VacantSite1;VacantSite2]
Euclidian distance = 2.0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 31,
    label = "HOX + CXHO <=> site + OOC=[Pt]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(7.62e+16,'m^2/(mol*s)'), n=0, Ea=(411.885,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Estimated using template [*-C=O;Adsorbate2] for rate rule [*-C=O;O-*]
    Euclidian distance = 1.0
    family: Surface_Dissociation_Beta"""),
    longDesc = 
"""
Estimated using template [*-C=O;Adsorbate2] for rate rule [*-C=O;O-*]
Euclidian distance = 1.0
family: Surface_Dissociation_Beta
""",
)

entry(
    index = 32,
    label = "site + formic_acid-2 <=> HOX + CXHO",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(1.781e+17,'m^2/(mol*s)'), n=0, Ea=(37.5887,'kcal/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Matched reaction 34 HCOOH_2* + X_4 <=> HCO* + OH_2* in Surface_Dissociation_vdW/training
    This reaction matched rate rule [Combined;VacantSite]
    family: Surface_Dissociation_vdW
    metal: None"""),
    longDesc = 
"""
Matched reaction 34 HCOOH_2* + X_4 <=> HCO* + OH_2* in Surface_Dissociation_vdW/training
This reaction matched rate rule [Combined;VacantSite]
family: Surface_Dissociation_vdW
metal: None
""",
)

entry(
    index = 33,
    label = "site + site + HOOH <=> HOX + HOX",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.016, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [O;VacantSite1;VacantSite2]
    Euclidian distance = 1.0
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [O;VacantSite1;VacantSite2]
Euclidian distance = 1.0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 34,
    label = "site + OO.[Pt] <=> HOX + HOX",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(3.562e+17,'m^2/(mol*s)'), n=0, Ea=(157.271,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""From training reaction 34 used for Combined;VacantSite
    Exact match found for rate rule [Combined;VacantSite]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Dissociation_vdW"""),
    longDesc = 
"""
From training reaction 34 used for Combined;VacantSite
Exact match found for rate rule [Combined;VacantSite]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Dissociation_vdW
""",
)

entry(
    index = 35,
    label = "O.[Pt] + OCX <=> HX + HOCXO",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2.07394e+13,'m^2/(mol*s)'), n=0.936633, Ea=(146.477,'kJ/mol'), T0=(1,'K'), Tmin=(303.03,'K'), Tmax=(2000,'K'), comment="""Estimated using an average for rate rule [AdsorbateVdW;*=C=R]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using an average for rate rule [AdsorbateVdW;*=C=R]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 36,
    label = "OX + O.[Pt] <=> HX + OO[Pt]",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(4.87241e+15,'m^2/(mol*s)'), n=0.639876, Ea=(294.286,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [AdsorbateVdW;*=O]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using an average for rate rule [AdsorbateVdW;*=O]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 37,
    label = "HX + formic_acid-2 <=> O.[Pt] + CXHO",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1e+13,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Donating;Abstracting] for rate rule [C-OH;Abstracting]
    Euclidian distance = 3.0
    family: Surface_Abstraction_Single_vdW
    Ea raised from -21.4 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [Donating;Abstracting] for rate rule [C-OH;Abstracting]
Euclidian distance = 3.0
family: Surface_Abstraction_Single_vdW
Ea raised from -21.4 to 0.0 kJ/mol.
""",
)

entry(
    index = 38,
    label = "HX + OO.[Pt] <=> HOX + O.[Pt]",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2e+13,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Donating;Abstracting] for rate rule [HO-OH;Abstracting]
    Euclidian distance = 3.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_Single_vdW
    Ea raised from -117.9 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [Donating;Abstracting] for rate rule [HO-OH;Abstracting]
Euclidian distance = 3.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_Single_vdW
Ea raised from -117.9 to 0.0 kJ/mol.
""",
)

entry(
    index = 39,
    label = "site + CH2O <=> C=O.[Pt]",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""From training reaction 5 used for Adsorbate;VacantSite
    Exact match found for rate rule [Adsorbate;VacantSite]
    Euclidian distance = 0
    family: Surface_Adsorption_vdW"""),
    longDesc = 
"""
From training reaction 5 used for Adsorbate;VacantSite
Exact match found for rate rule [Adsorbate;VacantSite]
Euclidian distance = 0
family: Surface_Adsorption_vdW
""",
)

entry(
    index = 40,
    label = "site + C=O.[Pt] <=> OX + C=[Pt]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.641e+16,'m^2/(mol*s)'), n=0, Ea=(241.213,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""From training reaction 35 used for OC;VacantSite
    Exact match found for rate rule [OC;VacantSite]
    Euclidian distance = 0
    family: Surface_Dissociation_Double_vdW"""),
    longDesc = 
"""
From training reaction 35 used for OC;VacantSite
Exact match found for rate rule [OC;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation_Double_vdW
""",
)

entry(
    index = 41,
    label = "[H][H].[Pt] + C=O.[Pt] <=> HX + OC[Pt]",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(1.40689e+10,'m^2/(mol*s)'), n=1.27097, Ea=(144.01,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [C=O;Adsorbate2] for rate rule [2R-C=O;H-H]
    Euclidian distance = 1.4142135623730951
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Dual_Adsorption_vdW"""),
    longDesc = 
"""
Estimated using template [C=O;Adsorbate2] for rate rule [2R-C=O;H-H]
Euclidian distance = 1.4142135623730951
Multiplied by reaction path degeneracy 2.0
family: Surface_Dual_Adsorption_vdW
""",
)

entry(
    index = 42,
    label = "HX + C=O.[Pt] <=> site + OC[Pt]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.234e+19,'m^2/(mol*s)'), n=0, Ea=(18.9096,'kcal/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Matched reaction 31 CH2O_2* + H* <=> CH2OH* + X_5 in Surface_Addition_Single_vdW/training
    This reaction matched rate rule [2R-C=O;H*]
    family: Surface_Addition_Single_vdW
    metal: None"""),
    longDesc = 
"""
Matched reaction 31 CH2O_2* + H* <=> CH2OH* + X_5 in Surface_Addition_Single_vdW/training
This reaction matched rate rule [2R-C=O;H*]
family: Surface_Addition_Single_vdW
metal: None
""",
)

entry(
    index = 43,
    label = "OCX + C=O.[Pt] <=> HX + OCHCOX",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2.07394e+13,'m^2/(mol*s)'), n=0.936633, Ea=(172.472,'kJ/mol'), T0=(1,'K'), Tmin=(303.03,'K'), Tmax=(2000,'K'), comment="""Estimated using an average for rate rule [AdsorbateVdW;*=C=R]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using an average for rate rule [AdsorbateVdW;*=C=R]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 44,
    label = "OX + C=O.[Pt] <=> HX + formyloxyX",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(4.87241e+15,'m^2/(mol*s)'), n=0.639876, Ea=(120.26,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [AdsorbateVdW;*=O]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using an average for rate rule [AdsorbateVdW;*=O]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 45,
    label = "HX + glyoxal-2 <=> CXHO + C=O.[Pt]",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2e+13,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Donating;Abstracting] for rate rule [C-C;Abstracting]
    Euclidian distance = 2.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_Single_vdW
    Ea raised from -81.4 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [Donating;Abstracting] for rate rule [C-C;Abstracting]
Euclidian distance = 2.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_Single_vdW
Ea raised from -81.4 to 0.0 kJ/mol.
""",
)

entry(
    index = 46,
    label = "CXHO + C=O.[Pt] <=> site + OCH2CHOX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.0616e+18,'m^2/(mol*s)'), n=0, Ea=(167.53,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [O=C;Adsorbate1] for rate rule [O=C;C*]
    Euclidian distance = 1.0
    family: Surface_Addition_Single_vdW"""),
    longDesc = 
"""
Estimated using template [O=C;Adsorbate1] for rate rule [O=C;C*]
Euclidian distance = 1.0
family: Surface_Addition_Single_vdW
""",
)

entry(
    index = 47,
    label = "CXHO + C=O.[Pt] <=> site + CH2OCHOX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.234e+19,'m^2/(mol*s)'), n=0, Ea=(79.118,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Estimated using template [2R-C=O;Adsorbate1] for rate rule [2R-C=O;C*]
    Euclidian distance = 1.0
    family: Surface_Addition_Single_vdW"""),
    longDesc = 
"""
Estimated using template [2R-C=O;Adsorbate1] for rate rule [2R-C=O;C*]
Euclidian distance = 1.0
family: Surface_Addition_Single_vdW
""",
)

entry(
    index = 48,
    label = "CXHO + C=O.[Pt] <=> OCX + OC[Pt]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.814e+16,'m^2/(mol*s)'), n=0, Ea=(40.5238,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;*C-H] for rate rule [2R-C=O;*C-H]
    Euclidian distance = 3.0
    family: Surface_Adsorption_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;*C-H] for rate rule [2R-C=O;*C-H]
Euclidian distance = 3.0
family: Surface_Adsorption_Abstraction_vdW
""",
)

entry(
    index = 49,
    label = "HOX + C=O.[Pt] <=> HX + formic_acid-2",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2e+13,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Donating;Abstracting] for rate rule [Donating;*O-H]
    Euclidian distance = 2.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_Single_vdW
    Ea raised from -35.0 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [Donating;Abstracting] for rate rule [Donating;*O-H]
Euclidian distance = 2.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_Single_vdW
Ea raised from -35.0 to 0.0 kJ/mol.
""",
)

entry(
    index = 50,
    label = "site + HOCH2OX <=> HOX + C=O.[Pt]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.401e+17,'m^2/(mol*s)'), n=0, Ea=(17.0648,'kcal/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Matched reaction 23 CH3O2* + X_5 <=> CH2O* + OH* in Surface_Addition_Single_vdW/training
    This reaction matched rate rule [O=C;HO*]
    family: Surface_Addition_Single_vdW
    metal: None"""),
    longDesc = 
"""
Matched reaction 23 CH3O2* + X_5 <=> CH2O* + OH* in Surface_Addition_Single_vdW/training
This reaction matched rate rule [O=C;HO*]
family: Surface_Addition_Single_vdW
metal: None
""",
)

entry(
    index = 51,
    label = "HOX + C=O.[Pt] <=> site + OOC[Pt]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.234e+19,'m^2/(mol*s)'), n=0, Ea=(267.939,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Estimated using template [2R-C=O;Adsorbate1] for rate rule [2R-C=O;HO*]
    Euclidian distance = 2.0
    family: Surface_Addition_Single_vdW"""),
    longDesc = 
"""
Estimated using template [2R-C=O;Adsorbate1] for rate rule [2R-C=O;HO*]
Euclidian distance = 2.0
family: Surface_Addition_Single_vdW
""",
)

entry(
    index = 52,
    label = "HOX + C=O.[Pt] <=> OX + OC[Pt]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.814e+16,'m^2/(mol*s)'), n=0, Ea=(40.5238,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [2R-C=O;*O-R]
    Euclidian distance = 3.1622776601683795
    family: Surface_Adsorption_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [2R-C=O;*O-R]
Euclidian distance = 3.1622776601683795
family: Surface_Adsorption_Abstraction_vdW
""",
)

entry(
    index = 53,
    label = "O.[Pt] + C=O.[Pt] <=> HOX + OC[Pt]",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(1.40689e+10,'m^2/(mol*s)'), n=1.27097, Ea=(144.01,'kJ/mol'), T0=(1,'K'), Tmin=(303.03,'K'), Tmax=(2000,'K'), comment="""Estimated using template [C=O;O-R] for rate rule [2R-C=O;O-R]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Dual_Adsorption_vdW"""),
    longDesc = 
"""
Estimated using template [C=O;O-R] for rate rule [2R-C=O;O-R]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Dual_Adsorption_vdW
""",
)

entry(
    index = 54,
    label = "O.[Pt] + C=O.[Pt] <=> HX + HOCH2OX",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(1.40689e+10,'m^2/(mol*s)'), n=1.27097, Ea=(144.01,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Adsorbate1;Adsorbate2] for rate rule [O=C;Adsorbate2]
    Euclidian distance = 2.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Dual_Adsorption_vdW"""),
    longDesc = 
"""
Estimated using template [Adsorbate1;Adsorbate2] for rate rule [O=C;Adsorbate2]
Euclidian distance = 2.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Dual_Adsorption_vdW
""",
)

entry(
    index = 55,
    label = "O.[Pt] + C=O.[Pt] <=> HX + OOC[Pt]",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(1.40689e+10,'m^2/(mol*s)'), n=1.27097, Ea=(305.125,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [C=O;Adsorbate2] for rate rule [2R-C=O;Adsorbate2]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Dual_Adsorption_vdW"""),
    longDesc = 
"""
Estimated using template [C=O;Adsorbate2] for rate rule [2R-C=O;Adsorbate2]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Dual_Adsorption_vdW
""",
)

entry(
    index = 56,
    label = "C=O.[Pt] + C=O.[Pt] <=> HX + OCH2CHOX",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(1.40689e+10,'m^2/(mol*s)'), n=1.27097, Ea=(144.01,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Adsorbate1;Adsorbate2] for rate rule [O=C;Adsorbate2]
    Euclidian distance = 2.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Dual_Adsorption_vdW"""),
    longDesc = 
"""
Estimated using template [Adsorbate1;Adsorbate2] for rate rule [O=C;Adsorbate2]
Euclidian distance = 2.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Dual_Adsorption_vdW
""",
)

entry(
    index = 57,
    label = "C=O.[Pt] + C=O.[Pt] <=> CXHO + OC[Pt]",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(1.40689e+10,'m^2/(mol*s)'), n=1.27097, Ea=(144.01,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [C=O;Adsorbate2] for rate rule [2R-C=O;C-R]
    Euclidian distance = 1.4142135623730951
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Dual_Adsorption_vdW"""),
    longDesc = 
"""
Estimated using template [C=O;Adsorbate2] for rate rule [2R-C=O;C-R]
Euclidian distance = 1.4142135623730951
Multiplied by reaction path degeneracy 2.0
family: Surface_Dual_Adsorption_vdW
""",
)

entry(
    index = 58,
    label = "C=O.[Pt] + C=O.[Pt] <=> HX + CH2OCHOX",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(1.40689e+10,'m^2/(mol*s)'), n=1.27097, Ea=(144.01,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [C=O;Adsorbate2] for rate rule [2R-C=O;Adsorbate2]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Dual_Adsorption_vdW"""),
    longDesc = 
"""
Estimated using template [C=O;Adsorbate2] for rate rule [2R-C=O;Adsorbate2]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Dual_Adsorption_vdW
""",
)

entry(
    index = 59,
    label = "site + CH3O <=> CO[Pt]",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.85, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using an average for rate rule [Adsorbate;VacantSite]
    Euclidian distance = 0
    family: Surface_Adsorption_Single"""),
    longDesc = 
"""
Estimated using an average for rate rule [Adsorbate;VacantSite]
Euclidian distance = 0
family: Surface_Adsorption_Single
""",
)

entry(
    index = 60,
    label = "HX + CH2O <=> CO[Pt]",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.05, n=0, Ea=(73.06,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Adsorbate1;R=R] for rate rule [*H;R=R]
    Euclidian distance = 1.0
    family: Surface_EleyRideal_Addition_Multiple_Bond"""),
    longDesc = 
"""
Estimated using template [Adsorbate1;R=R] for rate rule [*H;R=R]
Euclidian distance = 1.0
family: Surface_EleyRideal_Addition_Multiple_Bond
""",
)

entry(
    index = 61,
    label = "CO[Pt] <=> OC[Pt]",
    degeneracy = 3.0,
    kinetics = SurfaceArrhenius(A=(3.33867e+12,'s^-1'), n=0, Ea=(60.5233,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [Adsorbate1]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 3.0
    family: Surface_Migration"""),
    longDesc = 
"""
Estimated using an average for rate rule [Adsorbate1]
Euclidian distance = 0
Multiplied by reaction path degeneracy 3.0
family: Surface_Migration
""",
)

entry(
    index = 62,
    label = "CO2 + CO[Pt] <=> COC(=O)O[Pt]",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(73.06,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [Adsorbate1;R=R]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_EleyRideal_Addition_Multiple_Bond"""),
    longDesc = 
"""
Estimated using an average for rate rule [Adsorbate1;R=R]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_EleyRideal_Addition_Multiple_Bond
""",
)

entry(
    index = 63,
    label = "CO2 + CO[Pt] <=> COOC(=O)[Pt]",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(260.111,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [Adsorbate1;R=R]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_EleyRideal_Addition_Multiple_Bond
    Ea raised from 258.3 to 260.1 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using an average for rate rule [Adsorbate1;R=R]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_EleyRideal_Addition_Multiple_Bond
Ea raised from 258.3 to 260.1 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 64,
    label = "[H][H].[Pt] + CO[Pt] <=> HX + CO.[Pt]",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2e+13,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Donating;Abstracting] for rate rule [H-H;*O]
    Euclidian distance = 1.4142135623730951
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_Single_vdW
    Ea raised from -33.1 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [Donating;Abstracting] for rate rule [H-H;*O]
Euclidian distance = 1.4142135623730951
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_Single_vdW
Ea raised from -33.1 to 0.0 kJ/mol.
""",
)

entry(
    index = 65,
    label = "site + site + CH3OH <=> HX + CO[Pt]",
    degeneracy = 0.5,
    kinetics = StickingCoefficient(A=0.008, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [O-H;VacantSite1;VacantSite2]
    Euclidian distance = 2.0
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [O-H;VacantSite1;VacantSite2]
Euclidian distance = 2.0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 66,
    label = "HX + CO[Pt] <=> site + CO.[Pt]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(4.349e+22,'m^2/(mol*s)'), n=0, Ea=(10.8385,'kcal/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Matched reaction 25 CH3O* + H* <=> CH3OH_2* + X_4 in Surface_Dissociation_vdW/training
    This reaction matched rate rule [O-H;VacantSite]
    family: Surface_Dissociation_vdW
    metal: None"""),
    longDesc = 
"""
Matched reaction 25 CH3O* + H* <=> CH3OH_2* + X_4 in Surface_Dissociation_vdW/training
This reaction matched rate rule [O-H;VacantSite]
family: Surface_Dissociation_vdW
metal: None
""",
)

entry(
    index = 67,
    label = "OX + acetylX <=> OCX + CO[Pt]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.298e+17,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Estimated using template [O;Donating] for rate rule [O;*C-C]
    Euclidian distance = 2.0
    family: Surface_Abstraction"""),
    longDesc = 
"""
Estimated using template [O;Donating] for rate rule [O;*C-C]
Euclidian distance = 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 68,
    label = "site + CH3OCOX <=> OCX + CO[Pt]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.46e+20,'m^2/(mol*s)'), n=-0.213, Ea=(54.3,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""From training reaction 4 used for C-O;VacantSite
    Exact match found for rate rule [C-O;VacantSite]
    Euclidian distance = 0
    family: Surface_Dissociation"""),
    longDesc = 
"""
From training reaction 4 used for C-O;VacantSite
Exact match found for rate rule [C-O;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation
""",
)

entry(
    index = 69,
    label = "OCX + CO[Pt] <=> site + COOC#[Pt]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.799e+17,'m^2/(mol*s)'), n=0, Ea=(278.741,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Estimated using template [*=C=O;Adsorbate2] for rate rule [*=C=O;O-*]
    Euclidian distance = 1.0
    family: Surface_Dissociation_Beta"""),
    longDesc = 
"""
Estimated using template [*=C=O;Adsorbate2] for rate rule [*=C=O;O-*]
Euclidian distance = 1.0
family: Surface_Dissociation_Beta
""",
)

entry(
    index = 70,
    label = "site + CH3OOX <=> OX + CO[Pt]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(2.55105e+17,'m^2/(mol*s)'), n=0, Ea=(103.722,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [O;VacantSite]
    Euclidian distance = 0
    family: Surface_Dissociation"""),
    longDesc = 
"""
Estimated using an average for rate rule [O;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation
""",
)

entry(
    index = 71,
    label = "OX + CH3CHO <=> CXHO + CO[Pt]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.405e+20,'m^2/(mol*s)'), n=-0.101, Ea=(92.7,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [C-R;*=O] for rate rule [C-C;*=O]
    Euclidian distance = 1.0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [C-R;*=O] for rate rule [C-C;*=O]
Euclidian distance = 1.0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 72,
    label = "CXHO + CO[Pt] <=> OCX + CO.[Pt]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(6.572e+16,'m^2/(mol*s)'), n=0, Ea=(8.76301,'kcal/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Matched reaction 45 CH3O* + HCO* <=> CH3OH* + CO* in Surface_Abstraction_vdW/training
    This reaction matched rate rule [O-R;*=C=R]
    family: Surface_Abstraction_vdW
    metal: None"""),
    longDesc = 
"""
Matched reaction 45 CH3O* + HCO* <=> CH3OH* + CO* in Surface_Abstraction_vdW/training
This reaction matched rate rule [O-R;*=C=R]
family: Surface_Abstraction_vdW
metal: None
""",
)

entry(
    index = 73,
    label = "site + site + methyl_formate <=> CXHO + CO[Pt]",
    degeneracy = 0.5,
    kinetics = StickingCoefficient(A=0.008, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [O-C;VacantSite1;VacantSite2]
    Euclidian distance = 2.0
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [O-C;VacantSite1;VacantSite2]
Euclidian distance = 2.0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 74,
    label = "CXHO + CO[Pt] <=> site + COOC=[Pt]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(7.62e+16,'m^2/(mol*s)'), n=0, Ea=(421.893,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Estimated using template [*-C=O;Adsorbate2] for rate rule [*-C=O;O-*]
    Euclidian distance = 1.0
    family: Surface_Dissociation_Beta"""),
    longDesc = 
"""
Estimated using template [*-C=O;Adsorbate2] for rate rule [*-C=O;O-*]
Euclidian distance = 1.0
family: Surface_Dissociation_Beta
""",
)

entry(
    index = 75,
    label = "site + methyl_formate-2 <=> CXHO + CO[Pt]",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(3.562e+17,'m^2/(mol*s)'), n=0, Ea=(157.271,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""From training reaction 34 used for Combined;VacantSite
    Exact match found for rate rule [Combined;VacantSite]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Dissociation_vdW"""),
    longDesc = 
"""
From training reaction 34 used for Combined;VacantSite
Exact match found for rate rule [Combined;VacantSite]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Dissociation_vdW
""",
)

entry(
    index = 76,
    label = "OX + CO.[Pt] <=> HOX + CO[Pt]",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(5.15771e+12,'m^2/(mol*s)'), n=1.24904, Ea=(168.59,'kJ/mol'), T0=(1,'K'), Tmin=(303.03,'K'), Tmax=(2000,'K'), comment="""Estimated using template [O-C;*=O] for rate rule [O-C-3R;*=O]
    Euclidian distance = 1.0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [O-C;*=O] for rate rule [O-C-3R;*=O]
Euclidian distance = 1.0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 77,
    label = "OX + CO.[Pt] <=> HOX + CO[Pt]",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(A=(4.22427e+10,'m^2/(mol*s)'), n=1.38075, Ea=(147.821,'kJ/mol'), T0=(1,'K'), Tmin=(303.03,'K'), Tmax=(2000,'K'), comment="""From training reaction 16 used for O-R;*=O
    Exact match found for rate rule [O-R;*=O]
    Euclidian distance = 0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
From training reaction 16 used for O-R;*=O
Exact match found for rate rule [O-R;*=O]
Euclidian distance = 0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 78,
    label = "site + site + CH3OOH <=> HOX + CO[Pt]",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.016, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [O;VacantSite1;VacantSite2]
    Euclidian distance = 1.0
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [O;VacantSite1;VacantSite2]
Euclidian distance = 1.0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 79,
    label = "site + CH3OOH-2 <=> HOX + CO[Pt]",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(3.562e+17,'m^2/(mol*s)'), n=0, Ea=(157.271,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""From training reaction 34 used for Combined;VacantSite
    Exact match found for rate rule [Combined;VacantSite]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Dissociation_vdW"""),
    longDesc = 
"""
From training reaction 34 used for Combined;VacantSite
Exact match found for rate rule [Combined;VacantSite]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Dissociation_vdW
""",
)

entry(
    index = 80,
    label = "HOX + CO.[Pt] <=> O.[Pt] + CO[Pt]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1e+13,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Donating;Abstracting] for rate rule [O-H;*O-H]
    Euclidian distance = 2.8284271247461903
    family: Surface_Abstraction_Single_vdW
    Ea raised from -10.1 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [Donating;Abstracting] for rate rule [O-H;*O-H]
Euclidian distance = 2.8284271247461903
family: Surface_Abstraction_Single_vdW
Ea raised from -10.1 to 0.0 kJ/mol.
""",
)

entry(
    index = 81,
    label = "HX + CH3OOH-2 <=> O.[Pt] + CO[Pt]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1e+13,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Donating;Abstracting] for rate rule [O-O;Abstracting]
    Euclidian distance = 2.0
    family: Surface_Abstraction_Single_vdW
    Ea raised from -149.7 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [Donating;Abstracting] for rate rule [O-O;Abstracting]
Euclidian distance = 2.0
family: Surface_Abstraction_Single_vdW
Ea raised from -149.7 to 0.0 kJ/mol.
""",
)

entry(
    index = 82,
    label = "C=O.[Pt] + CO[Pt] <=> CXHO + CO.[Pt]",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2e+13,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Donating;Abstracting] for rate rule [C-R;*O]
    Euclidian distance = 1.4142135623730951
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_Single_vdW
    Ea raised from -46.3 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [Donating;Abstracting] for rate rule [C-R;*O]
Euclidian distance = 1.4142135623730951
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_Single_vdW
Ea raised from -46.3 to 0.0 kJ/mol.
""",
)

entry(
    index = 83,
    label = "HX + methyl_formate-2 <=> C=O.[Pt] + CO[Pt]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1e+13,'m^2/(mol*s)'), n=0, Ea=(6.32831,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Donating;Abstracting] for rate rule [O-C=R;Abstracting]
    Euclidian distance = 3.0
    family: Surface_Abstraction_Single_vdW
    Ea raised from 2.6 to 6.3 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [Donating;Abstracting] for rate rule [O-C=R;Abstracting]
Euclidian distance = 3.0
family: Surface_Abstraction_Single_vdW
Ea raised from 2.6 to 6.3 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 84,
    label = "C=O.[Pt] + CO[Pt] <=> site + CH3OCH2OX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(2.176e+18,'m^2/(mol*s)'), n=0, Ea=(6.68395,'kcal/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Matched reaction 47 CH3O_5* + CH2O* <=> H2COOCH3* + X_5 in Surface_Addition_Single_vdW/training
    This reaction matched rate rule [O=C;O*]
    family: Surface_Addition_Single_vdW
    metal: None
    Ea raised from 12.5 to 28.0 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Matched reaction 47 CH3O_5* + CH2O* <=> H2COOCH3* + X_5 in Surface_Addition_Single_vdW/training
This reaction matched rate rule [O=C;O*]
family: Surface_Addition_Single_vdW
metal: None
Ea raised from 12.5 to 28.0 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 85,
    label = "C=O.[Pt] + CO[Pt] <=> site + COOC[Pt]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.234e+19,'m^2/(mol*s)'), n=0, Ea=(275.562,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Estimated using template [2R-C=O;Adsorbate1] for rate rule [2R-C=O;O*]
    Euclidian distance = 1.0
    family: Surface_Addition_Single_vdW"""),
    longDesc = 
"""
Estimated using template [2R-C=O;Adsorbate1] for rate rule [2R-C=O;O*]
Euclidian distance = 1.0
family: Surface_Addition_Single_vdW
""",
)

entry(
    index = 86,
    label = "C=O.[Pt] + CO[Pt] <=> OX + CH3CH2OX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.814e+16,'m^2/(mol*s)'), n=0, Ea=(40.5238,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [O=C;Adsorbate1] for rate rule [O=C;*O-R]
    Euclidian distance = 1.0
    family: Surface_Adsorption_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [O=C;Adsorbate1] for rate rule [O=C;*O-R]
Euclidian distance = 1.0
family: Surface_Adsorption_Abstraction_vdW
""",
)

entry(
    index = 87,
    label = "C=O.[Pt] + CO[Pt] <=> OX + CH3OCH2X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.814e+16,'m^2/(mol*s)'), n=0, Ea=(40.5238,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [2R-C=O;*O-R]
    Euclidian distance = 3.1622776601683795
    family: Surface_Adsorption_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [2R-C=O;*O-R]
Euclidian distance = 3.1622776601683795
family: Surface_Adsorption_Abstraction_vdW
""",
)

entry(
    index = 88,
    label = "OX + DME <=> CO[Pt] + CO[Pt]",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(1.03154e+13,'m^2/(mol*s)'), n=1.24904, Ea=(168.59,'kJ/mol'), T0=(1,'K'), Tmin=(303.03,'K'), Tmax=(2000,'K'), comment="""Estimated using template [O-C;*=O] for rate rule [O-C-3R;*=O]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [O-C;*=O] for rate rule [O-C-3R;*=O]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 89,
    label = "site + site + CH3OOCH3 <=> CO[Pt] + CO[Pt]",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.016, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [O;VacantSite1;VacantSite2]
    Euclidian distance = 1.0
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [O;VacantSite1;VacantSite2]
Euclidian distance = 1.0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 90,
    label = "site + CH3OOCH3-2 <=> CO[Pt] + CO[Pt]",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(3.562e+17,'m^2/(mol*s)'), n=0, Ea=(157.271,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""From training reaction 34 used for Combined;VacantSite
    Exact match found for rate rule [Combined;VacantSite]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Dissociation_vdW"""),
    longDesc = 
"""
From training reaction 34 used for Combined;VacantSite
Exact match found for rate rule [Combined;VacantSite]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Dissociation_vdW
""",
)

entry(
    index = 91,
    label = "C=O.[Pt] + CO.[Pt] <=> CO[Pt] + CO[Pt]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(7.03447e+09,'m^2/(mol*s)'), n=1.27097, Ea=(144.01,'kJ/mol'), T0=(1,'K'), Tmin=(303.03,'K'), Tmax=(2000,'K'), comment="""Estimated using template [Adsorbate1;O-R] for rate rule [O=C;O-R]
    Euclidian distance = 2.0
    family: Surface_Dual_Adsorption_vdW"""),
    longDesc = 
"""
Estimated using template [Adsorbate1;O-R] for rate rule [O=C;O-R]
Euclidian distance = 2.0
family: Surface_Dual_Adsorption_vdW
""",
)

entry(
    index = 92,
    label = "OCX + C.[Pt] <=> HX + acetylX",
    degeneracy = 4.0,
    kinetics = SurfaceArrhenius(A=(4.14787e+13,'m^2/(mol*s)'), n=0.936633, Ea=(147.229,'kJ/mol'), T0=(1,'K'), Tmin=(303.03,'K'), Tmax=(2000,'K'), comment="""Estimated using an average for rate rule [AdsorbateVdW;*=C=R]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 4.0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using an average for rate rule [AdsorbateVdW;*=C=R]
Euclidian distance = 0
Multiplied by reaction path degeneracy 4.0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 93,
    label = "HX + CH3CHO <=> CXHO + C.[Pt]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1e+13,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Donating;Abstracting] for rate rule [C-C;Abstracting]
    Euclidian distance = 2.0
    family: Surface_Abstraction_Single_vdW
    Ea raised from -45.7 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [Donating;Abstracting] for rate rule [C-C;Abstracting]
Euclidian distance = 2.0
family: Surface_Abstraction_Single_vdW
Ea raised from -45.7 to 0.0 kJ/mol.
""",
)

entry(
    index = 94,
    label = "HX + CO.[Pt] <=> HOX + C.[Pt]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1e+13,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Donating;Abstracting] for rate rule [O-C-3R;Abstracting]
    Euclidian distance = 3.0
    family: Surface_Abstraction_Single_vdW
    Ea raised from -4.4 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [Donating;Abstracting] for rate rule [O-C-3R;Abstracting]
Euclidian distance = 3.0
family: Surface_Abstraction_Single_vdW
Ea raised from -4.4 to 0.0 kJ/mol.
""",
)

entry(
    index = 95,
    label = "C=O.[Pt] + C.[Pt] <=> HX + CH3CH2OX",
    degeneracy = 4.0,
    kinetics = SurfaceArrhenius(A=(2.81379e+10,'m^2/(mol*s)'), n=1.27097, Ea=(144.01,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Adsorbate1;Adsorbate2] for rate rule [O=C;Adsorbate2]
    Euclidian distance = 2.0
    Multiplied by reaction path degeneracy 4.0
    family: Surface_Dual_Adsorption_vdW"""),
    longDesc = 
"""
Estimated using template [Adsorbate1;Adsorbate2] for rate rule [O=C;Adsorbate2]
Euclidian distance = 2.0
Multiplied by reaction path degeneracy 4.0
family: Surface_Dual_Adsorption_vdW
""",
)

entry(
    index = 96,
    label = "C=O.[Pt] + C.[Pt] <=> C[Pt] + OC[Pt]",
    degeneracy = 4.0,
    kinetics = SurfaceArrhenius(A=(2.81379e+10,'m^2/(mol*s)'), n=1.27097, Ea=(144.01,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [C=O;Adsorbate2] for rate rule [2R-C=O;C-R]
    Euclidian distance = 1.4142135623730951
    Multiplied by reaction path degeneracy 4.0
    family: Surface_Dual_Adsorption_vdW"""),
    longDesc = 
"""
Estimated using template [C=O;Adsorbate2] for rate rule [2R-C=O;C-R]
Euclidian distance = 1.4142135623730951
Multiplied by reaction path degeneracy 4.0
family: Surface_Dual_Adsorption_vdW
""",
)

entry(
    index = 97,
    label = "C=O.[Pt] + C.[Pt] <=> HX + CH3OCH2X",
    degeneracy = 4.0,
    kinetics = SurfaceArrhenius(A=(2.81379e+10,'m^2/(mol*s)'), n=1.27097, Ea=(144.01,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [C=O;Adsorbate2] for rate rule [2R-C=O;Adsorbate2]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 4.0
    family: Surface_Dual_Adsorption_vdW"""),
    longDesc = 
"""
Estimated using template [C=O;Adsorbate2] for rate rule [2R-C=O;Adsorbate2]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 4.0
family: Surface_Dual_Adsorption_vdW
""",
)

entry(
    index = 98,
    label = "C[Pt] + CO.[Pt] <=> CO[Pt] + C.[Pt]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1e+13,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Donating;Abstracting] for rate rule [O-H;*C-3R]
    Euclidian distance = 2.8284271247461903
    family: Surface_Abstraction_Single_vdW
    Ea raised from -3.9 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [Donating;Abstracting] for rate rule [O-H;*C-3R]
Euclidian distance = 2.8284271247461903
family: Surface_Abstraction_Single_vdW
Ea raised from -3.9 to 0.0 kJ/mol.
""",
)

entry(
    index = 99,
    label = "HX + DME <=> CO[Pt] + C.[Pt]",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2e+13,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Donating;Abstracting] for rate rule [O-C-3R;Abstracting]
    Euclidian distance = 3.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_Single_vdW
    Ea raised from -45.6 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [Donating;Abstracting] for rate rule [O-C-3R;Abstracting]
Euclidian distance = 3.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_Single_vdW
Ea raised from -45.6 to 0.0 kJ/mol.
""",
)

entry(
    index = 100,
    label = "site + CH3 <=> C[Pt]",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.85, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using an average for rate rule [Adsorbate;VacantSite]
    Euclidian distance = 0
    family: Surface_Adsorption_Single"""),
    longDesc = 
"""
Estimated using an average for rate rule [Adsorbate;VacantSite]
Euclidian distance = 0
family: Surface_Adsorption_Single
""",
)

entry(
    index = 101,
    label = "CO2 + C[Pt] <=> acetyloxyX",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(73.06,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [*C;R=R]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_EleyRideal_Addition_Multiple_Bond"""),
    longDesc = 
"""
Estimated using an average for rate rule [*C;R=R]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_EleyRideal_Addition_Multiple_Bond
""",
)

entry(
    index = 102,
    label = "CO2 + C[Pt] <=> CH3OCOX",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(110.056,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [*C;R=R]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_EleyRideal_Addition_Multiple_Bond
    Ea raised from 108.0 to 110.1 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using an average for rate rule [*C;R=R]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_EleyRideal_Addition_Multiple_Bond
Ea raised from 108.0 to 110.1 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 103,
    label = "HX + C=[Pt] <=> site + C[Pt]",
    degeneracy = 3.0,
    kinetics = SurfaceArrhenius(A=(3.09e+19,'m^2/(mol*s)'), n=-0.087, Ea=(57200,'J/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Matched reaction 16 CH2X_3 + HX_5 <=> CH3X_1 + Ni_4 in Surface_Dissociation/training
    This reaction matched rate rule [C-H;VacantSite]
    family: Surface_Dissociation
    metal: None"""),
    longDesc = 
"""
Matched reaction 16 CH2X_3 + HX_5 <=> CH3X_1 + Ni_4 in Surface_Dissociation/training
This reaction matched rate rule [C-H;VacantSite]
family: Surface_Dissociation
metal: None
""",
)

entry(
    index = 104,
    label = "[H][H].[Pt] + C=[Pt] <=> HX + C[Pt]",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2.07394e+13,'m^2/(mol*s)'), n=0.936633, Ea=(121.703,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [AdsorbateVdW;*=C] for rate rule [H-H;*=C-2R]
    Euclidian distance = 1.4142135623730951
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;*=C] for rate rule [H-H;*=C-2R]
Euclidian distance = 1.4142135623730951
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 105,
    label = "CXHO + C=[Pt] <=> OCX + C[Pt]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(2.14108e+17,'m^2/(mol*s)'), n=0.0505, Ea=(9.5,'kJ/mol'), T0=(1,'K'), comment="""Estimated using average of templates [Abstracting;*-C-H] + [C=*;*R-H] for rate rule [C=*;*-C-H]
    Euclidian distance = 2.0
    family: Surface_Abstraction"""),
    longDesc = 
"""
Estimated using average of templates [Abstracting;*-C-H] + [C=*;*R-H] for rate rule [C=*;*-C-H]
Euclidian distance = 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 106,
    label = "site + acetylX <=> OCX + C[Pt]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(7.35976e+18,'m^2/(mol*s)'), n=-0.1065, Ea=(27.15,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [C;VacantSite]
    Euclidian distance = 0
    family: Surface_Dissociation"""),
    longDesc = 
"""
Estimated using an average for rate rule [C;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation
""",
)

entry(
    index = 107,
    label = "OCX + C[Pt] <=> site + COC#[Pt]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.799e+17,'m^2/(mol*s)'), n=0, Ea=(477.528,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Estimated using template [*=C=O;Adsorbate2] for rate rule [*=C=O;C-*]
    Euclidian distance = 1.0
    family: Surface_Dissociation_Beta"""),
    longDesc = 
"""
Estimated using template [*=C=O;Adsorbate2] for rate rule [*=C=O;C-*]
Euclidian distance = 1.0
family: Surface_Dissociation_Beta
""",
)

entry(
    index = 108,
    label = "HOX + C=[Pt] <=> OX + C[Pt]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.39e+17,'m^2/(mol*s)'), n=0.101, Ea=(19000,'J/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Matched reaction 24 CH2X_1 + HOX_3 <=> CH3X_4 + OX_5 in Surface_Abstraction/training
    This reaction matched rate rule [O;*-C-H]
    family: Surface_Abstraction
    metal: None"""),
    longDesc = 
"""
Matched reaction 24 CH2X_1 + HOX_3 <=> CH3X_4 + OX_5 in Surface_Abstraction/training
This reaction matched rate rule [O;*-C-H]
family: Surface_Abstraction
metal: None
""",
)

entry(
    index = 109,
    label = "C=[Pt] + C=O.[Pt] <=> CXHO + C[Pt]",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2.07394e+13,'m^2/(mol*s)'), n=0.936633, Ea=(121.703,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [AdsorbateVdW;*=C] for rate rule [C-R;*=C-2R]
    Euclidian distance = 1.4142135623730951
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;*=C] for rate rule [C-R;*=C-2R]
Euclidian distance = 1.4142135623730951
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 110,
    label = "site + site + CH3CHO-2 <=> CXHO + C[Pt]",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.016, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using an average for rate rule [Adsorbate;VacantSite1;VacantSite2]
    Euclidian distance = 0
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Estimated using an average for rate rule [Adsorbate;VacantSite1;VacantSite2]
Euclidian distance = 0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 111,
    label = "CXHO + C[Pt] <=> site + COC=[Pt]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(7.62e+16,'m^2/(mol*s)'), n=0, Ea=(307.732,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Estimated using template [*-C=O;Adsorbate2] for rate rule [*-C=O;C-*]
    Euclidian distance = 1.0
    family: Surface_Dissociation_Beta"""),
    longDesc = 
"""
Estimated using template [*-C=O;Adsorbate2] for rate rule [*-C=O;C-*]
Euclidian distance = 1.0
family: Surface_Dissociation_Beta
""",
)

entry(
    index = 112,
    label = "site + CH3CHO <=> CXHO + C[Pt]",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(3.562e+17,'m^2/(mol*s)'), n=0, Ea=(157.271,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""From training reaction 34 used for Combined;VacantSite
    Exact match found for rate rule [Combined;VacantSite]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Dissociation_vdW"""),
    longDesc = 
"""
From training reaction 34 used for Combined;VacantSite
Exact match found for rate rule [Combined;VacantSite]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Dissociation_vdW
""",
)

entry(
    index = 113,
    label = "O.[Pt] + C=[Pt] <=> HOX + C[Pt]",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2.07394e+13,'m^2/(mol*s)'), n=0.936633, Ea=(121.703,'kJ/mol'), T0=(1,'K'), Tmin=(303.03,'K'), Tmax=(2000,'K'), comment="""Estimated using template [O-R;*=C] for rate rule [O-R;*=C-2R]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [O-R;*=C] for rate rule [O-R;*=C-2R]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 114,
    label = "site + site + CH3OH <=> HOX + C[Pt]",
    degeneracy = 0.5,
    kinetics = StickingCoefficient(A=0.008, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [O-C;VacantSite1;VacantSite2]
    Euclidian distance = 2.0
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [O-C;VacantSite1;VacantSite2]
Euclidian distance = 2.0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 115,
    label = "site + CO.[Pt] <=> HOX + C[Pt]",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(3.562e+17,'m^2/(mol*s)'), n=0, Ea=(157.271,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""From training reaction 34 used for Combined;VacantSite
    Exact match found for rate rule [Combined;VacantSite]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Dissociation_vdW"""),
    longDesc = 
"""
From training reaction 34 used for Combined;VacantSite
Exact match found for rate rule [Combined;VacantSite]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Dissociation_vdW
""",
)

entry(
    index = 116,
    label = "HX + CO.[Pt] <=> O.[Pt] + C[Pt]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1e+13,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Donating;Abstracting] for rate rule [C-OH;Abstracting]
    Euclidian distance = 3.0
    family: Surface_Abstraction_Single_vdW
    Ea raised from -10.6 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [Donating;Abstracting] for rate rule [C-OH;Abstracting]
Euclidian distance = 3.0
family: Surface_Abstraction_Single_vdW
Ea raised from -10.6 to 0.0 kJ/mol.
""",
)

entry(
    index = 117,
    label = "C=O.[Pt] + C[Pt] <=> HX + CH3CHO",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2e+13,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Donating;Abstracting] for rate rule [Donating;*C-3R]
    Euclidian distance = 2.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_Single_vdW
    Ea raised from -4.5 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [Donating;Abstracting] for rate rule [Donating;*C-3R]
Euclidian distance = 2.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_Single_vdW
Ea raised from -4.5 to 0.0 kJ/mol.
""",
)

entry(
    index = 118,
    label = "C=O.[Pt] + C[Pt] <=> site + CH3CH2OX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.0616e+18,'m^2/(mol*s)'), n=0, Ea=(65.61,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [O=C;Adsorbate1] for rate rule [O=C;C*]
    Euclidian distance = 1.0
    family: Surface_Addition_Single_vdW"""),
    longDesc = 
"""
Estimated using template [O=C;Adsorbate1] for rate rule [O=C;C*]
Euclidian distance = 1.0
family: Surface_Addition_Single_vdW
""",
)

entry(
    index = 119,
    label = "C=O.[Pt] + C[Pt] <=> site + CH3OCH2X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.234e+19,'m^2/(mol*s)'), n=0, Ea=(79.118,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Estimated using template [2R-C=O;Adsorbate1] for rate rule [2R-C=O;C*]
    Euclidian distance = 1.0
    family: Surface_Addition_Single_vdW"""),
    longDesc = 
"""
Estimated using template [2R-C=O;Adsorbate1] for rate rule [2R-C=O;C*]
Euclidian distance = 1.0
family: Surface_Addition_Single_vdW
""",
)

entry(
    index = 120,
    label = "C=O.[Pt] + C[Pt] <=> C=[Pt] + CO[Pt]",
    degeneracy = 3.0,
    kinetics = SurfaceArrhenius(A=(5.442e+16,'m^2/(mol*s)'), n=0, Ea=(40.5238,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""From training reaction 43 used for O=C;*C-H
    Exact match found for rate rule [O=C;*C-H]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 3.0
    family: Surface_Adsorption_Abstraction_vdW"""),
    longDesc = 
"""
From training reaction 43 used for O=C;*C-H
Exact match found for rate rule [O=C;*C-H]
Euclidian distance = 0
Multiplied by reaction path degeneracy 3.0
family: Surface_Adsorption_Abstraction_vdW
""",
)

entry(
    index = 121,
    label = "C=O.[Pt] + C[Pt] <=> C=[Pt] + OC[Pt]",
    degeneracy = 3.0,
    kinetics = SurfaceArrhenius(A=(5.442e+16,'m^2/(mol*s)'), n=0, Ea=(40.5238,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;*C-H] for rate rule [2R-C=O;*C-H]
    Euclidian distance = 3.0
    Multiplied by reaction path degeneracy 3.0
    family: Surface_Adsorption_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;*C-H] for rate rule [2R-C=O;*C-H]
Euclidian distance = 3.0
Multiplied by reaction path degeneracy 3.0
family: Surface_Adsorption_Abstraction_vdW
""",
)

entry(
    index = 122,
    label = "C=[Pt] + CO.[Pt] <=> C[Pt] + CO[Pt]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(1.03697e+13,'m^2/(mol*s)'), n=0.936633, Ea=(121.703,'kJ/mol'), T0=(1,'K'), Tmin=(303.03,'K'), Tmax=(2000,'K'), comment="""Estimated using template [O-R;*=C] for rate rule [O-R;*=C-2R]
    Euclidian distance = 1.0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [O-R;*=C] for rate rule [O-R;*=C-2R]
Euclidian distance = 1.0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 123,
    label = "OX + CC.[Pt] <=> C[Pt] + CO[Pt]",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2.81e+20,'m^2/(mol*s)'), n=-0.101, Ea=(101.107,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [C-R;*=O] for rate rule [C-C;*=O]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [C-R;*=O] for rate rule [C-C;*=O]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 124,
    label = "site + site + DME-2 <=> C[Pt] + CO[Pt]",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.016, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [O-C;VacantSite1;VacantSite2]
    Euclidian distance = 2.0
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Estimated using template [Adsorbate;VacantSite1;VacantSite2] for rate rule [O-C;VacantSite1;VacantSite2]
Euclidian distance = 2.0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 125,
    label = "site + DME <=> C[Pt] + CO[Pt]",
    degeneracy = 4.0,
    kinetics = SurfaceArrhenius(A=(7.124e+17,'m^2/(mol*s)'), n=0, Ea=(157.271,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""From training reaction 34 used for Combined;VacantSite
    Exact match found for rate rule [Combined;VacantSite]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 4.0
    family: Surface_Dissociation_vdW"""),
    longDesc = 
"""
From training reaction 34 used for Combined;VacantSite
Exact match found for rate rule [Combined;VacantSite]
Euclidian distance = 0
Multiplied by reaction path degeneracy 4.0
family: Surface_Dissociation_vdW
""",
)

entry(
    index = 126,
    label = "C[Pt] + C.[Pt] <=> HX + CC.[Pt]",
    degeneracy = 4.0,
    kinetics = SurfaceArrhenius(A=(4e+13,'m^2/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [Donating;Abstracting] for rate rule [Donating;*C-3R]
    Euclidian distance = 2.0
    Multiplied by reaction path degeneracy 4.0
    family: Surface_Abstraction_Single_vdW
    Ea raised from -10.2 to 0.0 kJ/mol."""),
    longDesc = 
"""
Estimated using template [Donating;Abstracting] for rate rule [Donating;*C-3R]
Euclidian distance = 2.0
Multiplied by reaction path degeneracy 4.0
family: Surface_Abstraction_Single_vdW
Ea raised from -10.2 to 0.0 kJ/mol.
""",
)

entry(
    index = 127,
    label = "C=[Pt] + C.[Pt] <=> C[Pt] + C[Pt]",
    degeneracy = 4.0,
    kinetics = SurfaceArrhenius(A=(4.14787e+13,'m^2/(mol*s)'), n=0.936633, Ea=(121.703,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [AdsorbateVdW;*=C] for rate rule [C-R;*=C-2R]
    Euclidian distance = 1.4142135623730951
    Multiplied by reaction path degeneracy 4.0
    family: Surface_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;*=C] for rate rule [C-R;*=C-2R]
Euclidian distance = 1.4142135623730951
Multiplied by reaction path degeneracy 4.0
family: Surface_Abstraction_vdW
""",
)

entry(
    index = 128,
    label = "site + site + C2H6 <=> C[Pt] + C[Pt]",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.016, n=0, Ea=(20.8169,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using an average for rate rule [Adsorbate;VacantSite1;VacantSite2]
    Euclidian distance = 0
    family: Surface_Adsorption_Dissociative
    Ea raised from 0.0 to 20.8 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using an average for rate rule [Adsorbate;VacantSite1;VacantSite2]
Euclidian distance = 0
family: Surface_Adsorption_Dissociative
Ea raised from 0.0 to 20.8 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 129,
    label = "site + CC.[Pt] <=> C[Pt] + C[Pt]",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(3.562e+17,'m^2/(mol*s)'), n=0, Ea=(157.271,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""From training reaction 34 used for Combined;VacantSite
    Exact match found for rate rule [Combined;VacantSite]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Dissociation_vdW"""),
    longDesc = 
"""
From training reaction 34 used for Combined;VacantSite
Exact match found for rate rule [Combined;VacantSite]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Dissociation_vdW
""",
)

entry(
    index = 130,
    label = "[H][H].[Pt] + CO2X <=> HX + formyloxyX",
    degeneracy = 4.0,
    kinetics = SurfaceArrhenius(A=(2.81379e+10,'m^2/(mol*s)'), n=1.27097, Ea=(144.01,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Adsorbate1;Adsorbate2] for rate rule [O=C=O;H-H]
    Euclidian distance = 3.1622776601683795
    Multiplied by reaction path degeneracy 4.0
    family: Surface_Dual_Adsorption_vdW"""),
    longDesc = 
"""
Estimated using template [Adsorbate1;Adsorbate2] for rate rule [O=C=O;H-H]
Euclidian distance = 3.1622776601683795
Multiplied by reaction path degeneracy 4.0
family: Surface_Dual_Adsorption_vdW
""",
)

entry(
    index = 131,
    label = "[H][H].[Pt] + CO2X <=> HX + HOCXO",
    degeneracy = 4.0,
    kinetics = SurfaceArrhenius(A=(2.81379e+10,'m^2/(mol*s)'), n=1.27097, Ea=(144.01,'kJ/mol'), T0=(1,'K'), Tmin=(303.03,'K'), Tmax=(2000,'K'), comment="""Estimated using template [CO2;Adsorbate2] for rate rule [CO2;H-H]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 4.0
    family: Surface_Dual_Adsorption_vdW"""),
    longDesc = 
"""
Estimated using template [CO2;Adsorbate2] for rate rule [CO2;H-H]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 4.0
family: Surface_Dual_Adsorption_vdW
""",
)

entry(
    index = 132,
    label = "HX + CO2X <=> site + formyloxyX",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(1.243e+18,'m^2/(mol*s)'), n=0, Ea=(20.0627,'kcal/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Matched reaction 17 CO2* + H* <=> HCOO* + X_5 in Surface_Addition_Single_vdW/training
    This reaction matched rate rule [O=C=O;H*]
    family: Surface_Addition_Single_vdW
    metal: None"""),
    longDesc = 
"""
Matched reaction 17 CO2* + H* <=> HCOO* + X_5 in Surface_Addition_Single_vdW/training
This reaction matched rate rule [O=C=O;H*]
family: Surface_Addition_Single_vdW
metal: None
""",
)

entry(
    index = 133,
    label = "site + HOCXO <=> HX + CO2X",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(8.028e+17,'m^2/(mol*s)'), n=0, Ea=(28.3645,'kcal/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Matched reaction 11 COOH* + X_5 <=> CO2_2* + H* in Surface_Addition_Single_vdW/training
    This reaction matched rate rule [CO2;H*]
    family: Surface_Addition_Single_vdW
    metal: None"""),
    longDesc = 
"""
Matched reaction 11 COOH* + X_5 <=> CO2_2* + H* in Surface_Addition_Single_vdW/training
This reaction matched rate rule [CO2;H*]
family: Surface_Addition_Single_vdW
metal: None
""",
)

entry(
    index = 134,
    label = "CO2X + CXHO <=> site + O=CC(=O)O[Pt]",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(1.243e+18,'m^2/(mol*s)'), n=0, Ea=(184.262,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Estimated using template [O=C=O;Adsorbate1] for rate rule [O=C=O;C*]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Addition_Single_vdW
    Ea raised from 183.8 to 184.3 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [O=C=O;Adsorbate1] for rate rule [O=C=O;C*]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Addition_Single_vdW
Ea raised from 183.8 to 184.3 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 135,
    label = "CO2X + CXHO <=> site + O=COC(=O)[Pt]",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(9.69133e+18,'m^2/(mol*s)'), n=-0.544242, Ea=(189.782,'kJ/mol'), T0=(1,'K'), Tmin=(303.03,'K'), Tmax=(2000,'K'), comment="""Estimated using template [CO2;Adsorbate1] for rate rule [CO2;C*]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Addition_Single_vdW"""),
    longDesc = 
"""
Estimated using template [CO2;Adsorbate1] for rate rule [CO2;C*]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Addition_Single_vdW
""",
)

entry(
    index = 136,
    label = "CO2X + CXHO <=> OCX + formyloxyX",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(3.628e+16,'m^2/(mol*s)'), n=0, Ea=(40.5238,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [O=C;*C-H] for rate rule [O=C=O;*C-H]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Adsorption_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [O=C;*C-H] for rate rule [O=C=O;*C-H]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Abstraction_vdW
""",
)

entry(
    index = 137,
    label = "CO2X + CXHO <=> OCX + HOCXO",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(3.628e+16,'m^2/(mol*s)'), n=0, Ea=(40.5238,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;*C-H] for rate rule [CO2;*C-H]
    Euclidian distance = 4.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Adsorption_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;*C-H] for rate rule [CO2;*C-H]
Euclidian distance = 4.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Abstraction_vdW
""",
)

entry(
    index = 138,
    label = "HOX + CO2X <=> site + O=C(O)O[Pt]",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(9.32788e+15,'m^2/(mol*s)'), n=-0.257599, Ea=(73.2678,'kJ/mol'), T0=(1,'K'), Tmin=(303.03,'K'), Tmax=(2000,'K'), comment="""Estimated using template [O=C;HO*] for rate rule [O=C=O;HO*]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Addition_Single_vdW"""),
    longDesc = 
"""
Estimated using template [O=C;HO*] for rate rule [O=C=O;HO*]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Addition_Single_vdW
""",
)

entry(
    index = 139,
    label = "HOX + CO2X <=> site + O=C([Pt])OO",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(9.69133e+18,'m^2/(mol*s)'), n=-0.544242, Ea=(313.682,'kJ/mol'), T0=(1,'K'), Tmin=(303.03,'K'), Tmax=(2000,'K'), comment="""Estimated using template [CO2;Adsorbate1] for rate rule [CO2;HO*]
    Euclidian distance = 2.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Addition_Single_vdW
    Ea raised from 313.3 to 313.7 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [CO2;Adsorbate1] for rate rule [CO2;HO*]
Euclidian distance = 2.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Addition_Single_vdW
Ea raised from 313.3 to 313.7 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 140,
    label = "HOX + CO2X <=> OX + formyloxyX",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(3.628e+16,'m^2/(mol*s)'), n=0, Ea=(40.5238,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [O=C;Adsorbate1] for rate rule [O=C=O;*O-R]
    Euclidian distance = 1.4142135623730951
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Adsorption_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [O=C;Adsorbate1] for rate rule [O=C=O;*O-R]
Euclidian distance = 1.4142135623730951
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Abstraction_vdW
""",
)

entry(
    index = 141,
    label = "HOX + CO2X <=> OX + HOCXO",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(3.628e+16,'m^2/(mol*s)'), n=0, Ea=(40.5238,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [CO2;*O-R]
    Euclidian distance = 4.123105625617661
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Adsorption_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [CO2;*O-R]
Euclidian distance = 4.123105625617661
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Abstraction_vdW
""",
)

entry(
    index = 142,
    label = "O.[Pt] + CO2X <=> HOX + formyloxyX",
    degeneracy = 4.0,
    kinetics = SurfaceArrhenius(A=(2.81379e+10,'m^2/(mol*s)'), n=1.27097, Ea=(144.01,'kJ/mol'), T0=(1,'K'), Tmin=(303.03,'K'), Tmax=(2000,'K'), comment="""Estimated using template [Adsorbate1;O-R] for rate rule [O=C=O;O-R]
    Euclidian distance = 3.0
    Multiplied by reaction path degeneracy 4.0
    family: Surface_Dual_Adsorption_vdW"""),
    longDesc = 
"""
Estimated using template [Adsorbate1;O-R] for rate rule [O=C=O;O-R]
Euclidian distance = 3.0
Multiplied by reaction path degeneracy 4.0
family: Surface_Dual_Adsorption_vdW
""",
)

entry(
    index = 143,
    label = "HOX + HOCXO <=> O.[Pt] + CO2X",
    degeneracy = 4.0,
    kinetics = SurfaceArrhenius(A=(3.398e+17,'m^2/(mol*s)'), n=0, Ea=(0,'kcal/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Matched reaction 12 COOH* + OH* <=> CO2* + H2O* in Surface_Dual_Adsorption_vdW/training
    This reaction matched rate rule [CO2;O-R]
    family: Surface_Dual_Adsorption_vdW
    metal: None"""),
    longDesc = 
"""
Matched reaction 12 COOH* + OH* <=> CO2* + H2O* in Surface_Dual_Adsorption_vdW/training
This reaction matched rate rule [CO2;O-R]
family: Surface_Dual_Adsorption_vdW
metal: None
""",
)

entry(
    index = 144,
    label = "O.[Pt] + CO2X <=> HX + O=C(O)O[Pt]",
    degeneracy = 4.0,
    kinetics = SurfaceArrhenius(A=(2.81379e+10,'m^2/(mol*s)'), n=1.27097, Ea=(144.01,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Adsorbate1;Adsorbate2] for rate rule [O=C=O;Adsorbate2]
    Euclidian distance = 3.0
    Multiplied by reaction path degeneracy 4.0
    family: Surface_Dual_Adsorption_vdW"""),
    longDesc = 
"""
Estimated using template [Adsorbate1;Adsorbate2] for rate rule [O=C=O;Adsorbate2]
Euclidian distance = 3.0
Multiplied by reaction path degeneracy 4.0
family: Surface_Dual_Adsorption_vdW
""",
)

entry(
    index = 145,
    label = "O.[Pt] + CO2X <=> HX + O=C([Pt])OO",
    degeneracy = 4.0,
    kinetics = SurfaceArrhenius(A=(2.81379e+10,'m^2/(mol*s)'), n=1.27097, Ea=(350.516,'kJ/mol'), T0=(1,'K'), Tmin=(303.03,'K'), Tmax=(2000,'K'), comment="""Estimated using an average for rate rule [CO2;Adsorbate2]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 4.0
    family: Surface_Dual_Adsorption_vdW"""),
    longDesc = 
"""
Estimated using an average for rate rule [CO2;Adsorbate2]
Euclidian distance = 0
Multiplied by reaction path degeneracy 4.0
family: Surface_Dual_Adsorption_vdW
""",
)

entry(
    index = 146,
    label = "CO2X + C=O.[Pt] <=> CXHO + formyloxyX",
    degeneracy = 4.0,
    kinetics = SurfaceArrhenius(A=(2.81379e+10,'m^2/(mol*s)'), n=1.27097, Ea=(144.01,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Adsorbate1;Adsorbate2] for rate rule [O=C=O;C-R]
    Euclidian distance = 3.1622776601683795
    Multiplied by reaction path degeneracy 4.0
    family: Surface_Dual_Adsorption_vdW"""),
    longDesc = 
"""
Estimated using template [Adsorbate1;Adsorbate2] for rate rule [O=C=O;C-R]
Euclidian distance = 3.1622776601683795
Multiplied by reaction path degeneracy 4.0
family: Surface_Dual_Adsorption_vdW
""",
)

entry(
    index = 147,
    label = "CO2X + C=O.[Pt] <=> CXHO + HOCXO",
    degeneracy = 4.0,
    kinetics = SurfaceArrhenius(A=(2.81379e+10,'m^2/(mol*s)'), n=1.27097, Ea=(144.01,'kJ/mol'), T0=(1,'K'), Tmin=(303.03,'K'), Tmax=(2000,'K'), comment="""Estimated using template [CO2;Adsorbate2] for rate rule [CO2;C-R]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 4.0
    family: Surface_Dual_Adsorption_vdW"""),
    longDesc = 
"""
Estimated using template [CO2;Adsorbate2] for rate rule [CO2;C-R]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 4.0
family: Surface_Dual_Adsorption_vdW
""",
)

entry(
    index = 148,
    label = "CO2X + C=O.[Pt] <=> HX + O=CC(=O)O[Pt]",
    degeneracy = 4.0,
    kinetics = SurfaceArrhenius(A=(2.81379e+10,'m^2/(mol*s)'), n=1.27097, Ea=(144.01,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Adsorbate1;Adsorbate2] for rate rule [O=C=O;Adsorbate2]
    Euclidian distance = 3.0
    Multiplied by reaction path degeneracy 4.0
    family: Surface_Dual_Adsorption_vdW"""),
    longDesc = 
"""
Estimated using template [Adsorbate1;Adsorbate2] for rate rule [O=C=O;Adsorbate2]
Euclidian distance = 3.0
Multiplied by reaction path degeneracy 4.0
family: Surface_Dual_Adsorption_vdW
""",
)

entry(
    index = 149,
    label = "CO2X + C=O.[Pt] <=> HX + O=COC(=O)[Pt]",
    degeneracy = 4.0,
    kinetics = SurfaceArrhenius(A=(2.81379e+10,'m^2/(mol*s)'), n=1.27097, Ea=(144.01,'kJ/mol'), T0=(1,'K'), Tmin=(303.03,'K'), Tmax=(2000,'K'), comment="""Estimated using an average for rate rule [CO2;Adsorbate2]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 4.0
    family: Surface_Dual_Adsorption_vdW"""),
    longDesc = 
"""
Estimated using an average for rate rule [CO2;Adsorbate2]
Euclidian distance = 0
Multiplied by reaction path degeneracy 4.0
family: Surface_Dual_Adsorption_vdW
""",
)

entry(
    index = 150,
    label = "CO2X + CO[Pt] <=> site + COC(=O)O[Pt]",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(2.32584e+18,'m^2/(mol*s)'), n=0, Ea=(48.2427,'kJ/mol'), T0=(1,'K'), comment="""Estimated using average of templates [O=C;O*] + [O=C=O;Adsorbate1] for rate rule [O=C=O;O*]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Addition_Single_vdW"""),
    longDesc = 
"""
Estimated using average of templates [O=C;O*] + [O=C=O;Adsorbate1] for rate rule [O=C=O;O*]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Addition_Single_vdW
""",
)

entry(
    index = 151,
    label = "CO2X + CO[Pt] <=> site + COOC(=O)[Pt]",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(9.69133e+18,'m^2/(mol*s)'), n=-0.544242, Ea=(233.667,'kJ/mol'), T0=(1,'K'), Tmin=(303.03,'K'), Tmax=(2000,'K'), comment="""Estimated using template [CO2;Adsorbate1] for rate rule [CO2;O*]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Addition_Single_vdW
    Ea raised from 231.3 to 233.7 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [CO2;Adsorbate1] for rate rule [CO2;O*]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Addition_Single_vdW
Ea raised from 231.3 to 233.7 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 152,
    label = "CO2X + CO[Pt] <=> OX + acetyloxyX",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(3.628e+16,'m^2/(mol*s)'), n=0, Ea=(40.5238,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [O=C;Adsorbate1] for rate rule [O=C=O;*O-R]
    Euclidian distance = 1.4142135623730951
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Adsorption_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [O=C;Adsorbate1] for rate rule [O=C=O;*O-R]
Euclidian distance = 1.4142135623730951
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Abstraction_vdW
""",
)

entry(
    index = 153,
    label = "CO2X + CO[Pt] <=> OX + CH3OCOX",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(3.628e+16,'m^2/(mol*s)'), n=0, Ea=(40.5238,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [CO2;*O-R]
    Euclidian distance = 4.123105625617661
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Adsorption_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;Adsorbate1] for rate rule [CO2;*O-R]
Euclidian distance = 4.123105625617661
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Abstraction_vdW
""",
)

entry(
    index = 154,
    label = "CO2X + C.[Pt] <=> formyloxyX + C[Pt]",
    degeneracy = 8.0,
    kinetics = SurfaceArrhenius(A=(5.62758e+10,'m^2/(mol*s)'), n=1.27097, Ea=(144.01,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Adsorbate1;Adsorbate2] for rate rule [O=C=O;C-R]
    Euclidian distance = 3.1622776601683795
    Multiplied by reaction path degeneracy 8.0
    family: Surface_Dual_Adsorption_vdW"""),
    longDesc = 
"""
Estimated using template [Adsorbate1;Adsorbate2] for rate rule [O=C=O;C-R]
Euclidian distance = 3.1622776601683795
Multiplied by reaction path degeneracy 8.0
family: Surface_Dual_Adsorption_vdW
""",
)

entry(
    index = 155,
    label = "CO2X + C.[Pt] <=> HOCXO + C[Pt]",
    degeneracy = 8.0,
    kinetics = SurfaceArrhenius(A=(5.62758e+10,'m^2/(mol*s)'), n=1.27097, Ea=(144.01,'kJ/mol'), T0=(1,'K'), Tmin=(303.03,'K'), Tmax=(2000,'K'), comment="""Estimated using template [CO2;Adsorbate2] for rate rule [CO2;C-R]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 8.0
    family: Surface_Dual_Adsorption_vdW"""),
    longDesc = 
"""
Estimated using template [CO2;Adsorbate2] for rate rule [CO2;C-R]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 8.0
family: Surface_Dual_Adsorption_vdW
""",
)

entry(
    index = 156,
    label = "CO2X + C.[Pt] <=> HX + acetyloxyX",
    degeneracy = 8.0,
    kinetics = SurfaceArrhenius(A=(5.62758e+10,'m^2/(mol*s)'), n=1.27097, Ea=(144.01,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Adsorbate1;Adsorbate2] for rate rule [O=C=O;Adsorbate2]
    Euclidian distance = 3.0
    Multiplied by reaction path degeneracy 8.0
    family: Surface_Dual_Adsorption_vdW"""),
    longDesc = 
"""
Estimated using template [Adsorbate1;Adsorbate2] for rate rule [O=C=O;Adsorbate2]
Euclidian distance = 3.0
Multiplied by reaction path degeneracy 8.0
family: Surface_Dual_Adsorption_vdW
""",
)

entry(
    index = 157,
    label = "CO2X + C.[Pt] <=> HX + CH3OCOX",
    degeneracy = 8.0,
    kinetics = SurfaceArrhenius(A=(5.62758e+10,'m^2/(mol*s)'), n=1.27097, Ea=(144.01,'kJ/mol'), T0=(1,'K'), Tmin=(303.03,'K'), Tmax=(2000,'K'), comment="""Estimated using an average for rate rule [CO2;Adsorbate2]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 8.0
    family: Surface_Dual_Adsorption_vdW"""),
    longDesc = 
"""
Estimated using an average for rate rule [CO2;Adsorbate2]
Euclidian distance = 0
Multiplied by reaction path degeneracy 8.0
family: Surface_Dual_Adsorption_vdW
""",
)

entry(
    index = 158,
    label = "CO2X + C[Pt] <=> site + acetyloxyX",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(1.243e+18,'m^2/(mol*s)'), n=0, Ea=(83.9422,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Estimated using template [O=C=O;Adsorbate1] for rate rule [O=C=O;C*]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Addition_Single_vdW"""),
    longDesc = 
"""
Estimated using template [O=C=O;Adsorbate1] for rate rule [O=C=O;C*]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Addition_Single_vdW
""",
)

entry(
    index = 159,
    label = "CO2X + C[Pt] <=> site + CH3OCOX",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(A=(9.69133e+18,'m^2/(mol*s)'), n=-0.544242, Ea=(189.782,'kJ/mol'), T0=(1,'K'), Tmin=(303.03,'K'), Tmax=(2000,'K'), comment="""Estimated using template [CO2;Adsorbate1] for rate rule [CO2;C*]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Addition_Single_vdW"""),
    longDesc = 
"""
Estimated using template [CO2;Adsorbate1] for rate rule [CO2;C*]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Addition_Single_vdW
""",
)

entry(
    index = 160,
    label = "CO2X + C[Pt] <=> formyloxyX + C=[Pt]",
    degeneracy = 6.0,
    kinetics = SurfaceArrhenius(A=(1.0884e+17,'m^2/(mol*s)'), n=0, Ea=(111.978,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [O=C;*C-H] for rate rule [O=C=O;*C-H]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 6.0
    family: Surface_Adsorption_Abstraction_vdW"""),
    longDesc = 
"""
Estimated using template [O=C;*C-H] for rate rule [O=C=O;*C-H]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 6.0
family: Surface_Adsorption_Abstraction_vdW
""",
)

entry(
    index = 161,
    label = "CO2X + C[Pt] <=> HOCXO + C=[Pt]",
    degeneracy = 6.0,
    kinetics = SurfaceArrhenius(A=(1.0884e+17,'m^2/(mol*s)'), n=0, Ea=(85.0559,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Estimated using template [AdsorbateVdW;*C-H] for rate rule [CO2;*C-H]
    Euclidian distance = 4.0
    Multiplied by reaction path degeneracy 6.0
    family: Surface_Adsorption_Abstraction_vdW
    Ea raised from 84.0 to 85.1 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [AdsorbateVdW;*C-H] for rate rule [CO2;*C-H]
Euclidian distance = 4.0
Multiplied by reaction path degeneracy 6.0
family: Surface_Adsorption_Abstraction_vdW
Ea raised from 84.0 to 85.1 kJ/mol to match endothermicity of reaction.
""",
)

