#!/usr/bin/env python
# encoding: utf-8

name = "seed"
shortDesc = ""
longDesc = """

"""
autoGenerated=True
entry(
    index = 0,
    label = "[O]O + C[CH]CCC <=> oxygen + pentane",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.75906e-08,'m^3/(mol*s)'), n=3.80154, Ea=(26.4597,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [X_H;C_rad/H/NonDeC] for rate rule [Orad_O_H;C_rad/H/NonDeC]
    Euclidian distance = 2.0
    family: H_Abstraction"""),
    longDesc = 
"""
Estimated using template [X_H;C_rad/H/NonDeC] for rate rule [Orad_O_H;C_rad/H/NonDeC]
Euclidian distance = 2.0
family: H_Abstraction
""",
)

entry(
    index = 1,
    label = "[O]O + CC[CH]CC <=> oxygen + pentane",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.75906e-08,'m^3/(mol*s)'), n=3.80154, Ea=(26.4597,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [X_H;C_rad/H/NonDeC] for rate rule [Orad_O_H;C_rad/H/NonDeC]
    Euclidian distance = 2.0
    family: H_Abstraction"""),
    longDesc = 
"""
Estimated using template [X_H;C_rad/H/NonDeC] for rate rule [Orad_O_H;C_rad/H/NonDeC]
Euclidian distance = 2.0
family: H_Abstraction
""",
)

entry(
    index = 2,
    label = "CC[CH]CC <=> C[CH]CCC",
    degeneracy = 4.0,
    kinetics = Arrhenius(A=(1.352e+10,'s^-1'), n=0.88, Ea=(158.992,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), comment="""From training reaction 357 used for R2H_S;C_rad_out_H/NonDeC;Cs_H_out_H/NonDeC
    Exact match found for rate rule [R2H_S;C_rad_out_H/NonDeC;Cs_H_out_H/NonDeC]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 4.0
    family: intra_H_migration"""),
    longDesc = 
"""
From training reaction 357 used for R2H_S;C_rad_out_H/NonDeC;Cs_H_out_H/NonDeC
Exact match found for rate rule [R2H_S;C_rad_out_H/NonDeC;Cs_H_out_H/NonDeC]
Euclidian distance = 0
Multiplied by reaction path degeneracy 4.0
family: intra_H_migration
""",
)

entry(
    index = 3,
    label = "CC[CH]CC + pentane <=> C[CH]CCC + pentane",
    degeneracy = 4.0,
    kinetics = Arrhenius(A=(5.1475e-09,'m^3/(mol*s)'), n=4.29, Ea=(32.2691,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [C/H2/NonDeC;C_rad/H/NonDeC]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 4.0
    family: H_Abstraction"""),
    longDesc = 
"""
Estimated using an average for rate rule [C/H2/NonDeC;C_rad/H/NonDeC]
Euclidian distance = 0
Multiplied by reaction path degeneracy 4.0
family: H_Abstraction
""",
)

entry(
    index = 4,
    label = "[O]O + [CH2]CCCC <=> oxygen + pentane",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.06232e-06,'m^3/(mol*s)'), n=3.29519, Ea=(39.1374,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [X_H;C_rad/H2/Cs] for rate rule [Orad_O_H;C_rad/H2/Cs]
    Euclidian distance = 2.0
    family: H_Abstraction"""),
    longDesc = 
"""
Estimated using template [X_H;C_rad/H2/Cs] for rate rule [Orad_O_H;C_rad/H2/Cs]
Euclidian distance = 2.0
family: H_Abstraction
""",
)

entry(
    index = 5,
    label = "[CH2]CCCC <=> C[CH]CCC",
    degeneracy = 2.0,
    duplicate = True,
    kinetics = Arrhenius(A=(3.22e+09,'s^-1'), n=0.13, Ea=(86.6088,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), comment="""Matched reaction 131 C5H11 <=> C5H11-2 in intra_H_migration/training
    This reaction matched rate rule [R2H_S;C_rad_out_H/NonDeC;Cs_H_out_2H]
    family: intra_H_migration"""),
    longDesc = 
"""
Matched reaction 131 C5H11 <=> C5H11-2 in intra_H_migration/training
This reaction matched rate rule [R2H_S;C_rad_out_H/NonDeC;Cs_H_out_2H]
family: intra_H_migration
""",
)

entry(
    index = 6,
    label = "[CH2]CCCC <=> C[CH]CCC",
    degeneracy = 2.0,
    duplicate = True,
    kinetics = Arrhenius(A=(3.22e+09,'s^-1'), n=0.13, Ea=(86.6088,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), comment="""Matched reaction 131 C5H11 <=> C5H11-2 in intra_H_migration/training
    This reaction matched rate rule [R4H_SSS;C_rad_out_H/NonDeC;Cs_H_out_2H]
    family: intra_H_migration"""),
    longDesc = 
"""
Matched reaction 131 C5H11 <=> C5H11-2 in intra_H_migration/training
This reaction matched rate rule [R4H_SSS;C_rad_out_H/NonDeC;Cs_H_out_2H]
family: intra_H_migration
""",
)

entry(
    index = 7,
    label = "[CH2]CCCC + pentane <=> C[CH]CCC + pentane",
    degeneracy = 4.0,
    kinetics = Arrhenius(A=(4.32773e-09,'m^3/(mol*s)'), n=4.29, Ea=(31.5317,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [C/H2/NonDeC;C_rad/H2/Cs]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 4.0
    family: H_Abstraction"""),
    longDesc = 
"""
Estimated using an average for rate rule [C/H2/NonDeC;C_rad/H2/Cs]
Euclidian distance = 0
Multiplied by reaction path degeneracy 4.0
family: H_Abstraction
""",
)

entry(
    index = 8,
    label = "[CH2]CCCC <=> CC[CH]CC",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(1.064e+06,'s^-1'), n=1.93, Ea=(33.8,'kcal/mol'), T0=(1,'K'), comment="""Matched reaction 108 CCCC[CH2] <=> CC[CH]CC in intra_H_migration/training
    This reaction matched rate rule [R3H_SS_Cs;C_rad_out_H/NonDeC;Cs_H_out_2H]
    family: intra_H_migration"""),
    longDesc = 
"""
Matched reaction 108 CCCC[CH2] <=> CC[CH]CC in intra_H_migration/training
This reaction matched rate rule [R3H_SS_Cs;C_rad_out_H/NonDeC;Cs_H_out_2H]
family: intra_H_migration
""",
)

entry(
    index = 9,
    label = "[CH2]CCCC + pentane <=> CC[CH]CC + pentane",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(2.16387e-09,'m^3/(mol*s)'), n=4.29, Ea=(31.5317,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [C/H2/NonDeC;C_rad/H2/Cs]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: H_Abstraction"""),
    longDesc = 
"""
Estimated using an average for rate rule [C/H2/NonDeC;C_rad/H2/Cs]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: H_Abstraction
""",
)

entry(
    index = 10,
    label = "[CH2]CCCC <=> C[CH]CCC",
    degeneracy = 2.0,
    duplicate = True,
    kinetics = Arrhenius(A=(3.22e+09,'s^-1'), n=0.13, Ea=(86.6088,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), comment="""Matched reaction 131 C5H11 <=> C5H11-2 in intra_H_migration/training
    This reaction matched rate rule [R2H_S;C_rad_out_2H;Cs_H_out_H/(NonDeC/Cs)]
    family: intra_H_migration"""),
    longDesc = 
"""
Matched reaction 131 C5H11 <=> C5H11-2 in intra_H_migration/training
This reaction matched rate rule [R2H_S;C_rad_out_2H;Cs_H_out_H/(NonDeC/Cs)]
family: intra_H_migration
""",
)

entry(
    index = 11,
    label = "[CH2]CCCC <=> C[CH]CCC",
    degeneracy = 2.0,
    duplicate = True,
    kinetics = Arrhenius(A=(3.22e+09,'s^-1'), n=0.13, Ea=(86.6088,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), comment="""Matched reaction 131 C5H11 <=> C5H11-2 in intra_H_migration/training
    This reaction matched rate rule [R4H_SSS;C_rad_out_2H;Cs_H_out_H/NonDeC]
    family: intra_H_migration"""),
    longDesc = 
"""
Matched reaction 131 C5H11 <=> C5H11-2 in intra_H_migration/training
This reaction matched rate rule [R4H_SSS;C_rad_out_2H;Cs_H_out_H/NonDeC]
family: intra_H_migration
""",
)

entry(
    index = 12,
    label = "oxygen + C[CH]CCC <=> CCCC(C)O[O]",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(1.21695e+08,'m^3/(mol*s)'), n=-0.428622, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=0.0, var=33.1368631905, Tref=1000.0, N=1, correlation='Root_N-1R->H_N-1CNOS->N_1COS->O_Ext-1O-R_Ext-2R-R_Ext-4R!H-R_Ext-2R-R_N-2R-inRing',), comment="""BM rule fitted to 2 training reactions at node Root_N-1R->H_N-1CNOS->N_1COS->O_Ext-1O-R_Ext-2R-R_Ext-4R!H-R_Ext-2R-R_N-2R-inRing
        Total Standard Deviation in ln(k): 11.5401827615
    Exact match found for rate rule [Root_N-1R->H_N-1CNOS->N_1COS->O_Ext-1O-R_Ext-2R-R_Ext-4R!H-R_Ext-2R-R_N-2R-inRing]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: R_Recombination"""),
    longDesc = 
"""
BM rule fitted to 2 training reactions at node Root_N-1R->H_N-1CNOS->N_1COS->O_Ext-1O-R_Ext-2R-R_Ext-4R!H-R_Ext-2R-R_N-2R-inRing
    Total Standard Deviation in ln(k): 11.5401827615
Exact match found for rate rule [Root_N-1R->H_N-1CNOS->N_1COS->O_Ext-1O-R_Ext-2R-R_Ext-4R!H-R_Ext-2R-R_N-2R-inRing]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: R_Recombination
""",
)

entry(
    index = 13,
    label = "oxygen + CC[CH]CC <=> CCC(CC)O[O]",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(1.21695e+08,'m^3/(mol*s)'), n=-0.428622, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=0.0, var=33.1368631905, Tref=1000.0, N=1, correlation='Root_N-1R->H_N-1CNOS->N_1COS->O_Ext-1O-R_Ext-2R-R_Ext-4R!H-R_Ext-2R-R_N-2R-inRing',), comment="""BM rule fitted to 2 training reactions at node Root_N-1R->H_N-1CNOS->N_1COS->O_Ext-1O-R_Ext-2R-R_Ext-4R!H-R_Ext-2R-R_N-2R-inRing
        Total Standard Deviation in ln(k): 11.5401827615
    Exact match found for rate rule [Root_N-1R->H_N-1CNOS->N_1COS->O_Ext-1O-R_Ext-2R-R_Ext-4R!H-R_Ext-2R-R_N-2R-inRing]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: R_Recombination"""),
    longDesc = 
"""
BM rule fitted to 2 training reactions at node Root_N-1R->H_N-1CNOS->N_1COS->O_Ext-1O-R_Ext-2R-R_Ext-4R!H-R_Ext-2R-R_N-2R-inRing
    Total Standard Deviation in ln(k): 11.5401827615
Exact match found for rate rule [Root_N-1R->H_N-1CNOS->N_1COS->O_Ext-1O-R_Ext-2R-R_Ext-4R!H-R_Ext-2R-R_N-2R-inRing]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: R_Recombination
""",
)

entry(
    index = 14,
    label = "[O]O + C[CH]CCC <=> CCCC(C)OO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.08474e+07,'m^3/(mol*s)'), n=-0.428622, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=0.0, var=33.1368631905, Tref=1000.0, N=1, correlation='Root_N-1R->H_N-1CNOS->N_1COS->O_Ext-1O-R_Ext-2R-R_Ext-4R!H-R_Ext-2R-R_N-2R-inRing',), comment="""BM rule fitted to 2 training reactions at node Root_N-1R->H_N-1CNOS->N_1COS->O_Ext-1O-R_Ext-2R-R_Ext-4R!H-R_Ext-2R-R_N-2R-inRing
        Total Standard Deviation in ln(k): 11.5401827615
    Exact match found for rate rule [Root_N-1R->H_N-1CNOS->N_1COS->O_Ext-1O-R_Ext-2R-R_Ext-4R!H-R_Ext-2R-R_N-2R-inRing]
    Euclidian distance = 0
    family: R_Recombination"""),
    longDesc = 
"""
BM rule fitted to 2 training reactions at node Root_N-1R->H_N-1CNOS->N_1COS->O_Ext-1O-R_Ext-2R-R_Ext-4R!H-R_Ext-2R-R_N-2R-inRing
    Total Standard Deviation in ln(k): 11.5401827615
Exact match found for rate rule [Root_N-1R->H_N-1CNOS->N_1COS->O_Ext-1O-R_Ext-2R-R_Ext-4R!H-R_Ext-2R-R_N-2R-inRing]
Euclidian distance = 0
family: R_Recombination
""",
)

entry(
    index = 15,
    label = "CC[CH]CC + CCCC(C)OO <=> CCCC(C)O[O] + pentane",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.51e-11,'cm^3/(mol*s)'), n=6.77, Ea=(-35.9824,'kJ/mol'), T0=(1,'K'), Tmin=(500,'K'), Tmax=(1000,'K'), comment="""Estimated using an average for rate rule [ROOH_sec;C_rad/H/NonDeC]
    Euclidian distance = 0
    family: H_Abstraction
    Ea raised from -36.0 to -36.0 kJ/mol."""),
    longDesc = 
"""
Estimated using an average for rate rule [ROOH_sec;C_rad/H/NonDeC]
Euclidian distance = 0
family: H_Abstraction
Ea raised from -36.0 to -36.0 kJ/mol.
""",
)

entry(
    index = 16,
    label = "C[CH]CCC + CCCC(C)OO <=> CCCC(C)O[O] + pentane",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.51e-11,'cm^3/(mol*s)'), n=6.77, Ea=(-35.9824,'kJ/mol'), T0=(1,'K'), Tmin=(500,'K'), Tmax=(1000,'K'), comment="""Estimated using an average for rate rule [ROOH_sec;C_rad/H/NonDeC]
    Euclidian distance = 0
    family: H_Abstraction
    Ea raised from -36.0 to -36.0 kJ/mol."""),
    longDesc = 
"""
Estimated using an average for rate rule [ROOH_sec;C_rad/H/NonDeC]
Euclidian distance = 0
family: H_Abstraction
Ea raised from -36.0 to -36.0 kJ/mol.
""",
)

entry(
    index = 17,
    label = "[CH2]CCCC + CCCC(C)OO <=> CCCC(C)O[O] + pentane",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.51e-11,'cm^3/(mol*s)'), n=6.77, Ea=(-35.9824,'kJ/mol'), T0=(1,'K'), Tmin=(500,'K'), Tmax=(1000,'K'), comment="""Estimated using an average for rate rule [ROOH_sec;C_rad/H2/Cs]
    Euclidian distance = 0
    family: H_Abstraction
    Ea raised from -36.0 to -36.0 kJ/mol."""),
    longDesc = 
"""
Estimated using an average for rate rule [ROOH_sec;C_rad/H2/Cs]
Euclidian distance = 0
family: H_Abstraction
Ea raised from -36.0 to -36.0 kJ/mol.
""",
)

entry(
    index = 18,
    label = "[O]O + CCCC(C)O[O] <=> oxygen + CCCC(C)OO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.2e+11,'cm^3/(mol*s)'), n=0, Ea=(-8.1588,'kJ/mol'), T0=(1,'K'), comment="""From training reaction 244 used for Orad_O_H;OOC
    Exact match found for rate rule [Orad_O_H;OOC]
    Euclidian distance = 0
    family: H_Abstraction
    Ea raised from -8.2 to -8.2 kJ/mol."""),
    longDesc = 
"""
From training reaction 244 used for Orad_O_H;OOC
Exact match found for rate rule [Orad_O_H;OOC]
Euclidian distance = 0
family: H_Abstraction
Ea raised from -8.2 to -8.2 kJ/mol.
""",
)

entry(
    index = 19,
    label = "[O]O + CC[CH]CC <=> CCC(CC)OO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.08474e+07,'m^3/(mol*s)'), n=-0.428622, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=0.0, var=33.1368631905, Tref=1000.0, N=1, correlation='Root_N-1R->H_N-1CNOS->N_1COS->O_Ext-1O-R_Ext-2R-R_Ext-4R!H-R_Ext-2R-R_N-2R-inRing',), comment="""BM rule fitted to 2 training reactions at node Root_N-1R->H_N-1CNOS->N_1COS->O_Ext-1O-R_Ext-2R-R_Ext-4R!H-R_Ext-2R-R_N-2R-inRing
        Total Standard Deviation in ln(k): 11.5401827615
    Exact match found for rate rule [Root_N-1R->H_N-1CNOS->N_1COS->O_Ext-1O-R_Ext-2R-R_Ext-4R!H-R_Ext-2R-R_N-2R-inRing]
    Euclidian distance = 0
    family: R_Recombination"""),
    longDesc = 
"""
BM rule fitted to 2 training reactions at node Root_N-1R->H_N-1CNOS->N_1COS->O_Ext-1O-R_Ext-2R-R_Ext-4R!H-R_Ext-2R-R_N-2R-inRing
    Total Standard Deviation in ln(k): 11.5401827615
Exact match found for rate rule [Root_N-1R->H_N-1CNOS->N_1COS->O_Ext-1O-R_Ext-2R-R_Ext-4R!H-R_Ext-2R-R_N-2R-inRing]
Euclidian distance = 0
family: R_Recombination
""",
)

entry(
    index = 20,
    label = "CC[CH]CC + CCC(CC)OO <=> CCC(CC)O[O] + pentane",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.51e-11,'cm^3/(mol*s)'), n=6.77, Ea=(-35.9824,'kJ/mol'), T0=(1,'K'), Tmin=(500,'K'), Tmax=(1000,'K'), comment="""Estimated using an average for rate rule [ROOH_sec;C_rad/H/NonDeC]
    Euclidian distance = 0
    family: H_Abstraction
    Ea raised from -36.0 to -36.0 kJ/mol."""),
    longDesc = 
"""
Estimated using an average for rate rule [ROOH_sec;C_rad/H/NonDeC]
Euclidian distance = 0
family: H_Abstraction
Ea raised from -36.0 to -36.0 kJ/mol.
""",
)

entry(
    index = 21,
    label = "C[CH]CCC + CCC(CC)OO <=> CCC(CC)O[O] + pentane",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.51e-11,'cm^3/(mol*s)'), n=6.77, Ea=(-35.9824,'kJ/mol'), T0=(1,'K'), Tmin=(500,'K'), Tmax=(1000,'K'), comment="""Estimated using an average for rate rule [ROOH_sec;C_rad/H/NonDeC]
    Euclidian distance = 0
    family: H_Abstraction
    Ea raised from -36.0 to -36.0 kJ/mol."""),
    longDesc = 
"""
Estimated using an average for rate rule [ROOH_sec;C_rad/H/NonDeC]
Euclidian distance = 0
family: H_Abstraction
Ea raised from -36.0 to -36.0 kJ/mol.
""",
)

entry(
    index = 22,
    label = "[CH2]CCCC + CCC(CC)OO <=> CCC(CC)O[O] + pentane",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.51e-11,'cm^3/(mol*s)'), n=6.77, Ea=(-35.9824,'kJ/mol'), T0=(1,'K'), Tmin=(500,'K'), Tmax=(1000,'K'), comment="""Estimated using an average for rate rule [ROOH_sec;C_rad/H2/Cs]
    Euclidian distance = 0
    family: H_Abstraction
    Ea raised from -36.0 to -36.0 kJ/mol."""),
    longDesc = 
"""
Estimated using an average for rate rule [ROOH_sec;C_rad/H2/Cs]
Euclidian distance = 0
family: H_Abstraction
Ea raised from -36.0 to -36.0 kJ/mol.
""",
)

entry(
    index = 23,
    label = "[O]O + CCC(CC)O[O] <=> oxygen + CCC(CC)OO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.2e+11,'cm^3/(mol*s)'), n=0, Ea=(-8.1588,'kJ/mol'), T0=(1,'K'), comment="""From training reaction 244 used for Orad_O_H;OOC
    Exact match found for rate rule [Orad_O_H;OOC]
    Euclidian distance = 0
    family: H_Abstraction
    Ea raised from -8.2 to -8.2 kJ/mol."""),
    longDesc = 
"""
From training reaction 244 used for Orad_O_H;OOC
Exact match found for rate rule [Orad_O_H;OOC]
Euclidian distance = 0
family: H_Abstraction
Ea raised from -8.2 to -8.2 kJ/mol.
""",
)

entry(
    index = 24,
    label = "CCCC(C)O[O] + CCC(CC)OO <=> CCC(CC)O[O] + CCCC(C)OO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.092,'cm^3/(mol*s)','*|/',3), n=3.96, Ea=(27.7399,'kJ/mol'), T0=(1,'K'), Tmin=(600,'K'), Tmax=(2000,'K'), comment="""Estimated using template [O/H/NonDeO;OOC] for rate rule [ROOH_sec;OOC]
    Euclidian distance = 1.0
    family: H_Abstraction"""),
    longDesc = 
"""
Estimated using template [O/H/NonDeO;OOC] for rate rule [ROOH_sec;OOC]
Euclidian distance = 1.0
family: H_Abstraction
""",
)

entry(
    index = 25,
    label = "oxygen + [CH2]CCCC <=> CCCCCO[O]",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(2.96276e+06,'m^3/(mol*s)'), n=-0.119415, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=0.0, var=33.1368631905, Tref=1000.0, N=1, correlation='Root_N-1R->H_N-1CNOS->N_1COS->O_Ext-1O-R_Ext-2R-R_Ext-4R!H-R_Sp-4R!H-2R_Sp-5R!H-4R!H',), comment="""BM rule fitted to 2 training reactions at node Root_N-1R->H_N-1CNOS->N_1COS->O_Ext-1O-R_Ext-2R-R_Ext-4R!H-R_Sp-4R!H-2R_Sp-5R!H-4R!H
        Total Standard Deviation in ln(k): 11.5401827615
    Exact match found for rate rule [Root_N-1R->H_N-1CNOS->N_1COS->O_Ext-1O-R_Ext-2R-R_Ext-4R!H-R_Sp-4R!H-2R_Sp-5R!H-4R!H]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: R_Recombination"""),
    longDesc = 
"""
BM rule fitted to 2 training reactions at node Root_N-1R->H_N-1CNOS->N_1COS->O_Ext-1O-R_Ext-2R-R_Ext-4R!H-R_Sp-4R!H-2R_Sp-5R!H-4R!H
    Total Standard Deviation in ln(k): 11.5401827615
Exact match found for rate rule [Root_N-1R->H_N-1CNOS->N_1COS->O_Ext-1O-R_Ext-2R-R_Ext-4R!H-R_Sp-4R!H-2R_Sp-5R!H-4R!H]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: R_Recombination
""",
)

entry(
    index = 26,
    label = "[O]O + [CH2]CCCC <=> CCCCCOO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(308.407,'m^3/(mol*s)'), n=0.967216, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=-0.0049236047651, var=0.0302625193734, Tref=1000.0, N=3, correlation='Root_N-1R->H_N-1CNOS->N_1COS->O_Ext-1O-R_Ext-2R-R_Ext-4R!H-R_Sp-4R!H-2R',), comment="""BM rule fitted to 2 training reactions at node Root_N-1R->H_N-1CNOS->N_1COS->O_Ext-1O-R_Ext-2R-R_Ext-4R!H-R_Sp-4R!H-2R
        Total Standard Deviation in ln(k): 0.361117102774
    Exact match found for rate rule [Root_N-1R->H_N-1CNOS->N_1COS->O_Ext-1O-R_Ext-2R-R_Ext-4R!H-R_Sp-4R!H-2R]
    Euclidian distance = 0
    family: R_Recombination"""),
    longDesc = 
"""
BM rule fitted to 2 training reactions at node Root_N-1R->H_N-1CNOS->N_1COS->O_Ext-1O-R_Ext-2R-R_Ext-4R!H-R_Sp-4R!H-2R
    Total Standard Deviation in ln(k): 0.361117102774
Exact match found for rate rule [Root_N-1R->H_N-1CNOS->N_1COS->O_Ext-1O-R_Ext-2R-R_Ext-4R!H-R_Sp-4R!H-2R]
Euclidian distance = 0
family: R_Recombination
""",
)

entry(
    index = 27,
    label = "CC[CH]CC + CCCCCOO <=> CCCCCO[O] + pentane",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.51e-11,'cm^3/(mol*s)'), n=6.77, Ea=(-35.9824,'kJ/mol'), T0=(1,'K'), Tmin=(500,'K'), Tmax=(1000,'K'), comment="""Estimated using an average for rate rule [ROOH_pri;C_rad/H/NonDeC]
    Euclidian distance = 0
    family: H_Abstraction
    Ea raised from -36.0 to -36.0 kJ/mol."""),
    longDesc = 
"""
Estimated using an average for rate rule [ROOH_pri;C_rad/H/NonDeC]
Euclidian distance = 0
family: H_Abstraction
Ea raised from -36.0 to -36.0 kJ/mol.
""",
)

entry(
    index = 28,
    label = "C[CH]CCC + CCCCCOO <=> CCCCCO[O] + pentane",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.51e-11,'cm^3/(mol*s)'), n=6.77, Ea=(-35.9824,'kJ/mol'), T0=(1,'K'), Tmin=(500,'K'), Tmax=(1000,'K'), comment="""Estimated using an average for rate rule [ROOH_pri;C_rad/H/NonDeC]
    Euclidian distance = 0
    family: H_Abstraction
    Ea raised from -36.0 to -36.0 kJ/mol."""),
    longDesc = 
"""
Estimated using an average for rate rule [ROOH_pri;C_rad/H/NonDeC]
Euclidian distance = 0
family: H_Abstraction
Ea raised from -36.0 to -36.0 kJ/mol.
""",
)

entry(
    index = 29,
    label = "[CH2]CCCC + CCCCCOO <=> CCCCCO[O] + pentane",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.51e-11,'cm^3/(mol*s)'), n=6.77, Ea=(-35.9824,'kJ/mol'), T0=(1,'K'), Tmin=(500,'K'), Tmax=(1000,'K'), comment="""Estimated using an average for rate rule [ROOH_pri;C_rad/H2/Cs]
    Euclidian distance = 0
    family: H_Abstraction
    Ea raised from -36.0 to -36.0 kJ/mol."""),
    longDesc = 
"""
Estimated using an average for rate rule [ROOH_pri;C_rad/H2/Cs]
Euclidian distance = 0
family: H_Abstraction
Ea raised from -36.0 to -36.0 kJ/mol.
""",
)

entry(
    index = 30,
    label = "[O]O + CCCCCO[O] <=> oxygen + CCCCCOO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.2e+11,'cm^3/(mol*s)'), n=0, Ea=(-8.1588,'kJ/mol'), T0=(1,'K'), comment="""From training reaction 244 used for Orad_O_H;OOC
    Exact match found for rate rule [Orad_O_H;OOC]
    Euclidian distance = 0
    family: H_Abstraction
    Ea raised from -8.2 to -8.2 kJ/mol."""),
    longDesc = 
"""
From training reaction 244 used for Orad_O_H;OOC
Exact match found for rate rule [Orad_O_H;OOC]
Euclidian distance = 0
family: H_Abstraction
Ea raised from -8.2 to -8.2 kJ/mol.
""",
)

entry(
    index = 31,
    label = "CCCC(C)O[O] + CCCCCOO <=> CCCCCO[O] + CCCC(C)OO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.092,'cm^3/(mol*s)','*|/',3), n=3.96, Ea=(27.7399,'kJ/mol'), T0=(1,'K'), Tmin=(600,'K'), Tmax=(2000,'K'), comment="""Estimated using template [O/H/NonDeO;OOC] for rate rule [ROOH_pri;OOC]
    Euclidian distance = 1.0
    family: H_Abstraction"""),
    longDesc = 
"""
Estimated using template [O/H/NonDeO;OOC] for rate rule [ROOH_pri;OOC]
Euclidian distance = 1.0
family: H_Abstraction
""",
)

entry(
    index = 32,
    label = "CCC(CC)O[O] + CCCCCOO <=> CCCCCO[O] + CCC(CC)OO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.092,'cm^3/(mol*s)','*|/',3), n=3.96, Ea=(27.7399,'kJ/mol'), T0=(1,'K'), Tmin=(600,'K'), Tmax=(2000,'K'), comment="""Estimated using template [O/H/NonDeO;OOC] for rate rule [ROOH_pri;OOC]
    Euclidian distance = 1.0
    family: H_Abstraction"""),
    longDesc = 
"""
Estimated using template [O/H/NonDeO;OOC] for rate rule [ROOH_pri;OOC]
Euclidian distance = 1.0
family: H_Abstraction
""",
)

